### PR TITLE
Exponential Back Off now retry query in case of `ConnectionException`

### LINKED ISSUE #4310: [Sync] ExponentialBackoffTask not retrying
`ExponentialBackoffTask` should retry the query with incremental backoff.

However, if you use `Airplane mode` in the device, the OkHttp query will fail, with an unknown `-1` code causing the `ExponentialBackoffTask` no to retry when the network is back 

```
03-10 14:50:23.002  1732  1810 E REALM_JAVA: Unrecoverable error, while refreshing the access Token (UNKNOWN(-1)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: java.net.ConnectException: Failed to connect to /172.19.216.95:9080
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at okhttp3.RealCall.execute(RealCall.java:60)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at io.realm.internal.network.OkHttpAuthenticationServer.authenticate(OkHttpAuthenticationServer.java:110)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at io.realm.internal.network.OkHttpAuthenticationServer.refreshUser(OkHttpAuthenticationServer.java:73)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at io.realm.SyncSession$4.execute(SyncSession.java:264)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at io.realm.SyncSession$4.execute(SyncSession.java:260)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at io.realm.internal.network.ExponentialBackoffTask.run(ExponentialBackoffTask.java:66)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: 	at java.lang.Thread.run(Thread.java:818)
03-10 14:50:23.002  1732  1810 E REALM_JAVA: ) reschedule will not happen

```

### PR DESCRIPTION
**Pull request by nhachicha**
`ConnectionException` which is a network error, was being treated as an `ErrorCode.UNKNOWN` instead of `ErrorCode.IO_EXCEPTION`which allow retrying.

fixes #4310

### CODE REVIEW

File: realm/realm-library/src/objectServer/java/io/realm/internal/network/OkHttpAuthenticationServer.java [hunk 1]
```diff
@@ -54,7 +55,9 @@ public AuthenticateResponse loginUser(SyncCredentials credentials, URL authentic
             String requestBody = AuthenticateRequest.userLogin(credentials).toJson();
             return authenticate(authenticationUrl, requestBody);
         } catch (Exception e) {
-            return AuthenticateResponse.from(new ObjectServerError(ErrorCode.UNKNOWN, e));
+            // ConnectException is recoverable (with exponential backoff)
+            ErrorCode errorCode = (e instanceof ConnectException) ? ErrorCode.IO_EXCEPTION : ErrorCode.UNKNOWN;
+            return AuthenticateResponse.from(new ObjectServerError(errorCode, e));
```
Comment (zaki50) [inline realm/realm-library/src/objectServer/java/io/realm/internal/network/OkHttpAuthenticationServer.java]: Shouldn't we create a utility method which creates `AuthenticateResponse` from `Exception`?

Comment (cmelchior) [inline realm/realm-library/src/objectServer/java/io/realm/internal/network/OkHttpAuthenticationServer.java]: Wouldn't it be more relevant to have a utility method that mapped between Exception and ErrorCode? Since this is being used for both authenticate/changepassword/logout and probably future ones as well.
