### PR TITLE
Free the SharedRealm in phantom daemon

### LINKED ISSUE #3730: NullPointerException: Null reference used for synchronization. SharedRealm.finalize()
#### Actual Results

> E/System: Uncaught exception thrown by finalizer
> E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
> 	at io.realm.internal.SharedRealm.finalize(SharedRealm.java:318)
> 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:217)
> 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
> 	at java.lang.Thread.run(Thread.java:818)

#### Steps & Code to Reproduce

>Was reproduced by client. Appeared multiple times in logcat.
>"Once in a while a popup error message is shown telling that the app has crashed."

#### Version of Realm and tooling
Realm version(s): 2.0.2

Realm sync feature enabled: no

Which Android version and device: Samsung Galaxy A5 (Android 6.0.1)

### PR DESCRIPTION
**Pull request by beeender**
Treat the SharedRealm the same as other native objects.
SharedRealm.close will only call Object Store Realm::close without
deleting the ShareRealm pointer.
Then we don't need the finalizer anymore. Fix #3730 .
This is related with
https://github.com/realm/realm-object-store/pull/318
as well. It is possible that java close the Realm in any of the Object Store's 
callbacks. To avoid Object Store operating on a invalid SharedRealm
pointer, binding should try to make sure after callbacks. However, it
cannot be totally avoided since user could set the Realm instance to
null and the instance can be GCed at any time. It is still something
should be considered in the Object Store implementation.

### CODE REVIEW

**Comment by Zhuinden** [comment]
Does this mean your Realm instances can get released even if you don't explicitly call `close()` on them?

**Comment by beeender** [comment]
@Zhuinden Actually it was released even before in the `finalize()`. But still, explicit call to `close()` is necessary since `SharedRealm` will bypass the `RealmCache`.

File: realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java [hunk 1]
```diff
@@ -215,10 +217,6 @@ public static SharedRealm getInstance(RealmConfiguration config, RealmNotifier r
         }
     }
 
-    long getNativePtr() {
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java]: Just moving it.

File: realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp [hunk 2]
```diff
@@ -29,6 +29,8 @@ static_assert(SchemaMode::Additive ==
 static_assert(SchemaMode::Manual ==
               static_cast<SchemaMode>(io_realm_internal_SharedRealm_SCHEMA_MODE_VALUE_MANUAL), "");
 
+static void finalize_shared_realm(jlong ptr);
```
Comment (kneth) [inline realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp]: Do we need this prototype?

Comment (beeender) [inline realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp]: Yes, for the `-Wmissing-declarations`.

File: realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java (hunk 1 above)
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java]: it looks better to be together with `getNativeFinalizerPtr()` and close to `close()`. :)

File: realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp (hunk 2 above)
Comment (kneth) [inline realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp]: Really? OK

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,9 @@
+## 2.3.1
+
+### Bug fixes
+
+* Fixed NPE problem happened in SharedRealm.finalize() (#3730).
```
Comment (Zhuinden) [inline CHANGELOG.md]: I'm not sure if that `happened` is really needed.

Comment (beeender) [inline CHANGELOG.md]: doh .... too late ... it is all your fault, you comment 10 seconds earlier !! I will fix it next time when modify the changelog.

Comment (Zhuinden) [inline CHANGELOG.md]: I'm sorry 😭
