### PR TITLE
Fix javadoc issues

### LINKED ISSUE #892: Update api-doc with references
http links are not linked correctly many places.

### PR DESCRIPTION
**Pull request by emanuelez**
Fixes #892

### CODE REVIEW

**Comment by emanuelez** [comment]
@cmelchior @kneth @bmunkholm

File: realm/src/main/java/io/realm/Realm.java [hunk 1]
```diff
@@ -1695,7 +1696,7 @@ public static boolean deleteRealmFile(Context context) {
      * Delete the Realm file from the filesystem for a custom named Realm.
      * The realm must be unused and closed before calling this method.
      *
-     * @param context  an Android @{{@link android.content.Context}.
+     * @param context  an Android {@link android.content.Context}.
```
Comment (kneth) [inline realm/src/main/java/io/realm/Realm.java]: an `{` too many.

**Comment by kneth** [comment]
:+1:
