### PR TITLE
Fix BadVersionException

### LINKED ISSUE #2021: BadVersionException
Hey, guys. I keep getting this exception. I am using 0.87.1 version of Realm(and I use Realm as a singleton).  

My situation looks like this: there is navigation button which starts a fragment, which makes an async query for objects in onStart() method. This exception rises when user spams this navigation button or just makes fast transactions between fragments.

```java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1262
E/AndroidRuntime:     at io.realm.RealmQuery$3.call(RealmQuery.java:1491)
E/AndroidRuntime:     at io.realm.RealmQuery$3.call(RealmQuery.java:1467)
E/AndroidRuntime:     at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
E/AndroidRuntime:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime:  Caused by: io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1262
E/AndroidRuntime:     at io.realm.internal.TableQuery.nativeFindAllSortedWithHandover(Native Method)
E/AndroidRuntime:     at io.realm.internal.TableQuery.findAllSortedWithHandover(TableQuery.java:490)
E/AndroidRuntime:     at io.realm.RealmQuery$3.call(RealmQuery.java:1480)
E/AndroidRuntime:     at io.realm.RealmQuery$3.call(RealmQuery.java:1467) 
E/AndroidRuntime:     at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36) 
E/AndroidRuntime:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305) 
E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:856)```

By the way, sometimes my during fast transactions between fragments my app crashes with SIGSEV  or just completely freezes without throwing ANR, dunno if it's connected to the BadVersion, but just in case.

### LINKED ISSUE #2391: Bad Version exception. (Please stop send error to internal handler.)
Bad version exception still happens and you seem don't have solution about this.

It happens in findAllAsync or findAllSortedAsync.

So, I do try-catch to all usage of the methods.

But bad version exception fires again and kill app cause the methods don't allow send exception to us, just kill app! (why???)

We release our app with realm recently and bad version exception is most number of crash ever, very ever.

We have more than 1 million users in our app, and it is now giving users very bad experience.

I think you should fix it or for temporal solution, do not just throw exception in your sdk to kill app.
(If you can't, we have to change DB to another... But I don't want it and I think you too.)

One more, it is very bad exception and we get some upset about you haven't solved this bug even though this issue happened at Dec, 2015.

Please look at this issue seriously.

### LINKED ISSUE #2417: std::exception in io_realm_internal_TableQuery.cpp line 1682 when calling RealmResults.load() with multiple Realm instances
#### Steps to reproduce

- Obtain an instance of `Realm`
- Execute an async transaction on it
- Obtain a second instance of `Realm` with same configuration and on the same thread (it will return the same instance as the first `Realm`)
- Execute an async query
- Call `load()` to synchronously wait for the query to execute 

#### Issue

The `load()` method throws a native exception: `std::exception in io_realm_internal_TableQuery.cpp line 1682`. this exception is swallowed on the Java side, but I managed to debug it and I discovered it's actually a `BadVersionException`.
After some investigation I think the issue is in the invocation of `Realm.getInstance()` after submitting the first transaction. If that happens before (or if I reuse the same `Realm` variable) everything works correctly.
I already discussed with @cmelchior on Slack about the issue.

#### Code Sample
(in Kotlin :stuck_out_tongue: )
```kotlin
val realm = Realm.getInstance(realmConfiguration)
realm.executeTransactionAsync {
    it.deleteAll()
}
val realm2 = Realm.getInstance(realmConfiguration)
realm2.where(RealmDocument::class.java).findAllAsync().load()
```

#### Version of Realm and tooling
Realm version(s): 0.88.0

Android Studio version: 2.0

Which Android version and device: Emulator with 6.0

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #2417
Fixes #2391
Fixes #2021 

This replaces #2426 
Please review this throughly @realm/java

Copy paste from #2426 
> @nhachicha I updated the PR. We didn't properly handle BadVersionException in our findAllAsync methods from what I could tell. In a lot of cases we treated that exception as fatal (even though a retry was imminent). I think I fixed it, but still trying to wrap my head around testing it in a sane way. So far I have done manual testing but stubbing out values.

> Please review, especially around retrying and batch updates.

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/HandlerController.java [hunk 1]
```diff
@@ -367,7 +372,13 @@ private void completedAsyncRealmResults(QueryUpdateTask.Result result) {
                     if (!realmResults.isLoaded()) {
                         RealmLog.d("[COMPLETED_ASYNC_REALM_RESULTS "+ weakRealmResults + "] , realm:"+ HandlerController.this + " same versions, using results (RealmResults is not loaded)");
                         // swap pointer
-                        realmResults.swapTableViewPointer(result.updatedTableViews.get(weakRealmResults));
+                        try {
+                            realmResults.swapTableViewPointer(result.updatedTableViews.get(weakRealmResults));
+                        } catch (BadVersionException e) {
```
Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: This _can't_ happen, since the CallerThread.version == BgThread.version & the caller thread is holding an open SharedGroup using this version.

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: I switched BadVersionException to be Checked instead of runtime to make sure that all code paths where aware it might be a problem. In this case the handover from the caller -> worker did succeed, but I am still not confident that you can do worker -> caller safely as the worker has been closed at this point and the caller might have advanced.

**Comment by cmelchior** [comment]
@tgoyne / @finnschiermer Please help review the JNI parts. Just to ensure that there are not some corner cases that we forgot.

File: realm/realm-library/src/main/java/io/realm/internal/async/QueryUpdateTask.java [hunk 2]
```diff
@@ -100,6 +100,7 @@ public void run() {
             }
 
         } catch (Exception e) {
+            // TODO Should we just ignore BadVersionException?
```
Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/internal/async/QueryUpdateTask.java]: I think we should ignore it, any retry should be handled by the `HandlerController`

File: realm/realm-library/src/main/java/io/realm/HandlerController.java [hunk 3]
```diff
@@ -450,6 +461,16 @@ private void completedAsyncQueriesUpdate(QueryUpdateTask.Result result) {
                     asyncRealmResults.remove(weakRealmResults);
 
                 } else {
+                    // update the instance with the new pointer
+                    try {
+                        realmResults.swapTableViewPointer(query.getValue());
+                    } catch (BadVersionException e) {
```
Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: same as above. we're either on the same version, or we just advanced to the worker thread version, which should crash here https://github.com/realm/realm-java/pull/2450/files#diff-c6f79e9457082a73f91697a0d6ed683dR451 before we can get to this block

File: realm/realm-library/src/main/java/io/realm/HandlerController.java (hunk 1 above)
Comment (tgoyne) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: If the caller advanced then we won't hit this code path at all because that was already checked for. `begin_read()` is the only place where it makes sense to catch a BadVersionException, as everywhere else it the precondition can be checked first.

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp [hunk 4]
```diff
@@ -1146,12 +1150,20 @@ JNIEXPORT jlongArray JNICALL Java_io_realm_internal_TableQuery_nativeBatchUpdate
...
-        // position this shared group at the specified version
-        SG(bgSharedGroupPtr)->begin_read(handoverQuery->version);
+
+        // if the SharedGroup is not in Read Transaction, we position it at the same version as the handover
+        // The Handover object doesn't prevent a SharedGroup version from no longer being accessible. In rare
+        // cases this means that the version in the Handover object is invalid and Realm Core will throw a
+        // BadVersion as result.
+        if (SG(bgSharedGroupPtr)->get_transact_stage() != SharedGroup::transact_Reading) {
+            SG(bgSharedGroupPtr)->begin_read(handoverQuery->version);
+        } else if (SG(bgSharedGroupPtr)->get_version_of_current_transaction() != handoverQuery->version) {
```
Comment (stk1m1) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: @cmelchior I am not trying to review. @finnschiermer says 
> I don't think Core promises this call to be well defined, when used outside a transaction. It should be called from within a transaction, but see below for a bigger problem.

You can see his comment in my unit test for new `distinct()` submitted [here](https://github.com/realm/realm-core/commit/078e61244aa1551b7dcf475c4fa648e1dd62585c#diff-dfb86ea2c75fcee0e86ed82cdc5ae7adR11129)

Comment (nhachicha) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: this call is inside a read transaction

**Comment by cmelchior** [comment]
Updated after chatting with @nhachicha 
BadVersionChecks should now be more accurate.

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp [hunk 5]
```diff
@@ -1037,23 +1037,27 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_TableQuery_nativeFind(
     return -1;
 }
 
-std::unique_ptr<Query> getHandoverQuery (jlong bgSharedGroupPtr, jlong queryPtr, bool advanceToLatestVersion)
+// Returns a pointer to query on the worker SharedGroup or throw a BadVersion if the SharedGroup version required
+// for the handover is no longer available.
+std::unique_ptr<Query> handoverQueryToWorker(jlong bgSharedGroupPtr, jlong queryPtr, bool advanceToLatestVersion)
```
Comment (beeender) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: Do we still need `advanceToLatestVersion` for https://github.com/realm/realm-java/pull/2294/files#diff-feb202ebcef8ca848c17b2f2f81e78e7R2455 ?

File: realm/realm-library/src/main/java/io/realm/internal/TableQuery.java [hunk 6]
```diff
@@ -799,12 +810,12 @@ private void throwImmutable() {
     private native long nativeRemove(long nativeQueryPtr, long start, long end, long limit);
     private native long nativeImportHandoverTableViewIntoSharedGroup(long handoverTableViewPtr, long callerSharedGroupPtr);
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/internal/TableQuery.java]: This throws bad version as well

File: realm/realm-library/src/main/java/io/realm/HandlerController.java [hunk 7]
```diff
@@ -95,31 +96,35 @@ public boolean handleMessage(Message message) {
...
+                case COMPLETED_ASYNC_REALM_RESULTS:
+                    result = (QueryUpdateTask.Result) message.obj;
                     completedAsyncRealmResults(result);
                     break;
-                }
-                case COMPLETED_ASYNC_REALM_OBJECT: {
-                    QueryUpdateTask.Result result = (QueryUpdateTask.Result) message.obj;
+
+                case COMPLETED_ASYNC_REALM_OBJECT:
+                     result = (QueryUpdateTask.Result) message.obj;
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: extra space before `result`

Comment (stk1m1) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: An extra white space in front of `result =`

File: realm/realm-library/src/main/java/io/realm/HandlerController.java [hunk 8]
```diff
@@ -497,9 +511,15 @@ private void completedAsyncRealmObject(QueryUpdateTask.Result result) {
                     realmObject.onCompleted(rowPointer);
                     realmObject.notifyChangeListeners();
 
-                } else if (compare > 0) {
-                    // the caller has advanced we need to
-                    // retry against the current version of the caller if it's still empty
+                } else {
+                    if (compare > 0) {
+                        RealmLog.d("[COMPLETED_ASYNC_REALM_OBJECT "+ realmObject + "] , realm:" + HandlerController.this
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: Make the `realmObject.isValid()` be part of the log message? Easy to figure out the problem if needed

**Comment by stk1m1** [comment]
Hope this gets merged really soon.

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp [hunk 9]
```diff
@@ -1146,12 +1150,20 @@ JNIEXPORT jlongArray JNICALL Java_io_realm_internal_TableQuery_nativeBatchUpdate
...
         SharedGroup::Handover<Query> *handoverQueryPtr = HO(Query, handover_queries_pointer_array[0]);
         std::unique_ptr<SharedGroup::Handover<Query>> handoverQuery(handoverQueryPtr);
-        // position this shared group at the specified version
-        SG(bgSharedGroupPtr)->begin_read(handoverQuery->version);
+
+        // if the SharedGroup is not in Read Transaction, we position it at the same version as the handover
+        // The Handover object doesn't prevent a SharedGroup version from no longer being accessible. In rare
+        // cases this means that the version in the Handover object is invalid and Realm Core will throw a
+        // BadVersion as result.
+        if (SG(bgSharedGroupPtr)->get_transact_stage() != SharedGroup::transact_Reading) {
```
Comment (bmunkholm) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: For readability I would suggest to make a local variable `backgroundSG`=SG(bgSharedGroupPtr) or similar instead of doing the typecast all over.

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 10]
```diff
@@ -1809,6 +1816,139 @@ public void run() {
         }.start();
     }
 
+    // Test case for https://github.com/realm/realm-java/issues/2417
```
Comment (bmunkholm) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: Including the issue is great, but please also include a description of what it tests, so one doesn't have to lookup the issue. (same for the below issue references)

File: realm/realm-library/src/androidTest/java/io/realm/TestHelper.java [hunk 11]
```diff
@@ -760,6 +762,18 @@ public static void quitLooperOrFail() {
     }
 
     /**
+     * Replace the current thread executor with a another one for testing.
```
Comment (dalinaum) [inline realm/realm-library/src/androidTest/java/io/realm/TestHelper.java]: Replace -> Replaces

File: realm/realm-library/src/main/java/io/realm/RealmQuery.java [hunk 12]
```diff
@@ -1492,6 +1493,11 @@ public Long call() throws Exception {
 
                         return handoverTableViewPointer;
 
+                    } catch (BadVersionException e) {
+                        // In some rare race conditions, this can happen. In that case, just ignore the error.
+                        RealmLog.d("findAllAsync handover could not complete due to a BadVersionException. " +
```
Comment (bmunkholm) [inline realm/realm-library/src/main/java/io/realm/RealmQuery.java]: What should people do with this message? Be concerned? Change anything in their code? Report it?

Do anyone know what a "BadVersionException" mean? It sounds really bad... :-)
What does "Retry SHOULD be" mean? Should it be "Retry WILL be" or "Retry IS"?

File: realm/realm-library/src/main/java/io/realm/RealmResults.java [hunk 13]
```diff
@@ -800,10 +801,15 @@ public void set(E object) {
...
+     * @throws IllegalStateException if caller and worker are not at the same version.
      */
     void swapTableViewPointer(long handoverTableViewPointer) {
-        table = query.importHandoverTableView(handoverTableViewPointer, realm.sharedGroupManager.getNativePointer());
-        isCompleted = true;
+        try {
+            table = query.importHandoverTableView(handoverTableViewPointer, realm.sharedGroupManager.getNativePointer());
+            isCompleted = true;
+        } catch (BadVersionException e) {
+            throw new IllegalStateException("Caller and Worker SharedGroup should have been the same version");
```
Comment (bmunkholm) [inline realm/realm-library/src/main/java/io/realm/RealmResults.java]: Users don't know what a `SharedGroup` is - and shouldn't know.

File: realm/realm-library/src/main/java/io/realm/internal/ImplicitTransaction.java [hunk 14]
```diff
@@ -16,6 +16,8 @@
 
 package io.realm.internal;
 
+import io.realm.internal.async.BadVersionException;
```
Comment (bmunkholm) [inline realm/realm-library/src/main/java/io/realm/internal/ImplicitTransaction.java]: "BadVersion" just sounds "bad" - and doesn't say much. (I know it comes from core). Can't we find a better name that says more?

File: realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java [hunk 15]
```diff
@@ -24,7 +23,7 @@
  * state of the Realm which might be more up-to-date than the provided results or vice versa.
  */
 @Keep
-public class BadVersionException extends RealmException {
+public class BadVersionException extends Exception {
 
     public BadVersionException(String detailMessage) {
```
Comment (bmunkholm) [inline realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java]: "BadVersion" just sounds "bad" - and doesn't say much. (I know it comes from core). Can't we find a better name that says more?

File: realm/realm-library/src/main/java/io/realm/HandlerController.java [hunk 16]
```diff
@@ -437,7 +442,16 @@ private void completedAsyncQueriesUpdate(QueryUpdateTask.Result result) {
                 // refresh the Realm to the version provided by the worker thread
                 // (advanceRead to the latest version may cause a version mismatch error) preventing us
                 // from importing correctly the handover table view
-                realm.sharedGroupManager.advanceRead(result.versionID);
+                try {
+                    realm.sharedGroupManager.advanceRead(result.versionID);
+                } catch (BadVersionException e) {
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: I think it is totally safe to continue using the `SharedGroup` even if the `advance_read` failed because of `BadVersion`, right? @finnschiermer

File: realm/realm-library/src/main/java/io/realm/RealmQuery.java (hunk 12 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmQuery.java]: This is only being logged in Debug mode, which means that normal users do not see this message. This message is mostly for internal debugging (or we can ask users to enable it).

File: realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java (hunk 15 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java]: What about `UnreachableVersion`? It is probably also more accurate since it normally happens because the version we try to open is an old one that no longer is available.

File: realm/realm-library/src/main/java/io/realm/HandlerController.java (hunk 16 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: Yes, it should be safe, but we should actually abort here. I forgot to `return` if this is thrown. If this happens, a REALM_CHANGED event should be in the Looper queue anyway which will schedule a retry. Until that happens it will just continue using the old version (which should be fine).

Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: Yeah, `return` is missed! :+1:

**Comment by beeender** [comment]
`public BadVersionException(String detailMessage, Throwable exception)` is not used anymore, delete it?

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp (hunk 5 above)
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: I think so yes. That unit test covers the standard scenario that could cause caller and worker to get out of sync. The BadVersion in this PR is a lot more subtle as it is a race condition between async writes and queries.

File: realm/realm-library/src/main/java/io/realm/HandlerController.java (hunk 8 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: The object should always be valid since this async queries only for on managed objects?  `isValid` would only make sense if the object had been deleted? Which shouldn't impact this logic anyway or am I missing something?

Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: No? `Row.EMPTY_ROW.isAttached()` should return `false`. Otherwise, the following line (523) should check `isLoaded` instead?

File: realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java (hunk 15 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java]: Thinking again, I would rather leave a refactoring of this outside the scope of a patch PR. Also BadVersion might be appropriate after all as it could also happen if you try to handover to the wrong version = the version is reachable, but you just forgot to advance_read to it before doing the handover.

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp (hunk 4 above)
Comment (jcj52436999) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (118/100 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:59282 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflk9-001g97-6F
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:58:25 -0400
Date: Mon, 14 Mar 2016 10:31:57 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457976717;
	bh=sEScRBD8HAEm/7agcSwGLXQZTtNcW0/zVoSdGQWrcV0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=WpdL8KoPBLsseb5gqjKCm4Lb00tzRm8mQtQFbVqu9+1M5hHK8+9gn97e5oc01cPUY
	 9Jm7HAIaU/rKCnrEr23q0oSTR3kdmQy+OQNwLp20vD/N3ExatzMsK4PPP6F+JGjA5t
	 SdmLhr0fQwYE3q+6T3RIQmAbgBVKm0xvzdJhsVlY=

File: realm/realm-library/src/main/java/io/realm/HandlerController.java (hunk 16 above)
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: `BadVersionException` should never be thrown since `callerVersionID` is always smaller than `result.versionID`.

File: realm/realm-library/src/main/java/io/realm/HandlerController.java [hunk 17]
```diff
@@ -437,7 +442,16 @@ private void completedAsyncQueriesUpdate(QueryUpdateTask.Result result) {
...
+                    // It is possible for the SharedGroup on the caller thread to advance before handling the callback.
```
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: The comment here is not correct. We should update it.

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: Yup, I am updating it now

Comment (jcj52436999) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (103/100 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:36636 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmK0-001wQS-Lu
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:35:28 -0400
Date: Tue, 15 Mar 2016 03:33:30 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458038010;
	bh=c5eYn7xBHMHUjIqTxVhVoenhjhIS77XofXbx8ZRTNfM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=EiZfI1yra5wleqGdqiHLCS7tTGnbv/V27R0RmUzGl/byOOxl89xV2WhOILR3UT5ly
	 CzrRB2nhYkSgtBKSyI6rqkz8aTJKZtMu4AYxHKXvaUgUQpixTtu6PlfD9VomgefpVs
	 McS7ohQ5p55yGyMW/G78EUOzf38jZO9gNqhy+CSQ=

Comment (jcj52436999) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (104/100 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:40548 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmK5-001wSo-Mu
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:35:33 -0400
Date: Tue, 15 Mar 2016 03:33:54 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458038034;
	bh=KHIAo9MOCVsGoNd8RC98muI5P2wp/MRFEK4QQuRE1iw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=awKi2X/GOdTbvYerwa7Rx3BGnTrjFfOXpb2fcJ4GnE7yh5PqQCZtXJ3ake8lBttLt
	 XmkujCX1/ixN+iBJSWrIBw3mrXNttjv3XRCRH0i5Q+Qk99C15O3LN1ZVK+CRUN3+Ap
	 nGsqcrOo1jCtyg9wMufcXirr3n1i2pmTqJRtMlfk=

File: realm/realm-library/src/main/java/io/realm/HandlerController.java (hunk 16 above)
Comment (jcj52436999) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (114/100 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:34864 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMk-001xaj-9f
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:38:18 -0400
Date: Tue, 15 Mar 2016 01:12:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458029536;
	bh=6fmgPSFZh/596954I49I2LVy7j7A/eBP/BKuTLDyPC0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=OFnJmxxMcZgVUFC5d41Mp2uydnQScSfjucYCUQn+zKIRQLOSJVCGXv7sbwNkPufxO
	 3yjzixwKd9j3iVk3AVamePac9TUCs26YUghrLbnN13//GugUB6t2V/Ji9JaMVYsOfW
	 I5JNiW+lJnuazsRNvpqUXQ/2qH7aEY44nYIlMcEw=

**Comment by cmelchior** [comment]
retest this please

**Comment by cmelchior** [comment]
Ready for round 2 @realm/java

File: realm/realm-library/src/main/java/io/realm/HandlerController.java [hunk 18]
```diff
@@ -497,9 +508,15 @@ private void completedAsyncRealmObject(QueryUpdateTask.Result result) {
...
                     realmObject.notifyChangeListeners();
 
-                } else if (compare > 0) {
-                    // the caller has advanced we need to
-                    // retry against the current version of the caller if it's still empty
+                } else {
+                    if (compare > 0) {
+                        RealmLog.d("[COMPLETED_ASYNC_REALM_OBJECT "+ realmObject + "] , realm:" + HandlerController.this
+                                + " caller is more advanced. Schedule a retry on current version");
+                    } else {
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: Although this is unlikely to happen, i still think we should throw like the left side line 524.

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp (hunk 5 above)
Comment (beeender) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: :+1:

**Comment by beeender** [comment]
:+1:

File: realm/realm-library/src/main/java/io/realm/RealmQuery.java (hunk 12 above)
Comment (bmunkholm) [inline realm/realm-library/src/main/java/io/realm/RealmQuery.java]: Ah, sorry, missed that.
Still don't understand what you mean with "Should" though?

File: realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java (hunk 15 above)
Comment (bmunkholm) [inline realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java]: Sure - create another issues for that. As long as it's not exposed to the user API.

File: realm/realm-library/src/main/java/io/realm/RealmQuery.java (hunk 12 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmQuery.java]: Fixed

File: realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java (hunk 15 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java]: #2468 created
