### PR TITLE
insert(): Correctly detect multiple objects with the same primary key 

### LINKED ISSUE #3212: @PrimaryKey is not handled correctly when using insert()
#### Steps & Code to Reproduce

```java

public class PrimaryKeyActivity extends Activity {
    private static final String TAG = PrimaryKeyActivity.class.getSimpleName();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        final Car car = new Car();
        car.wheels = new RealmList<>(new Wheel(), new Wheel());

        final Realm realm = Realm.getDefaultInstance();
        Log.d(TAG, "Number of wheels with id 1 before inserting: " + realm.where(Wheel.class).equalTo("id", 1).count());
        realm.beginTransaction();
        realm.insert(car);
        realm.commitTransaction();
        Log.d(TAG, "Number of wheels with id 1 after inserting: " + realm.where(Wheel.class).equalTo("id", 1).count());
        realm.close();
    }
}

public class Car extends RealmObject {
    @PrimaryKey
    private long id = 42;
    public RealmList<Wheel> wheels;
}

public class Wheel extends RealmObject {
    @PrimaryKey
    private long id = 1;
}

```

#### Expected log output:

>D/PrimaryKeyActivity: Number of wheels with id 1 before inserting: 0
>D/PrimaryKeyActivity: Number of wheels with id 1 after inserting: 1

#### Actiual log output:

>D/PrimaryKeyActivity: Number of wheels with id 1 before inserting: 0
>D/PrimaryKeyActivity: Number of wheels with id 1 after inserting: **2**

As you can see, we have two objects with the same primary key.
Note that `insertOrUpdate()` and `copyToRealm()` work correctly.

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: Android 4.2.2 on Samsung GT-I9105

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #3212 

This PR fixes a bug which happened when using `insert()` with two java instances with the same primary key. This now correctly throws a `RealmPrimaryKeyConstraintBrokenException`.

@realm/java

### CODE REVIEW

File: realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java [hunk 1]
```diff
@@ -317,7 +319,33 @@ public void insertToRealm_NullPrimaryKey() {
...
+    public void insert_duplicatedPrimaryKeyFails() {
+
+        // Single object with 2 references to two objects with the same ID
+        AllJavaTypes obj = new AllJavaTypes(2);
+        obj.setFieldList(new RealmList<AllJavaTypes>(new AllJavaTypes(1), new AllJavaTypes(1)));
+        realm.beginTransaction();
+        try {
+            realm.insert(obj);
+            fail();
+        } catch (RealmPrimaryKeyConstraintException ignored) {
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java]: Why would this throw? It is clearly valid that `RealmList` can have duplicated elements. I would say if use have two objects with same pk but different other fields, then it is an undefined behaviour and user should not do that.

Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java]: Because you cannot `insert` two objects with the same PK. In that case you should have called `insertOrUpdate`. We cannot really just say it is undefined behaviour as it would be a serious data corruption if you suddenly had two objects with the same primary key.

Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java]: Note. It would work, if the list referenced the same Java object, e.g. `new RealmList<>(obj, obj)`. Then we correctly detect that it is the same object, but if you have to distinct java objects we can no longer assume anything

Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java]: Got it!

File: realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java [hunk 2]
```diff
@@ -668,12 +668,23 @@ public static long insert(Realm realm, some.test.AllTypes object, Map<RealmModel
...
+        } else {
+            rowIndex = Table.nativeFindFirstString(tableNativePtr, pkColumnIndex, primaryKeyValue);
+        }
+        if (rowIndex == TableOrView.NO_MATCH) {
+            rowIndex = Table.nativeAddEmptyRow(tableNativePtr, 1);
+            if (primaryKeyValue != null) {
+                Table.nativeSetString(tableNativePtr, pkColumnIndex, rowIndex, (String)primaryKeyValue);
+            }
+        } else {
+            table.throwDuplicatePrimaryKeyException(primaryKeyValue);
```
Comment (beeender) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: make `throwDuplicatePrimaryKeyException` static and use `Table` here

File: realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java [hunk 3]
```diff
@@ -668,12 +668,23 @@ public static long insert(Realm realm, some.test.AllTypes object, Map<RealmModel
...
-        String realmGet$columnString = ((AllTypesRealmProxyInterface)object).realmGet$columnString();
-        if (realmGet$columnString != null) {
-            Table.nativeSetString(tableNativePtr, columnInfo.columnStringIndex, rowIndex, realmGet$columnString);
+        long pkColumnIndex = table.getPrimaryKey();
+        String primaryKeyValue = ((AllTypesRealmProxyInterface) object).realmGet$columnString();
+        long rowIndex = TableOrView.NO_MATCH;
+        if (primaryKeyValue == null) {
+            rowIndex = table.findFirstNull(pkColumnIndex);
+        } else {
+            rowIndex = Table.nativeFindFirstString(tableNativePtr, pkColumnIndex, primaryKeyValue);
```
Comment (beeender) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: It is strange calling native method here but java method above. I think it is better call the java wrapper method only. Easy for maintaining.

Comment (beeender) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: Also, we can make less code by support `null` by `nativeFindFirstString`. But it is beyond the scope of this PR.

File: realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java [hunk 4]
```diff
@@ -668,12 +668,23 @@ public static long insert(Realm realm, some.test.AllTypes object, Map<RealmModel
...
+        }
+        if (rowIndex == TableOrView.NO_MATCH) {
+            rowIndex = Table.nativeAddEmptyRow(tableNativePtr, 1);
```
Comment (beeender) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: same, but calling the native method is for the purpose of insterting speed, i am OK with this.

File: realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java (hunk 3 above)
Comment (cmelchior) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: Not sure I follow? `((AllTypesRealmProxyInterface) object).realmGet$columnString();` is required because you need the data from the actual Java object since it is not a proxy. 

All other methods should ideally use the Table interface to avoid unnecessary allocations and checks (which was the entire point of `insert()`

File: realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java [hunk 5]
```diff
@@ -716,16 +727,27 @@ public static void insert(Realm realm, Iterator<? extends RealmModel> objects, M
...
-                cache.put(object, rowIndex);
-                String realmGet$columnString = ((AllTypesRealmProxyInterface)object).realmGet$columnString();
-                if (realmGet$columnString != null) {
-                    Table.nativeSetString(tableNativePtr, columnInfo.columnStringIndex, rowIndex, realmGet$columnString);
+                String primaryKeyValue = ((AllTypesRealmProxyInterface) object).realmGet$columnString();
+                long rowIndex = TableOrView.NO_MATCH;
+                if (primaryKeyValue == null) {
+                    rowIndex = table.findFirstNull(pkColumnIndex);
+                } else {
+                    rowIndex = Table.nativeFindFirstString(tableNativePtr, pkColumnIndex, primaryKeyValue);
```
Comment (beeender) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: same here

File: realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java [hunk 6]
```diff
@@ -716,16 +727,27 @@ public static void insert(Realm realm, Iterator<? extends RealmModel> objects, M
...
                 }
+                if (rowIndex == TableOrView.NO_MATCH) {
+                    rowIndex = Table.nativeAddEmptyRow(tableNativePtr, 1);
+                    if (primaryKeyValue != null) {
+                        Table.nativeSetString(tableNativePtr, pkColumnIndex, rowIndex, (String)primaryKeyValue);
+                    }
+                } else {
+                    table.throwDuplicatePrimaryKeyException(primaryKeyValue);
```
Comment (beeender) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: Table

File: realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java [hunk 7]
```diff
@@ -854,16 +870,10 @@ public static void insertOrUpdate(Realm realm, Iterator<? extends RealmModel> ob
                 if (rowIndex == TableOrView.NO_MATCH) {
                     rowIndex = Table.nativeAddEmptyRow(tableNativePtr, 1);
                     if (primaryKeyValue != null) {
-                        Table.nativeSetString(tableNativePtr, pkColumnIndex, rowIndex, ((AllTypesRealmProxyInterface) object).realmGet$columnString());
+                        Table.nativeSetString(tableNativePtr, pkColumnIndex, rowIndex, (String)primaryKeyValue);
```
Comment (beeender) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: just to confirm, the default value nullable string field is `null` not `""`?

Comment (cmelchior) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: Yup. The default is based on the `@Required` annotation.

I am actually not entirely sure we handle that case properly here: `@Required @PrimaryKey String  id`, should use `'"` as the default value.

File: realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java (hunk 3 above)
Comment (beeender) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: I mean it is calling java method `findFirstNull` at line 675, but native method `nativeFindFirstString` at line 677. which looks a bit strange.

Comment (cmelchior) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: Good point. I'll fix it.

**Comment by kneth** [comment]
@beeender has already done the hard work: LGTM

**Comment by cmelchior** [comment]
Updated @realm/java

**Comment by beeender** [comment]
:+1:

**Comment by kneth** [comment]
:+1:
