### PR TITLE
RealmMigrationNeededException can now return the path to the Realm

### LINKED ISSUE #1060: RealmMigrationNeededException should have getAbsolutePath()
I'd like to write schema check code as follows.

        try {
            Realm.getInstance(context, "foo.realm").close();
        } catch (RealmMigrationNeededException e) {
            Realm.migrateRealmAtPath(e.getAbsolutePath(), new MyRealmMigration());
        }

due to lacking of RealmMigrationNeededException#getAbsolutePath(), we must write 

    Realm.migrateRealmAtPath(new File(context.getFilesDir(), "foo.realm").getAbsolutePath(),
                             new MyRealmMigration());

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #1060 

@emanuelez @kneth @zaki50

### CODE REVIEW

**Comment by zaki50** [comment]
:+1:

**Comment by emanuelez** [comment]
A unit test would be nice, otherwise :+1:

File: realm/src/main/java/io/realm/internal/SharedGroup.java [hunk 1]
```diff
@@ -233,6 +231,18 @@ public boolean compact() {
         return nativeCompact(nativePtr);
     }
 
+
+    /**
+     * Returns the absolute path to the file backing this SharedGroup.
+     *
+     * @return Absolute path to the Realm file.
+     */
+    public String getPath() {
```
Comment (kneth) [inline realm/src/main/java/io/realm/internal/SharedGroup.java]: Since the Java documentation (https://docs.oracle.com/javase/7/docs/api/java/io/File.html) discuss `getPath()` and `getAbsolutePath()` as two different methods, I think this method should be called `getAbsolutePath()`.

**Comment by kneth** [comment]
Besides my comment: :+1:

**Comment by cmelchior** [comment]
Hmm, I am not sure I agree. Right now the method is called the same on Realm as on this exception. You are right that Java has 3 different ways for this (getPath/getAbsolutePath/getCanonicalPath), but if we don't have that distinction getPath is the shortest and most readable?
