### PR TITLE
Work around jmethod bug with Android

### LINKED ISSUE #4964: android:debuggable="true" and strange crash with  JNI DETECTED ERROR IN APPLICATION
#4963 reverted a change that `android:debuggable="true"` in `AndroidManifest.xml` .

When this is set, `RealmTests` will fail on `compactOnLaunch_shouldNotCompact` with a native crash:

```
07-13 04:51:34.308 F/DEBUG   (  485): Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: can't call boolean io.realm.DefaultCompactOnLaunchCallback.shouldCompact(long, long) on instance of io.realm.RealmTests$6'
```

This is very strange. I did some debugging and I can confirm a `CompactOnLaunchCallback` was passed to the relevant JNI method. And it is NOT a `RealmTests` instance.

So, it looks when that setting is enabled, Android has a bug somewhere that the `jobject` entries are messed up, the `CallBooleanMethod` was not trying to call the method on the given `jobject`, instead, it was calling the method on some object which was created before the given `jobject`.

Maybe a memory issue in the ART/DAVIK? 

Full callstack:

```
07-13 09:19:26.174 F/libc    (24509): Fatal signal 6 (SIGABRT), code -6 in tid 24536 (roidJUnitRunner)
07-13 09:19:26.285 F/DEBUG   (  485): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-13 09:19:26.285 F/DEBUG   (  485): Build fingerprint: 'google/bullhead/bullhead:6.0/MDA89E/2296692:user/release-keys'
07-13 09:19:26.285 F/DEBUG   (  485): Revision: 'rev_1.0'
07-13 09:19:26.285 F/DEBUG   (  485): ABI: 'arm64'
07-13 09:19:26.285 F/DEBUG   (  485): pid: 24509, tid: 24536, name: roidJUnitRunner  >>> io.realm.test <<<
07-13 09:19:26.286 F/DEBUG   (  485): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-13 09:19:26.275 W/debuggerd64(  485): type=1400 audit(0.0:42592): avc: denied { search } for name="io.realm.test" dev="dm-2" ino=392526 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
07-13 09:19:26.306 F/DEBUG   (  485): Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: can't call boolean io.realm.DefaultCompactOnLaunchCallback.shouldCompact(long, long) on instance of io.realm.RealmTests$6'
07-13 09:19:26.307 F/DEBUG   (  485):     x0   0000000000000000  x1   0000000000005fd8  x2   0000000000000006  x3   0000000000000000
07-13 09:19:26.307 F/DEBUG   (  485):     x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
07-13 09:19:26.307 F/DEBUG   (  485):     x8   0000000000000083  x9   00000000000139c0  x10  00000000862e34f8  x11  00000000862e3638
07-13 09:19:26.308 F/DEBUG   (  485):     x12  0000000000000000  x13  0000007f79d30000  x14  0000000000000000  x15  0000000000000000
07-13 09:19:26.308 F/DEBUG   (  485):     x16  0000007f79d22568  x17  0000007f79cb4f9c  x18  0000007f79d33f50  x19  0000007f70937500
07-13 09:19:26.308 F/DEBUG   (  485):     x20  0000007f70937440  x21  0000000000000000  x22  0000000000000006  x23  0000007f7580b800
07-13 09:19:26.308 F/DEBUG   (  485):     x24  0000007f586539c0  x25  0000000000000000  x26  0000007f76969000  x27  0000000000000000
07-13 09:19:26.308 F/DEBUG   (  485):     x28  0000007f7580b800  x29  0000007f70935030  x30  0000007f79cb2858
07-13 09:19:26.308 F/DEBUG   (  485):     sp   0000007f70935030  pc   0000007f79cb4fa4  pstate 0000000020000000
07-13 09:19:26.331 F/DEBUG   (  485): 
07-13 09:19:26.331 F/DEBUG   (  485): backtrace:
07-13 09:19:26.331 F/DEBUG   (  485):     #00 pc 000000000006afa4  /system/lib64/libc.so (tgkill+8)
07-13 09:19:26.331 F/DEBUG   (  485):     #01 pc 0000000000068854  /system/lib64/libc.so (pthread_kill+68)
07-13 09:19:26.332 F/DEBUG   (  485):     #02 pc 0000000000023838  /system/lib64/libc.so (raise+28)
07-13 09:19:26.332 F/DEBUG   (  485):     #03 pc 000000000001dfd8  /system/lib64/libc.so (abort+60)
07-13 09:19:26.332 F/DEBUG   (  485):     #04 pc 00000000004357d0  /system/lib64/libart.so (art::Runtime::Abort()+324)
07-13 09:19:26.332 F/DEBUG   (  485):     #05 pc 0000000000138164  /system/lib64/libart.so (art::LogMessage::~LogMessage()+3136)
07-13 09:19:26.332 F/DEBUG   (  485):     #06 pc 0000000000310ab8  /system/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2080)
07-13 09:19:26.332 F/DEBUG   (  485):     #07 pc 0000000000310f38  /system/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+116)
07-13 09:19:26.332 F/DEBUG   (  485):     #08 pc 0000000000143f1c  /system/lib64/libart.so (art::ScopedCheck::AbortF(char const*, ...)+144)
07-13 09:19:26.333 F/DEBUG   (  485):     #09 pc 0000000000144314  /system/lib64/libart.so (art::ScopedCheck::CheckMethodAndSig(art::ScopedObjectAccess&, _jobject*, _jclass*, _jmethodID*, art::Primitive::Type, art::InvokeType)+724)
07-13 09:19:26.333 F/DEBUG   (  485):     #10 pc 000000000015d9f8  /system/lib64/libart.so (art::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primitive::Type, art::InvokeType)+724)
07-13 09:19:26.333 F/DEBUG   (  485):     #11 pc 0000000000160490  /system/lib64/libart.so (art::CheckJNI::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+68)
07-13 09:19:26.333 F/DEBUG   (  485):     #12 pc 00000000000d370c  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (_JNIEnv::CallBooleanMethod(_jobject*, _jmethodID*, ...)+124)
07-13 09:19:26.333 F/DEBUG   (  485):     #13 pc 00000000000d3750  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (std::_Function_handler<bool (unsigned long, unsigned long), Java_io_realm_internal_SharedRealm_nativeCreateConfig::'lambda'(unsigned long, unsigned long)>::_M_invoke(std::_Any_data const&, unsigned long, unsigned long)+56)
07-13 09:19:26.333 F/DEBUG   (  485):     #14 pc 000000000014dc68  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (std::function<bool (unsigned long, unsigned long)>::operator()(unsigned long, unsigned long) const+24)
07-13 09:19:26.333 F/DEBUG   (  485):     #15 pc 00000000001509d8  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (realm::Realm::open_with_config(realm::Realm::Config const&, std::unique_ptr<realm::Replication, std::default_delete<realm::Replication> >&, std::unique_ptr<realm::SharedGroup, std::default_delete<realm::SharedGroup> >&, std::unique_ptr<realm::Group, std::default_delete<realm::Group> >&, realm::Realm*)+3628)
07-13 09:19:26.334 F/DEBUG   (  485):     #16 pc 0000000000150dc8  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (realm::Realm::Realm(realm::Realm::Config, std::shared_ptr<realm::_impl::RealmCoordinator>)+580)
07-13 09:19:26.334 F/DEBUG   (  485):     #17 pc 000000000016b044  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (realm::_impl::RealmCoordinator::get_realm(realm::Realm::Config)+1776)
07-13 09:19:26.334 F/DEBUG   (  485):     #18 pc 000000000014e0d0  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (realm::Realm::get_shared_realm(realm::Realm::Config)+372)
07-13 09:19:26.334 F/DEBUG   (  485):     #19 pc 00000000000d7b54  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (Java_io_realm_internal_SharedRealm_nativeGetSharedRealm+536)
07-13 09:19:26.334 F/DEBUG   (  485):     #20 pc 0000000001326e1c  /data/app/io.realm.test-1/oat/arm64/base.odex (offset 0xac2000) (long io.realm.internal.SharedRealm.nativeGetSharedRealm(long, io.realm.internal.RealmNotifier)+160)
07-13 09:19:26.334 F/DEBUG   (  485):     #21 pc 0000000001324458  /data/app/io.realm.test-1/oat/arm64/base.odex (offset 0xac2000) (void io.realm.internal.SharedRealm.<init>(long, io.realm.RealmConfiguration, io.realm.internal.SharedRealm$SchemaVersionListener)+604)
07-13 09:19:26.334 F/DEBUG   (  485):     #22 pc 0000000001325418  /data/app/io.realm.test-1/oat/arm64/base.odex (offset 0xac2000) (io.realm.internal.SharedRealm io.realm.internal.SharedRealm.getInstance(io.realm.RealmConfiguration, io.realm.internal.SharedRealm$SchemaVersionListener, boolean)+1884)
07-13 09:19:26.335 F/DEBUG   (  485):     #23 pc 0000000001324c1c  /data/app/io.realm.test-1/oat/arm64/base.odex (offset 0xac2000) (io.realm.internal.SharedRealm io.realm.internal.SharedRealm.getInstance(io.realm.RealmConfiguration)+112)
07-13 09:19:26.335 F/DEBUG   (  485):     #24 pc 0000000000c0bba0  /data/app/io.realm.test-1/oat/arm64/base.odex (offset 0xac2000) (io.realm.BaseRealm io.realm.RealmCache.doCreateRealmOrGetFromCache(io.realm.RealmConfiguration, java.lang.Class)+532)
07-13 09:19:26.335 F/DEBUG   (  485):     #25 pc 0000000000c0b790  /data/app/io.realm.test-1/oat/arm64/base.odex (offset 0xac2000) (io.realm.BaseRealm io.realm.RealmCache.createRealmOrGetFromCache(io.realm.RealmConfiguration, java.lang.Class)+196)
07-13 09:19:26.335 F/DEBUG   (  485):     #26 pc 0000000001236e00  /data/app/io.realm.test-1/oat/arm64/base.odex (offset 0xac2000) (io.realm.Realm io.realm.Realm.getInstance(io.realm.RealmConfiguration)+340)
07-13 09:19:26.335 F/DEBUG   (  485):     #27 pc 0000000000cf22e0  /data/app/io.realm.test-1/oat/arm64/base.odex (offset 0xac2000) (io.realm.internal.util.Pair io.realm.RealmTests.populateTestRealmAndCompactOnLaunch(io.realm.CompactOnLaunchCallback, int)+836)
07-13 09:19:26.335 F/DEBUG   (  485):     #28 pc 0000000000cf1f54  /data/app/io.realm.test-1/oat/arm64/base.odex (offset 0xac2000) (io.realm.internal.util.Pair io.realm.RealmTests.populateTestRealmAndCompactOnLaunch(io.realm.CompactOnLaunchCallback)+88)
07-13 09:19:26.336 F/DEBUG   (  485):     #29 pc 0000000000cf7a38  /data/app/io.realm.test-1/oat/arm64/base.odex (offset 0xac2000) (void io.realm.RealmTests.compactOnLaunch_shouldNotCompact()+140)
07-13 09:19:26.336 F/DEBUG   (  485):     #30 pc 000000000011e164  /system/lib64/libart.so (art_quick_invoke_stub+580)
07-13 09:19:26.336 F/DEBUG   (  485):     #31 pc 000000000012e01c  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+176)
07-13 09:19:26.336 F/DEBUG   (  485):     #32 pc 0000000000430ac8  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+888)
07-13 09:19:26.336 F/DEBUG   (  485):     #33 pc 00000000003c93dc  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobject*)+40)
07-13 09:19:26.336 F/DEBUG   (  485):     #34 pc 000000007273f3a4  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x1ed4000)
07-13 09:19:27.055 W/ActivityManager(  880): Error in app io.realm.test running instrumentation ComponentInfo{io.realm.test/android.support.test.runner.AndroidJUnitRunner}:
07-13 09:19:27.055 W/ActivityManager(  880):   Native crash
07-13 09:19:27.055 W/ActivityManager(  880):   Native crash: Aborted

```

### PR DESCRIPTION
**Pull request by beeender**
- cherry-pick #4939 to enabled debug in menifest which caused a crash described in #4964.
- Removed API to create JavaMethod from jobject/class name string.  There seems to be a bug in Android JVM when getting the method by: jclass cls = env->GetObjectClass(obj); jmethodID method = env->GetMethodID(cls, "xxx", "xxx") The methodID retrieved by the above way triggers a strange bug in JVM, it reports the method cannot be found on a non-relevant object. Like:
  > can't call boolean io.realm.DefaultCompactOnLaunchCallback.shouldCompact(long, long) on instance of io.realm.RealmTests$6'

  Where RealmTest$6 has nothing to do with that JNI call.  It is not because of the local ref of cls has been deleted -- Even if it is deleted, the methodID should still be valid according to the doc:

  > The class references, field IDs, and method IDs are guaranteed valid until the class is unloaded. Classes are only unloaded if all classes associated with a ClassLoader can be garbage collected, which is rare but will not be impossible in Android.

  The class should never be unload in this case!
- For safety reasons, the JavaMethod should only be created from a JavaClass right now to avoid future surprise.

Close #4964

### CODE REVIEW

**Comment by zaki50** [comment]
How about keeping global ref to a class where the method belongs in addition to `jmethodID` in `JavaMethod`?
It doesn't work?

**Comment by beeender** [comment]
@zaki50 I have thought about that. but it doesn't solve the problem of 
```
JavaMethod(JNIEnv* env, jobject obj, const char* method_name, const char* signature);
```
Simply because the `jmethod` instance getting by `cls = env->GetObjectClass(jobject);` then `methodID = env->getMethod(cls, "xx", "xxx")` will be invalided because of some bugs, even the class ref is kept in this case.

It would be fine with 
```
JavaMethod(JNIEnv* env, const char* class_name, const char* method_name, const char* signature, bool static_method = false);
```

But since for most cases, the `jmethodID` will be a static var, holding multiple instance of the same class for different method will waste a bit more memory. We could cache the class instance in a global map with the class name as the key to solve that maybe? I will investigate it later in another PR if needed.

**Comment by zaki50** [comment]
How about the following?

```
jclass localClass = env->GetObjectClass(jobject);
m_global_class = (jclass) env->NewGlobalRef(localClass);
env->DeleteLocalRef(localClass)
m_method_id = env->GetMethodID(m_global_class, method_name, signature);
```

It doesn't work?

**Comment by beeender** [comment]
@zaki50 no, it doesn't. Although it should work. See the PR main post about the issue.

**Comment by zaki50** [comment]
@beeender OK, changes in this PR are fine for me. :+1:

File: realm/realm-library/src/main/cpp/jni_util/java_method.hpp [hunk 1]
```diff
@@ -30,11 +31,28 @@ class JavaMethod {
...
 
+    // From https://developer.android.com/training/articles/perf-jni.html
+    // The class references, field IDs, and method IDs are guaranteed valid until the class is unloaded. Classes are
+    // only unloaded if all classes associated with a ClassLoader can be garbage collected, which is rare but will not
+    // be impossible in Android. Note however that the jclass is a class reference and must be protected with a call
+    // to NewGlobalRef (see the next section).
+    //
+    // BUT THERE ARE BUGS. See below:
+    //
+    // NOTE: For anyone wants to implement this method, please DON'T. There might be a bug in JVM implementation that
```
Comment (bmeike) [inline realm/realm-library/src/main/cpp/jni_util/java_method.hpp]: I suggest you change this to:
// WARNING!!  There might be a bug in the JVM ...
That would be better English.

File: realm/realm-library/src/main/cpp/jni_util/java_method.hpp [hunk 2]
```diff
@@ -30,11 +31,28 @@ class JavaMethod {
...
-    JavaMethod(JNIEnv* env, const char* class_name, const char* method_name, const char* signature,
+    JavaMethod(JNIEnv* env, JavaClass const& cls, const char* method_name, const char* signature,
                bool static_method = false);
 
+    // From https://developer.android.com/training/articles/perf-jni.html
+    // The class references, field IDs, and method IDs are guaranteed valid until the class is unloaded. Classes are
+    // only unloaded if all classes associated with a ClassLoader can be garbage collected, which is rare but will not
+    // be impossible in Android. Note however that the jclass is a class reference and must be protected with a call
+    // to NewGlobalRef (see the next section).
+    //
```
Comment (bmeike) [inline realm/realm-library/src/main/cpp/jni_util/java_method.hpp]: It is funny.  This is the first thing I thought of, when I saw all those static references to class objects.  Huh.

File: realm/realm-library/src/main/cpp/jni_util/java_method.hpp [hunk 3]
```diff
@@ -30,11 +31,28 @@ class JavaMethod {
...
+    // BUT THERE ARE BUGS. See below:
+    //
+    // NOTE: For anyone wants to implement this method, please DON'T. There might be a bug in JVM implementation that
+    // the jmethodID retrieved from jobject's jclass would be invalid under some certain conditions.
+    // See https://github.com/realm/realm-java/issues/4964 for how to reproduce it.
+    // JavaMethod(JNIEnv* env, jobject obj, const char* method_name, const char* signature);
+
+    // For this constructor, no evidence shows that the jmethodID will be invalided if there is no ref to the jclass.
```
Comment (bmeike) [inline realm/realm-library/src/main/cpp/jni_util/java_method.hpp]: I think this might be better:
"There is no evidence that jmethodId will be invalid when there is no ref to the jclass.  Just in case, though...
... to make sure we don't encounter another JVM bug."
Just a suggestion.

Comment (Zhuinden) [inline realm/realm-library/src/main/cpp/jni_util/java_method.hpp]: `invalided` should probably be `invalidated`
