### PR TITLE
Made Realm.compactRealmFile() more failure resilient.

### LINKED ISSUE #953: compactRealmFile() doesn't cleanup properly
If ```Realm.compactRealmFile()``` fails for some reason, the temporary files created might not get deleted. This can leave rather large copies of unused Realm files on the disc.

### PR DESCRIPTION
**Pull request by cmelchior**
- [x] Awaits a new core release with fix for compact() on empty Realms.
Fixes #953 

 ```Realm.compactRealmFile()``` now uses the methods provided by core which are more failure resilient.

@emanuelez @kneth @bmunkholm

### CODE REVIEW

**Comment by kneth** [comment]
We should definitely start using core's `compact()` method.

**Comment by cmelchior** [comment]
I have added cores compact method and we now use that instead
@emanuelez @kneth

File: realm/src/main/java/io/realm/Realm.java [hunk 1]
```diff
@@ -1717,32 +1716,28 @@ public static synchronized boolean deleteRealmFile(Context context, String fileN
...
+    public static synchronized boolean compactRealmFile(Context context, String fileName, byte[] key) {
         File realmFile = new File(context.getFilesDir(), fileName);
-        File tmpFile = new File(
-                context.getFilesDir(),
-                String.valueOf(System.currentTimeMillis()) + UUID.randomUUID() + ".realm");
-
-        Realm realm = null;
+        String path = realmFile.getAbsolutePath();
+        if (openRealms.get(path.hashCode()).get() > 0) {
+            throw new IllegalStateException("Cannot compact a open Realm");
```
Comment (emanuelez) [inline realm/src/main/java/io/realm/Realm.java]: a -> an

File: realm-jni/src/io_realm_internal_SharedGroup.cpp [hunk 2]
```diff
@@ -268,3 +268,14 @@ JNIEXPORT jstring JNICALL Java_io_realm_internal_SharedGroup_nativeGetDefaultRep
...
 }
+
+JNIEXPORT jboolean JNICALL Java_io_realm_internal_SharedGroup_nativeCompact(
+    JNIEnv* env, jobject, jlong native_ptr)
+{
+    TR_ENTER_PTR(native_ptr)
+    try {
+        return SG(native_ptr)->compact(); // throws
+    }
+    CATCH_STD()
```
Comment (kneth) [inline realm-jni/src/io_realm_internal_SharedGroup.cpp]: You should add `CATCH_FILE()` too.

File: realm/src/main/java/io/realm/Realm.java [hunk 3]
```diff
@@ -1756,9 +1751,30 @@ public static synchronized boolean compactRealmFile(Context context, String file
...
+     *
+     * @throws IllegalStateException if trying to compact a Realm that is already open
      */
     public static boolean compactRealmFile(Context context) {
-        return compactRealmFile(context, DEFAULT_REALM_NAME);
+        return compactRealmFile(context, DEFAULT_REALM_NAME, null);
+    }
+
+    /**
+     * Compact a realm file. A realm file usually contain free/unused space.
```
Comment (kneth) [inline realm/src/main/java/io/realm/Realm.java]: Realm is written with capital R in our documentation.

**Comment by kneth** [comment]
Besides my comments: :+1:

File: realm/src/main/java/io/realm/Realm.java (hunk 3 above)
Comment (bmunkholm) [inline realm/src/main/java/io/realm/Realm.java]: Actually not always. @timanglade made some guidelines once - maybe he can share those again. In this case I wouldn't capitalize (but that's just based on intuition, not guideliens :-) )

File: realm/src/main/java/io/realm/Realm.java [hunk 4]
```diff
@@ -1717,32 +1716,28 @@ public static synchronized boolean deleteRealmFile(Context context, String fileN
      *
      * @param context an Android {@link android.content.Context}
      * @param fileName the name of the file to compact
+     * @param key Key for opening a encrypted Realm.
```
Comment (bmunkholm) [inline realm/src/main/java/io/realm/Realm.java]: a -> an

File: realm/src/main/java/io/realm/Realm.java (hunk 3 above)
Comment (kneth) [inline realm/src/main/java/io/realm/Realm.java]: It's impossible to argue against intuition but the documentation for `deleteRealmFile()` uses capital R ;-)

File: realm/src/androidTest/java/io/realm/RealmTest.java [hunk 5]
```diff
@@ -917,11 +917,33 @@ public void testWriteCopyTo() throws IOException {
...
+        Realm.deleteRealmFile(getContext(), REALM_NAME);
+        byte[] key = new byte[64];
+        new Random(42).nextBytes(key);
+        Realm realm = Realm.getInstance(getContext(), REALM_NAME, key);
+        realm.close();
+        assertTrue(Realm.compactRealmFile(getContext(), REALM_NAME, key));
+    }
+
     public void testCompactRealmFile() throws IOException {
+        testRealm.close();
```
Comment (emanuelez) [inline realm/src/androidTest/java/io/realm/RealmTest.java]: Not a good idea. This can potentially screw up the reference counting. We should probably use a completely other Realm file.

File: realm/src/androidTest/java/io/realm/RealmTest.java [hunk 6]
```diff
@@ -917,14 +914,57 @@ public void testWriteCopyTo() throws IOException {
...
-        assertTrue(Realm.compactRealmFile(getContext()));
-        long after = new File(getContext().getFilesDir(), copyRealm).length();
+
+    public void testCompactRealmFileThrowsIfOpen() throws IOException {
+        try {
+            Realm.compactRealmFile(getContext());
+        } catch (IllegalStateException expected) {
+            return;
+        }
+        fail();
```
Comment (kneth) [inline realm/src/androidTest/java/io/realm/RealmTest.java]: If you move `fail()` inside the `try` block, the `return` isn't needed.

File: realm/src/main/java/io/realm/Realm.java [hunk 7]
```diff
@@ -1707,58 +1706,75 @@ public static synchronized boolean deleteRealmFile(Context context, String fileN
...
+                sharedGroup.close();
             }
         }
-        return true;
+        return result;
     }
 
     /**
-     * Compact a realm file. A realm file usually contain free/unused space.
+     * Compact a Realm file. A realm file usually contain free/unused space.
```
Comment (kneth) [inline realm/src/main/java/io/realm/Realm.java]: realm -> Realm

File: realm/src/main/java/io/realm/Realm.java [hunk 8]
```diff
@@ -1707,58 +1706,75 @@ public static synchronized boolean deleteRealmFile(Context context, String fileN
...
      * This method removes this free space and the file size is thereby reduced.
      * Objects within the realm files are untouched.
```
Comment (kneth) [inline realm/src/main/java/io/realm/Realm.java]: realm -> Realm

File: realm/src/main/java/io/realm/Realm.java [hunk 9]
```diff
@@ -1707,58 +1706,75 @@ public static synchronized boolean deleteRealmFile(Context context, String fileN
...
      */
     public static boolean compactRealmFile(Context context) {
-        return compactRealmFile(context, DEFAULT_REALM_NAME);
+        return compactRealmFile(context, DEFAULT_REALM_NAME, null);
+    }
+
+    /**
+     * Compact a Realm file. A Realm file usually contain free/unused space.
+     * This method removes this free space and the file size is thereby reduced.
+     * Objects within the realm files are untouched.
```
Comment (kneth) [inline realm/src/main/java/io/realm/Realm.java]: realm -> Realm

**Comment by timanglade** [comment]
Will repeat this during the “how to talk about Realm” presentation.

“Realm” is always capitalized i.e. “a Realm file” but in some context it’s easier to refer to the file extension, which is lowercase. For example:
- “You can compact a Realm file”
- “look for the .realm file in your Documents folder“

**Comment by kneth** [comment]
I have disabled compacting encrypted Realms as it fails on some devices.

@cmelchior @emanuelez @tgoyne @finnschiermer

File: changelog.txt [hunk 10]
```diff
@@ -1,4 +1,5 @@
 0.81
+ * Realm.compactRealmFile() now also works for encrypted Realms.
```
Comment (cmelchior) [inline changelog.txt]: Well, no :)

File: realm/src/androidTest/java/io/realm/RealmTest.java [hunk 11]
```diff
@@ -937,14 +934,64 @@ public void testWriteCopyTo() throws IOException {
...
+        String REALM_NAME = "enc.realm";
+        Realm.deleteRealmFile(getContext(), REALM_NAME);
+        byte[] key = new byte[64];
+        new Random(42).nextBytes(key);
+        Realm realm = Realm.getInstance(getContext(), REALM_NAME, key);
+        realm.close();
+        // TODO: remove try/catch block when compacting encrypted Realms is supported
+        try {
+            assertTrue(Realm.compactRealmFile(getContext(), REALM_NAME, key));
+        } catch (IllegalArgumentException expected) {
```
Comment (cmelchior) [inline realm/src/androidTest/java/io/realm/RealmTest.java]: Instead it should be 
```
Realm.compactRealmFile(getContext(), REALM_NAME, key);
fail();
```

File: realm/src/androidTest/java/io/realm/RealmTest.java [hunk 12]
```diff
@@ -937,14 +934,64 @@ public void testWriteCopyTo() throws IOException {
...
+        String REALM_NAME = "enc.realm";
+        Realm.deleteRealmFile(getContext(), REALM_NAME);
+        byte[] key = new byte[64];
+        new Random(42).nextBytes(key);
+        Realm realm = Realm.getInstance(getContext(), REALM_NAME, key);
+        populateTestRealm(realm, 100);
+        realm.close();
+        // TODO: remove try/catch block when compacting encrypted Realms is supported
+        try {
+            assertTrue(Realm.compactRealmFile(getContext(), REALM_NAME, key));
```
Comment (cmelchior) [inline realm/src/androidTest/java/io/realm/RealmTest.java]: Same

**Comment by finnschiermer** [comment]
This look like a testcase error: when calling compact on the SharedGroup, it must be in the attached state (file must have been opened). In the testcases you close SharedGroup right before calling compact.

**Comment by kneth** [comment]
@finnschiermer The `Realm.compactRealmFile()` creates a `SharedGroup` object (without implicit transactions), compacts the file, and closes the `SharedGroup`.

**Comment by finnschiermer** [comment]
okidoki
