### PR TITLE
Remove readonly for defaultPermissionRealmConfig

### LINKED ISSUE #5414: Cannot open the read only Realm. 'Permission' is missing
ISSUE TYPE: BUG
=============

#### Goal

> Fetch permissions for a user

#### Expected Results

> Successful fetch of permissions

#### Actual Results

>  REALM_JAVA: io.realm.exceptions.RealmMigrationNeededException: Cannot open the read only Realm. 'Permission' is missing.
                                                                   at io.realm.Realm.<init>(Realm.java:165)
                                                                   at io.realm.Realm.createInstance(Realm.java:417)
                                                                   at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:348)
                                                                   at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
                                                                   at io.realm.RealmCache$CreateRealmRunnable.run(RealmCache.java:115)
                                                                   at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                   at java.lang.Thread.run(Thread.java:764)
                                                               `CreateRealmRunnable` failed.

#### Steps & Code to Reproduce

> Following instructions [here](https://realm.io/docs/java/3.7.1/#retrieving-permissions)

#### Code Sample

```java
public static void fetchPermissions() {
        final PermissionManager pm = SyncUser.currentUser().getPermissionManager();
        // Retrieve
        pm.getPermissions(new PermissionManager.PermissionsCallback() {
            @Override
            public void onSuccess(RealmResults<Permission> permissions) {

                Log.i(TAG, "PRINTING ALL PERMISSIONS");
                printPermissions(permissions);

                // Change listeners can be registered
                // The PermissionManager keeps a reference to these as long as the Permission Manager
                // is open, so they do not risk getting GC'ed
                permissions.addChangeListener(new RealmChangeListener<RealmResults<Permission>>() {
                    @Override
                    public void onChange(RealmResults<Permission> permissions) {
                        Log.i(TAG, "CHANGED PERMISSIONS");
                        printPermissions(permissions);
                    }
                });
                pm.close();
            }

            @Override
            public void onError(ObjectServerError error) {
                // handle error
                Log.i(TAG, "Error fetching permissions");
                Log.i(TAG, error.toString());
                pm.close();
            }
        });
}
```

#### Version of Realm and tooling
Realm version(s): 3.7.1

Realm sync feature enabled: yes

Android Studio version: 2.3.3

Which Android version and device: ?

### PR DESCRIPTION
**Pull request by beeender**
close #5414

### CODE REVIEW

File: realm/realm-library/src/objectServer/java/io/realm/PermissionManager.java [hunk 1]
```diff
@@ -220,7 +220,9 @@ public void onError(SyncSession session, ObjectServerError error) {
                 })
                 .modules(new PermissionModule())
                 .waitForInitialRemoteData()
-                .readOnly()
+                // FIXME: Something is seriously wrong with the Permission Realm. It doesn't seem to
```
Comment (nhachicha) [inline realm/realm-library/src/objectServer/java/io/realm/PermissionManager.java]: Can we please create an issue to keep track of the FIXME?
