### PR TITLE
Hide StandardRealmSchema class from public API.

### LINKED ISSUE #4443: realm getSchema incorrect return type
realm.getSchema() function return object from type StandardRealmSchema 
this type is object have packcge only access so it is impossible to access his methods,
the only way is to convert this object to (RealmSchema), i think it is mistake 
the return type need to be RealmSchema and not StandardRealmSchema 

realm version in use :3.1.0

### PR DESCRIPTION
**Pull request by zaki50**
fixes #4443 

@realm/java

### CODE REVIEW

**Comment by zaki50** [comment]
To save method count, should we use `getSchema()` and cast it to `StandardRealmSchema` when using it internally?

**Comment by Zhuinden** [comment]
That seems scary long-term.

**Comment by bmeike** [comment]
I totally agree with @Zhuinden: not using Java (especially typing) in the interests of method count or some other Colt McAnliss-y metric is, absolutely, misguided (a variety of premature) optimization.

**Comment by zaki50** [comment]
@bmeike 👍

**Comment by zaki50** [comment]
@bmeike updated.

File: realm/realm-library/src/main/java/io/realm/OsRealmSchema.java [hunk 1]
```diff
@@ -62,6 +64,26 @@ public boolean contains(String className) {
...
+            throw new UnsupportedOperationException();
+        }
+
+        @Override
+        RealmObjectSchema getSchemaForClass(Class<? extends RealmModel> clazz) {
+            throw new UnsupportedOperationException();
+        }
+
+        @Override
+        StandardRealmObjectSchema getSchemaForClass(String className) {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/OsRealmSchema.java]: This should just return `RealmObjectSchema`?

File: realm/realm-library/src/main/java/io/realm/OsRealmSchema.java [hunk 2]
```diff
@@ -163,6 +185,26 @@ public boolean contains(String className) {
...
+        throw new UnsupportedOperationException();
+    }
+
+    @Override
+    RealmObjectSchema getSchemaForClass(Class<? extends RealmModel> clazz) {
+        throw new UnsupportedOperationException();
+    }
+
+    @Override
+    StandardRealmObjectSchema getSchemaForClass(String className) {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/OsRealmSchema.java]: Same

File: realm/realm-library/src/main/java/io/realm/RealmSchema.java [hunk 3]
```diff
@@ -145,4 +145,9 @@ private void checkIndices() {
             throw new IllegalStateException("Attempt to use column index before set.");
         }
     }
+
+    abstract Table getTable(Class<? extends RealmModel> clazz);
+    abstract Table getTable(String className);
+    abstract RealmObjectSchema getSchemaForClass(Class<? extends RealmModel> clazz);
+    abstract StandardRealmObjectSchema getSchemaForClass(String className);
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmSchema.java]: Return `RealmObjectSchema`?

Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/RealmSchema.java]: Right!

File: realm/realm-library/src/main/java/io/realm/OsRealmSchema.java (hunk 1 above)
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/OsRealmSchema.java]: This should be `OsRealmObjectSchema`.
Narrowing return type from parent class is valid since Java5.

File: realm/realm-library/src/main/java/io/realm/OsRealmSchema.java (hunk 2 above)
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/OsRealmSchema.java]: This should be `OsRealmObjectSchema`.

**Comment by zaki50** [comment]
@cmelchior fixed.

File: realm/realm-library/src/main/java/io/realm/OsRealmSchema.java (hunk 1 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/OsRealmSchema.java]: Missed this

Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/OsRealmSchema.java]: done.

**Comment by beeender** [comment]
please merge this after #4450 merged. thanks

**Comment by bmeike** [comment]
Thanks for doing that.  I think it will give us a better clue about what we need to implement for OsRealmsSchema.
