### PR TITLE
Checking to see if a transaction is in progress & more.

### LINKED ISSUE #1682: Error in executeTransaction hides underlying problem
I usually do all my transactions with the method *executeTransaction*. It seems that if there is a runtime error, the underlying error gets hidden. 

```
public void executeTransaction(Transaction transaction) {
        if (transaction == null)
            throw new IllegalArgumentException("Transaction should not be null");

        beginTransaction();
        try {
            transaction.execute(this);
            commitTransaction();
        } catch (RuntimeException e) {
            cancelTransaction(); <----
            throw new RealmException("Error during transaction.", e);
        } catch (Error e) {
            cancelTransaction();
            throw e;
        }
    }
```
This is part of the stack trace I receive:

```
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime: java.lang.IllegalStateException: Not inside a transaction.
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime:     at io.realm.internal.ImplicitTransaction.rollbackAndContinueAsRead(ImplicitTransaction.java:71)
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime:     at io.realm.internal.SharedGroupManager.rollbackAndContinueAsRead(SharedGroupManager.java:125)
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime:     at io.realm.BaseRealm.cancelTransaction(BaseRealm.java:348)
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime:     at io.realm.Realm.cancelTransaction(Realm.java:113)
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime:     at io.realm.Realm.executeTransaction(Realm.java:1037)
```

It is an issue as it hides the runtime exception I would actually like to log

### PR DESCRIPTION
**Pull request by donnfelker**
Fixes #1682

Checking to see if a transaction is currently in progress for sync and async transaction pathways. Also adding logging. Added a test helper to assist with log assertion.

### CODE REVIEW

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 1]
```diff
@@ -113,6 +114,79 @@ public void onError(Exception e) {
         exitOrThrow(executorService, signalCallbackFinished, signalClosedRealm, backgroundLooper, threadAssertionError);
     }
 
+    public void testAsyncTransactionThatThrowsRuntimeException() throws Throwable {
+        final TestHelper.TestLogger testLogger = new TestHelper.TestLogger();
+        RealmLog.add(testLogger);
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: You also need to remove it again, since this is a static field and not doing so can impact other tests.

File: realm/realm-library/src/androidTest/java/io/realm/RealmTest.java [hunk 2]
```diff
@@ -780,6 +781,49 @@ public void execute(Realm realm) {
         assertEquals(0, testRealm.allObjects(Owner.class).size());
     }
 
+    public void testExecuteTransactionCancelledInExecuteThrowsRuntimeException() {
+        TestHelper.TestLogger testLogger = new TestHelper.TestLogger();
+        RealmLog.add(testLogger);
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmTest.java]: Same, needs to be removed before the test ends

File: realm/realm-library/src/androidTest/java/io/realm/TestHelper.java [hunk 3]
```diff
@@ -242,6 +242,71 @@ public void e(String message, Throwable t) {
         };
     }
 
+    /**
+     * Returns a naive logger that can be used to test the values that are sent to the logger.
+     *
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/TestHelper.java]: Remove empty line

File: realm/realm-library/src/androidTest/java/io/realm/TestHelper.java [hunk 4]
```diff
@@ -242,6 +242,71 @@ public void e(String message, Throwable t) {
...
+     */
+    public static class TestLogger implements Logger {
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/TestHelper.java]: Nice idea

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 5]
```diff
@@ -1016,10 +1016,19 @@ public void executeTransaction(Transaction transaction) {
             transaction.execute(this);
             commitTransaction();
         } catch (RuntimeException e) {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: I'm trying to think we we are making a difference between Runtime and Exceptions, and fail to come up with a sensible one. The only thing it does is masking the real error, which was also the complaint in the issue. IMO we should remove the wrapper RealmException, and just collapse these two. What do you think?

**Comment by cmelchior** [comment]
Generally looks good. I added an idea for an optimisation, and we need to update the changelog as well.

File: realm/realm-library/src/main/java/io/realm/Realm.java (hunk 5 above)
Comment (donnfelker) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: `error` is being caught. But the docs for Error provide the following insight: ```is the superclass of all classes that represent unrecoverable
 * errors. When errors are thrown, they should not be caught by application
 * code.```  Should this be an error? Or should this be higher order such as `Throwable`?  I'm all for throwing the root error. What is the reason for the RealmException?

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Ah, I misread it for Exception the first time. The reason we handled Error differently here was because we don't want people to catch and potentially ignore an OutOfMemoryError which can potentially corrupt a Realm file if you keep writing to it after that.

I think we added the RealmException to be able to document error scenarios better, i.e. you only need to catch RealmException, but I'm starting to wonder if that was a smart choice. If not, then just catching Throwable, cancel the transaction and rethrow should be fine.

**Comment by donnfelker** [comment]
@cmelchior Take a look now and let me know what you think. Commits have been squashed, rebased on top of master and changelog has been updated as well.

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 6]
```diff
@@ -1016,10 +1016,11 @@ public void executeTransaction(Transaction transaction) {
...
-            cancelTransaction();
-            throw new RealmException("Error during transaction.", e);
-        } catch (Error e) {
-            cancelTransaction();
+            if(isInTransaction()) {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: spacing between `if (

File: realm/realm-library/src/main/java/io/realm/Realm.java (hunk 5 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Shouldn't this be `Throwable`?

File: changelog.txt [hunk 7]
```diff
@@ -1,4 +1,5 @@
 0.85.0
+ * BREAKING CHANGE: ChangeRealm#executeTransaction will catch a RuntimeException (no longer catches Error) and will log a useful error message, cancel the transaction and re-throw the exception when said RuntimeException occurs (#1682).
```
Comment (cmelchior) [inline changelog.txt]: To much information I think.
Maybe something like  `BREAKING CHANGE: Realm.executeTransaction() now directly throws any RuntimeException instead of wrapping it in a RealmException (#1682)`

**Comment by cmelchior** [comment]
Looks good. Only had a few cosmetic changes.

**Comment by donnfelker** [comment]
@cmelchior Cosmetic changes applied

**Comment by cmelchior** [comment]
Unit test is failing. Otherwise it looks good to me :+1: 
```
io.realm.RealmTest > testExecuteTransactionCancel[Nexus 9 - 5.0.1] [31mFAILED [0m
	java.lang.RuntimeException: Boom
	at io.realm.RealmTest$3.execute(RealmTest.java:776)
```

@realm/java

File: changelog.txt [hunk 8]
```diff
@@ -1,4 +1,5 @@
 0.85.0
+ * BREAKING CHANGE: Realm.executeTransaction() now directly throws any RuntimeException instead of wrapping it in a RealmException (#1682)
```
Comment (kneth) [inline changelog.txt]: Please add `.` at the end of the line.

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 9]
```diff
@@ -1069,11 +1070,19 @@ public void run() {
                                 });
                             }
                         } else {
-                            bgRealm.cancelTransaction();
+                            if(bgRealm.isInTransaction()) {
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: `if(` -> `if (`

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 10]
```diff
@@ -1069,11 +1070,19 @@ public void run() {
...
+                                bgRealm.cancelTransaction();
+                            } else {
+                                RealmLog.w("Thread is interrupted. Could not cancel transaction, not currently in a transaction.");
+                            }
                         }
 
                     } catch (final Exception e) {
-                        bgRealm.cancelTransaction();
+                        if(bgRealm.isInTransaction()) {
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: `if(` -> `if (`

**Comment by beeender** [comment]
:+1:

**Comment by cmelchior** [comment]
@donnfelker Merging
