### PR TITLE
Nh/fix 1894 changelistener not called

### LINKED ISSUE #1894: RealmChangeListener never called inside RealmResults
Hi, i use realm for a lot of time but today i want to try use new feature called "Async query".  I would be grateful for tell me what I'm doing wrong.
 
realm version:     compile 'io.realm:realm-android:0.86.0'
empty main activity snippet:

     @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main_activity);
        RealmResults< MyRealmObject> realmResults = Realm.getInstance(this).where(MyRealmObject.class).findAllAsync();
        realmResults.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange() {
                System.out.println("Never called...");
            }
        });
}

If i attached debbuger it stay on notifyChangeListeners and listener is not called because "this.currentTableViewVersion != version". RealmQuery is loaded because after few moment i have acces to data inside list.
realmresult

### PR DESCRIPTION
**Pull request by nhachicha**
fix #1894 + provide a work around for #1886 while waiting for core fix, the work around avoid calling _sync_if_needed_ if the RealmObject/RealmResults doesn't have any listeners

Note: it will be faster (small diff) to review this PR first https://github.com/realm/realm-java/pull/1892

### CODE REVIEW

**Comment by nhachicha** [comment]
@realm/java

File: realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTest.java [hunk 1]
```diff
@@ -67,6 +79,442 @@ public void run() {
...
+                });
+
+                realm.beginTransaction();
+                final Dog dog = realm.createObject(Dog.class);
+                realm.commitTransaction();
+
+                dog.addChangeListener(new RealmChangeListener() {
+                    @Override
+                    public void onChange() {
+                        assertEquals("Akamaru", dog.getName());
```
Comment (kneth) [inline realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTest.java]: Even ninja dogs can't hide when they are in a Realm :-)

Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTest.java]: _poof_

File: realm/realm-library/src/main/java/io/realm/RealmResults.java [hunk 2]
```diff
@@ -831,15 +824,17 @@ public void removeChangeListeners() {
...
-        if (currentTableViewVersion != version) {
-            currentTableViewVersion = version;
-            for (RealmChangeListener listener : listeners) {
-                listener.onChange();
+        if (listeners != null && !listeners.isEmpty()) {
+            // table might be null (if the async query didn't complete
+            // but we have already registered listeners for it)
+            if (pendingQuery != null && !isCompleted) return;
+
+            long version = table.sync();
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/RealmResults.java]: Should we check if `table` is a `TableView`? If not, an exception will be thrown.

Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/RealmResults.java]: That's a good point, but all calls to `RealmResults#createFromTableOrView`, `RealmResults#createFromDynamicTableOrView` are using `TableView`.  

`RealmResults#createFromTableQuery` & `RealmResults#createFromDynamicClass`  are used by async queries that will call `importHandoverTableView` to populate `Table` with a `TableView`

**Comment by nhachicha** [comment]
retest this please

**Comment by nhachicha** [comment]
retest this please

File: changelog.txt [hunk 3]
```diff
@@ -6,6 +6,9 @@
  * Updated ProGuard configuration (#1904).
  * Fixed a bug which could cause a crash when closing Realm instances in change listeners (#1900).
  * Fix a crash occurring during update of multiple async queries (#1895).
+ * Fix (#1884) listeners not triggered for RealmObject & RealmResults created using copy or create methods.
```
Comment (cmelchior) [inline changelog.txt]: Move issue to the end

File: changelog.txt [hunk 4]
```diff
@@ -6,6 +6,9 @@
...
+ * Fix (#1894) RealmChangeListener never called inside RealmResults.
```
Comment (cmelchior) [inline changelog.txt]: Move issue to the end

File: changelog.txt [hunk 5]
```diff
@@ -6,6 +6,9 @@
...
+ * Work around (waiting Core fix) for (#1886) crash when calling _sync_if_needed on a cleared View.
```
Comment (cmelchior) [inline changelog.txt]: For the purpose of the user it is fixed though?

**Comment by cmelchior** [comment]
Small comment about wording in the changelog, otherwise :+1:

**Comment by kneth** [comment]
:+1:
