### PR TITLE
Access to RealmResults based on deleted RealmList

### LINKED ISSUE #1945: Detect invalid RealmResults
The following code might lead to a native crash:

    realm.beginTransaction();
    RealmResults<Owner> owners = realm.allObjects(Owner.class);
    RealmResults<Dog> dogs = owners.first().where().equalTo("dogs.name", "Fido").findAll();
    owners.clear();
    long nDogs = dogs.size(); // crash here
    realm.commitTransaction();

The reason is that Realm's storage engine doesn't invalidate `dogs` after `owners.clear()`. Once it does, an exception should be thrown at `dogs.size()`.

See also https://github.com/realm/realm-core/issues/1413

### PR DESCRIPTION
**Pull request by beeender**
* When the original RealmList is deleted, for most methods of
  RealmResults should just work without crash by just treat it like an
  empty RealmResults.
* RealmResults.where() throws IllegalStateExecption in this case.
* RealmResults.isValid() return false in this case.

This is a temp fix, check https://github.com/realm/realm-core/pull/1434
for more details.

Close #1945

### CODE REVIEW

**Comment by beeender** [comment]
@realm/java Ready for review. CI will pass after new core integrated.

File: realm/realm-library/src/androidTest/java/io/realm/RealmResultsTest.java [hunk 1]
```diff
@@ -1146,4 +1146,100 @@ public void testComparisons() {
...
+        RealmResults<Dog> dogs = owner.getDogs().where().equalTo(Dog.FIELD_NAME, "name_0").findAll();
+        //dogs = dogs.where().findFirst().getOwner().getDogs().where().equalTo(Dog.FIELD_NAME, "name_0").findAll();
+
+        testRealm.beginTransaction();
+        owner.removeFromRealm();
+        testRealm.commitTransaction();
+        return dogs;
+    }
+
+    public void testisValidResultsBuiltOnDeletedLinkView() {
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmResultsTest.java]: We will have to remember to convert all these to JUnit4 when merging with master :(

File: realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTest.java [hunk 2]
```diff
@@ -1827,8 +1826,8 @@ public void onChange() {
                         // Check if cat has been added to the realmObjects in case of the behaviour of getCat changes
                         for (WeakReference<RealmObject> weakReference : realm.handlerController.realmObjects.keySet()) {
                             if (weakReference.get() == cat) {
-                               foundKey = true;
-                               break;
+                                foundKey = true;
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTest.java]: Isn't this indentation wrong?

File: realm/realm-library/src/main/java/io/realm/RealmResults.java [hunk 3]
```diff
@@ -856,13 +872,42 @@ void notifyChangeListeners() {
...
+                RealmLog.d("The parent RealmList has been deleted already.");
+            }
             if (currentTableViewVersion != version) {
                 currentTableViewVersion = version;
                 for (RealmChangeListener listener : listeners) {
                     listener.onChange();
                 }
             }
+            // No point to keep those listeners, just clear them.
+            if (version == TABLE_VIEW_VERSION_REALM_LIST_DELETED) {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmResults.java]: Is this a good idea? As the user are not aware they get removed? I would probably log it is happening.

File: realm/realm-library/src/main/java/io/realm/internal/DeleteRealmListException.java [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package io.realm.internal;
+
+import io.realm.exceptions.RealmException;
+
+/**
+ *  Triggered from JNI level when access a RealmResults whose parent RealmList has been deleted already.
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/DeleteRealmListException.java]: access -> accessing

**Comment by cmelchior** [comment]
Apart from a few comments. It looks good :+1: 
 I'm most concerned about removing the changelisteners without warning. Can you elaborate on the reasoning for doing it?

File: realm/realm-jni/src/io_realm_internal_tableview.cpp [hunk 5]
```diff
@@ -25,20 +25,32 @@
...
+        ThrowException(env, TableInvalid, "The Realm has been closed and is no longer accessible.");
+        return false;
     }
-    return valid;
+    return true;
 }
 
+inline bool is_view_in_sync(JNIEnv* /*env*/, jlong nativeViewPtr) {
+    try {
+        TV(nativeViewPtr)->sync_if_needed();
```
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: Can `sync_if_needed()` throw other exceptions? If so, please can them too.

File: realm/realm-jni/src/io_realm_internal_tableview.cpp [hunk 6]
```diff
@@ -25,20 +25,32 @@
...
+    } catch (realm::DeletedLinkView&) {
+        // FIXME: Temp fix for https://github.com/realm/realm-core/pull/1434
```
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: Yes, using exceptions for flow control is a bad habit :-)

File: realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTest.java (hunk 2 above)
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTest.java]: Nvm. This edit is correct

File: realm/realm-jni/src/io_realm_internal_tableview.cpp [hunk 7]
```diff
@@ -25,20 +25,32 @@
 using namespace realm;
 
 // if you disable the validation, please remember to call sync_in_needed()
```
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: `sync_in_needed` -> `sync_is_needed`

File: realm/realm-jni/src/io_realm_internal_tableview.cpp [hunk 8]
```diff
@@ -25,20 +25,32 @@
...
+    }
+    if (!TV(nativeViewPtr)->is_attached()) {
+        ThrowException(env, TableInvalid, "The Realm has been closed and is no longer accessible.");
+        return false;
     }
-    return valid;
+    return true;
 }
 
+inline bool is_view_in_sync(JNIEnv* /*env*/, jlong nativeViewPtr) {
```
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: The name suggests that it's a predicate but the side effect is that the table view is sync'ed.

File: realm/realm-library/src/androidTest/java/io/realm/RealmResultsTest.java (hunk 1 above)
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmResultsTest.java]: Yes, sure!

**Comment by beeender** [comment]
@cmelchior User can check with `isValid` in the listener. It would also be OK that we keep the change listener, but actually the `RealmResults` in that case won't be changed any more.

**Comment by cmelchior** [comment]
@beeender Good point. Removing them sounds fair in that case as it will make other change notifications be faster and explicitly calling remove(listener) would just be a no-op.

I would change the comment above the section to mention that no further changes can happen though as the current wording did confuse me a bit.

Apart from that, it looks ready to merge.

**Comment by dalinaum** [comment]
:+1:
