### PR TITLE
Stale local ref crash with Object listener

### LINKED ISSUE #4437: JNI Error
#### Goal

To be able to commit a transaction

#### Expected Results

To succeed and save to the Realm Database

#### Actual Results

Crashes

#### Code Sample

Affected Code, crashes on the first line (`executeTransaction`)
```java
Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            getDepartures().clear();

                            if(result.getTrainServices() != null && !result.getTrainServices().isEmpty()) {
                                for (Service service : result.getTrainServices()) {
                                    service.setId(getCrs(), true);
                                    getDepartures().add(realm.copyToRealmOrUpdate(service));
                                }
                            }

                            setDeparturesGathered(Calendar.getInstance().getTime());
                        }
                    });
```

Stack Trace: 
```
04-05 15:29:59.122 12199-12199/com.github.binpower93.stationhubapp E/art: JNI ERROR (app bug): attempt to use stale Local 0x100019 (should be 0x19)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0x100019
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]     from void io.realm.internal.SharedRealm.nativeCommitTransaction(long)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470] "main" prio=5 tid=1 Runnable
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   | group="main" sCount=0 dsCount=0 obj=0x74130000 self=0xeec05400
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   | sysTid=12199 nice=-10 cgrp=default sched=0/0 handle=0xf18d2534
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   | state=R schedstat=( 2844241477 208878546 2183 ) utm=256 stm=27 core=4 HZ=100
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   | stack=0xff336000-0xff338000 stackSize=8MB
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   | held mutexes= "mutator lock"(shared held)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #00 pc 00350ab5  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #01 pc 003311f9  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+308)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #02 pc 00239895  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+848)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #03 pc 00239e2b  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #04 pc 00334c25  /system/lib/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+240)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #05 pc 000ca321  /system/lib/libart.so (_ZN3art11ScopedCheck13CheckInstanceERNS_18ScopedObjectAccessENS0_12InstanceKindEP8_jobjectb+120)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #06 pc 000c98d3  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+190)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #07 pc 000ca90b  /system/lib/libart.so (_ZN3art11ScopedCheck12CheckVarArgsERNS_18ScopedObjectAccessEPKNS_7VarArgsE+186)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #08 pc 000c9881  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+108)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #09 pc 000c8d0b  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+802)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #10 pc 000cceb7  /system/lib/libart.so (_ZN3art8CheckJNI13CheckCallArgsERNS_18ScopedObjectAccessERNS_11ScopedCheckEP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDNS_10InvokeTypeEPKNS_7VarArgsE+114)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #11 pc 000cc4e5  /system/lib/libart.so (_ZN3art8CheckJNI11CallMethodVEPKcP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDSt9__va_listNS_9Primitive4TypeENS_10InvokeTypeE+512)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #12 pc 000c26b9  /system/lib/libart.so (_ZN3art8CheckJNI15CallVoidMethodVEP7_JNIEnvP8_jobjectP10_jmethodIDSt9__va_list+44)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #13 pc 00022c63  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #14 pc 0005df55  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #15 pc 0002c605  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #16 pc 0007b345  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #17 pc 0007b465  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #18 pc 0008f697  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #19 pc 0008f84d  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #20 pc 00080dcb  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #21 pc 000734a9  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #22 pc 0002df31  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (Java_io_realm_internal_SharedRealm_nativeCommitTransaction+64)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   native: #23 pc 0001a78d  /data/app/com.github.binpower93.stationhubapp-2/oat/arm/base.odex (Java_io_realm_internal_SharedRealm_nativeCommitTransaction__J+80)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at io.realm.internal.SharedRealm.nativeCommitTransaction(Native method)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at io.realm.internal.SharedRealm.commitTransaction(SharedRealm.java:251)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at io.realm.BaseRealm.commitTransaction(BaseRealm.java:320)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at io.realm.Realm.commitTransaction(Realm.java:127)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at io.realm.Realm.executeTransaction(Realm.java:1348)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at com.github.binpower93.stationhubapp.dataaccess.database.Station$4.success(Station.java:198)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at com.github.binpower93.stationhubapp.dataaccess.database.Station$4.success(Station.java:193)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at com.github.binpower93.stationhubapp.dataaccess.APIHelper$1.success(APIHelper.java:96)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at com.github.binpower93.stationhubapp.dataaccess.APIHelper$1.success(APIHelper.java:93)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at android.os.Handler.handleCallback(Handler.java:751)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at android.os.Handler.dispatchMessage(Handler.java:95)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at android.os.Looper.loop(Looper.java:154)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at android.app.ActivityThread.main(ActivityThread.java:6121)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at java.lang.reflect.Method.invoke!(Native method)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-05 15:29:59.170 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/java_vm_ext.cc:470] 
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] Runtime aborting...
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] Aborting thread:
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "main" prio=10 tid=1 Native
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | group="" sCount=0 dsCount=0 obj=0x74130000 self=0xeec05400
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12199 nice=-10 cgrp=default sched=0/0 handle=0xf18d2534
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=R schedstat=( 2869857571 209014744 2191 ) utm=257 stm=28 core=4 HZ=100
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xff336000-0xff338000 stackSize=8MB
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes= "abort lock"
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00350ab5  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 003311f9  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+308)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 003242b1  /system/lib/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+24)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 00324139  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+424)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 0031ae25  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 000b5285  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1132)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #06 pc 00239bc5  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1664)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #07 pc 00239e2b  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #08 pc 00334c25  /system/lib/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+240)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #09 pc 000ca321  /system/lib/libart.so (_ZN3art11ScopedCheck13CheckInstanceERNS_18ScopedObjectAccessENS0_12InstanceKindEP8_jobjectb+120)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #10 pc 000c98d3  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+190)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #11 pc 000ca90b  /system/lib/libart.so (_ZN3art11ScopedCheck12CheckVarArgsERNS_18ScopedObjectAccessEPKNS_7VarArgsE+186)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #12 pc 000c9881  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+108)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #13 pc 000c8d0b  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+802)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #14 pc 000cceb7  /system/lib/libart.so (_ZN3art8CheckJNI13CheckCallArgsERNS_18ScopedObjectAccessERNS_11ScopedCheckEP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDNS_10InvokeTypeEPKNS_7VarArgsE+114)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #15 pc 000cc4e5  /system/lib/libart.so (_ZN3art8CheckJNI11CallMethodVEPKcP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDSt9__va_listNS_9Primitive4TypeENS_10InvokeTypeE+512)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #16 pc 000c26b9  /system/lib/libart.so (_ZN3art8CheckJNI15CallVoidMethodVEP7_JNIEnvP8_jobjectP10_jmethodIDSt9__va_list+44)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #17 pc 00022c63  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #18 pc 0005df55  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #19 pc 0002c605  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #20 pc 0007b345  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #21 pc 0007b465  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #22 pc 0008f697  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #23 pc 0008f84d  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #24 pc 00080dcb  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #25 pc 000734a9  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #26 pc 0002df31  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (Java_io_realm_internal_SharedRealm_nativeCommitTransaction+64)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #27 pc 0001a78d  /data/app/com.github.binpower93.stationhubapp-2/oat/arm/base.odex (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at io.realm.internal.SharedRealm.nativeCommitTransaction(Native method)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at io.realm.internal.SharedRealm.commitTransaction(SharedRealm.java:251)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at io.realm.BaseRealm.commitTransaction(BaseRealm.java:320)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at io.realm.Realm.commitTransaction(Realm.java:127)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at io.realm.Realm.executeTransaction(Realm.java:1348)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.github.binpower93.stationhubapp.dataaccess.database.Station$4.success(Station.java:198)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.github.binpower93.stationhubapp.dataaccess.database.Station$4.success(Station.java:193)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.github.binpower93.stationhubapp.dataaccess.APIHelper$1.success(APIHelper.java:96)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.github.binpower93.stationhubapp.dataaccess.APIHelper$1.success(APIHelper.java:93)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at android.os.Handler.handleCallback(Handler.java:751)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at android.os.Handler.dispatchMessage(Handler.java:95)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at android.os.Looper.loop(Looper.java:154)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at android.app.ActivityThread.main(ActivityThread.java:6121)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.reflect.Method.invoke!(Native method)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] Dumping all threads without appropriate locks held: thread list lock mutator lock
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] All threads:
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] DALVIK THREADS (48):
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "main" prio=10 tid=1 Runnable
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | group="" sCount=0 dsCount=0 obj=0x74130000 self=0xeec05400
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12199 nice=-10 cgrp=default sched=0/0 handle=0xf18d2534
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=R schedstat=( 2899954027 209045942 2195 ) utm=258 stm=30 core=4 HZ=100
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xff336000-0xff338000 stackSize=8MB
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes= "abort lock" "mutator lock"(shared held)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00350ab5  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 003311f9  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+308)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 00343221  /system/lib/libart.so (_ZN3art14DumpCheckpoint3RunEPNS_6ThreadE+620)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 0033d22b  /system/lib/libart.so (_ZN3art10ThreadList13RunCheckpointEPNS_7ClosureE+330)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 0033cf27  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEb+586)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 00324105  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+372)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #06 pc 0031ae25  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #07 pc 000b5285  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1132)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #08 pc 00239bc5  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1664)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #09 pc 00239e2b  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #10 pc 00334c25  /system/lib/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+240)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #11 pc 000ca321  /system/lib/libart.so (_ZN3art11ScopedCheck13CheckInstanceERNS_18ScopedObjectAccessENS0_12InstanceKindEP8_jobjectb+120)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #12 pc 000c98d3  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+190)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #13 pc 000ca90b  /system/lib/libart.so (_ZN3art11ScopedCheck12CheckVarArgsERNS_18ScopedObjectAccessEPKNS_7VarArgsE+186)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #14 pc 000c9881  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+108)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #15 pc 000c8d0b  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+802)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #16 pc 000cceb7  /system/lib/libart.so (_ZN3art8CheckJNI13CheckCallArgsERNS_18ScopedObjectAccessERNS_11ScopedCheckEP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDNS_10InvokeTypeEPKNS_7VarArgsE+114)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #17 pc 000cc4e5  /system/lib/libart.so (_ZN3art8CheckJNI11CallMethodVEPKcP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDSt9__va_listNS_9Primitive4TypeENS_10InvokeTypeE+512)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #18 pc 000c26b9  /system/lib/libart.so (_ZN3art8CheckJNI15CallVoidMethodVEP7_JNIEnvP8_jobjectP10_jmethodIDSt9__va_list+44)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #19 pc 00022c63  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #20 pc 0005df55  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #21 pc 0002c605  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #22 pc 0007b345  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.389 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #23 pc 0007b465  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #24 pc 0008f697  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #25 pc 0008f84d  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #26 pc 00080dcb  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #27 pc 000734a9  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #28 pc 0002df31  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (Java_io_realm_internal_SharedRealm_nativeCommitTransaction+64)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #29 pc 0001a78d  /data/app/com.github.binpower93.stationhubapp-2/oat/arm/base.odex (Java_io_realm_internal_SharedRealm_nativeCommitTransaction__J+80)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at io.realm.internal.SharedRealm.nativeCommitTransaction(Native method)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at io.realm.internal.SharedRealm.commitTransaction(SharedRealm.java:251)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at io.realm.BaseRealm.commitTransaction(BaseRealm.java:320)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at io.realm.Realm.commitTransaction(Realm.java:127)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at io.realm.Realm.executeTransaction(Realm.java:1348)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.github.binpower93.stationhubapp.dataaccess.database.Station$4.success(Station.java:198)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.github.binpower93.stationhubapp.dataaccess.database.Station$4.success(Station.java:193)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.github.binpower93.stationhubapp.dataaccess.APIHelper$1.success(APIHelper.java:96)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.github.binpower93.stationhubapp.dataaccess.APIHelper$1.success(APIHelper.java:93)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at android.os.Handler.handleCallback(Handler.java:751)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at android.os.Handler.dispatchMessage(Handler.java:95)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at android.os.Looper.loop(Looper.java:154)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at android.app.ActivityThread.main(ActivityThread.java:6121)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.reflect.Method.invoke!(Native method)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "Jit thread pool worker thread 0" prio=10 tid=2 Native
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c710d0 self=0xe7892000
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12204 nice=9 cgrp=default sched=0/0 handle=0xee324920
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 779551443 125639352 894 ) utm=66 stm=11 core=5 HZ=100
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xee226000-0xee228000 stackSize=1022KB
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes=
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x8c/0x98
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xd4/0x130
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait+0xfc/0x210
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: do_futex+0xe0/0x920
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_SyS_futex+0xe8/0x17c
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00017404  /system/lib/libc.so (syscall+28)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 000b6e49  /system/lib/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+92)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 00344785  /system/lib/libart.so (_ZN3art10ThreadPool7GetTaskEPNS_6ThreadE+160)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 00343fa7  /system/lib/libart.so (_ZN3art16ThreadPoolWorker3RunEv+62)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 00343acf  /system/lib/libart.so (_ZN3art16ThreadPoolWorker8CallbackEPv+78)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 000470b3  /system/lib/libc.so (_ZL15__pthread_startPv+22)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #06 pc 00019e3d  /system/lib/libc.so (__start_thread+6)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   (no managed stack frames)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "Signal Catcher" prio=10 tid=3 WaitingInMainSignalCatcherLoop
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c71160 self=0xe4e49800
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12205 nice=0 cgrp=default sched=0/0 handle=0xee223920
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 503750 0 3 ) utm=0 stm=0 core=1 HZ=100
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xee127000-0xee129000 stackSize=1014KB
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes=
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x8c/0x98
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: do_sigtimedwait+0xec/0x1dc
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_SyS_rt_sigtimedwait+0xc4/0x124
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00048894  /system/lib/libc.so (__rt_sigtimedwait+12)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 0001e24b  /system/lib/libc.so (sigwait+34)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 00327363  /system/lib/libart.so (_ZN3art9SignalSet4WaitEv+22)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 00326f5d  /system/lib/libart.so (_ZN3art13SignalCatcher13WaitForSignalEPNS_6ThreadERNS_9SignalSetE+168)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 00325cc1  /system/lib/libart.so (_ZN3art13SignalCatcher3RunEPv+276)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 000470b3  /system/lib/libc.so (_ZL15__pthread_startPv+22)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #06 pc 00019e3d  /system/lib/libc.so (__start_thread+6)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   (no managed stack frames)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "JDWP" prio=10 tid=4 WaitingInMainDebuggerLoop
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c711f0 self=0xe7893400
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12206 nice=0 cgrp=default sched=0/0 handle=0xee124920
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 4221825 1624114 13 ) utm=0 stm=0 core=3 HZ=100
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xee028000-0xee02a000 stackSize=1014KB
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes=
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x8c/0x98
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: poll_schedule_timeout+0x54/0xbc
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: do_select+0x454/0x4c0
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_core_sys_select+0x178/0x240
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_sys_pselect6+0x1a4/0x254
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 0004876c  /system/lib/libc.so (__pselect6+20)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 0001d045  /system/lib/libc.so (select+88)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 003fba77  /system/lib/libart.so (_ZN3art4JDWP12JdwpAdbState15ProcessIncomingEv+302)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 002487a7  /system/lib/libart.so (_ZN3art4JDWP9JdwpState3RunEv+650)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 00247f4b  /system/lib/libart.so (_ZN3art4JDWPL15StartJdwpThreadEPv+22)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 000470b3  /system/lib/libc.so (_ZL15__pthread_startPv+22)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #06 pc 00019e3d  /system/lib/libc.so (__start_thread+6)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   (no managed stack frames)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "ReferenceQueueDaemon" prio=10 tid=5 Waiting
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c71280 self=0xe4e4ac00
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12207 nice=0 cgrp=default sched=0/0 handle=0xee025920
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 13942188 2871564 45 ) utm=1 stm=0 core=1 HZ=100
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xedf23000-0xedf25000 stackSize=1038KB
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes=
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x8c/0x98
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xd4/0x130
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait+0xfc/0x210
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: do_futex+0xe0/0x920
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_SyS_futex+0xe8/0x17c
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00017404  /system/lib/libc.so (syscall+28)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 000b6e49  /system/lib/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+92)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 0029f17b  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadExibNS_11ThreadStateE+514)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 002a09ab  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectExibNS_11ThreadStateE+258)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 002af1c7  /system/lib/libart.so (_ZN3artL11Object_waitEP7_JNIEnvP8_jobject+32)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 00000557  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__+74)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Object.wait!(Native method)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   - waiting on <0x0675d174> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:150)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   - locked <0x0675d174> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.run(Thread.java:761)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "FinalizerDaemon" prio=10 tid=6 Waiting
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c71310 self=0xe4e4b100
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12208 nice=0 cgrp=default sched=0/0 handle=0xedf20920
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 14659900 11089527 72 ) utm=0 stm=0 core=1 HZ=100
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xede1e000-0xede20000 stackSize=1038KB
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes=
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x8c/0x98
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xd4/0x130
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait+0xfc/0x210
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: do_futex+0xe0/0x920
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_SyS_futex+0xe8/0x17c
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00017404  /system/lib/libc.so (syscall+28)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 000b6e49  /system/lib/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+92)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 0029f17b  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadExibNS_11ThreadStateE+514)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 002a09ab  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectExibNS_11ThreadStateE+258)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 002af1f3  /system/lib/libart.so (_ZN3artL13Object_waitJIEP7_JNIEnvP8_jobjectxi+36)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 00000655  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__JI+96)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Object.wait!(Native method)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   - waiting on <0x09b3b69d> (a java.lang.Object)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Object.wait(Object.java:407)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   - locked <0x09b3b69d> (a java.lang.Object)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:204)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.run(Thread.java:761)
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "FinalizerWatchdogDaemon" prio=10 tid=7 Sleeping
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c713a0 self=0xe4e4b600
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12209 nice=0 cgrp=default sched=0/0 handle=0xede1b920
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 962653 6709530 17 ) utm=0 stm=0 core=1 HZ=100
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xedd19000-0xedd1b000 stackSize=1038KB
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes=
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x8c/0x98
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xd4/0x130
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait+0xfc/0x210
04-05 15:29:59.390 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: do_futex+0xe0/0x920
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_SyS_futex+0xe8/0x17c
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00017408  /system/lib/libc.so (syscall+32)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 000b7271  /system/lib/libart.so (_ZN3art17ConditionVariable9TimedWaitEPNS_6ThreadExi+108)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 0029f18b  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadExibNS_11ThreadStateE+530)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 002a09ab  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectExibNS_11ThreadStateE+258)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 002b3b79  /system/lib/libart.so (_ZN3artL12Thread_sleepEP7_JNIEnvP7_jclassP8_jobjectxi+56)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 0008543b  /system/framework/arm/boot.oat (Java_java_lang_Thread_sleep__Ljava_lang_Object_2JI+126)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.sleep!(Native method)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   - sleeping on <0x0d96c712> (a java.lang.Object)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.sleep(Thread.java:371)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   - locked <0x0d96c712> (a java.lang.Object)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.sleep(Thread.java:313)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:314)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:336)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:253)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.run(Thread.java:761)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "HeapTaskDaemon" prio=10 tid=8 Blocked
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c71430 self=0xe4e4bb00
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12210 nice=0 cgrp=default sched=0/0 handle=0xedd16920
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 312438219 25726722 165 ) utm=28 stm=2 core=5 HZ=100
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xedc14000-0xedc16000 stackSize=1038KB
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes=
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x8c/0x98
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xd4/0x130
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait+0xfc/0x210
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: do_futex+0xe0/0x920
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_SyS_futex+0xe8/0x17c
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00017408  /system/lib/libc.so (syscall+32)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 000b7271  /system/lib/libart.so (_ZN3art17ConditionVariable9TimedWaitEPNS_6ThreadExi+108)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 001b4da9  /system/lib/libart.so (_ZN3art2gc13TaskProcessor7GetTaskEPNS_6ThreadE+228)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 001b545d  /system/lib/libart.so (_ZN3art2gc13TaskProcessor11RunAllTasksEPNS_6ThreadE+44)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 001615cf  /system/framework/arm/boot-core-libart.oat (Java_dalvik_system_VMRuntime_runHeapTasks__+74)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at dalvik.system.VMRuntime.runHeapTasks(Native method)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   - waiting to lock an unknown object
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:433)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.run(Thread.java:761)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "Binder:12199_1" prio=10 tid=9 Native
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c715e0 self=0xeec05e00
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12212 nice=0 cgrp=default sched=0/0 handle=0xedb13920
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 21030519 9319843 73 ) utm=1 stm=0 core=1 HZ=100
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xeda17000-0xeda19000 stackSize=1014KB
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes=
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x8c/0x98
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: binder_thread_read+0xedc/0x1024
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: binder_ioctl+0x428/0x894
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_sys_ioctl+0x120/0x1238
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00048668  /system/lib/libc.so (__ioctl+8)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 0001ae3f  /system/lib/libc.so (ioctl+38)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 0003cc87  /system/lib/libbinder.so (_ZN7android14IPCThreadState14talkWithDriverEb+202)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 0003cd9d  /system/lib/libbinder.so (_ZN7android14IPCThreadState20getAndExecuteCommandEv+8)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 0003d31b  /system/lib/libbinder.so (_ZN7android14IPCThreadState14joinThreadPoolEb+46)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 0004f8c5  /system/lib/libbinder.so (???)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #06 pc 0000e345  /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+140)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #07 pc 000665f5  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+80)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 0003cd9d  /system/lib/libbinder.so (_ZN7android14IPCThreadState20getAndExecuteCommandEv+8)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 0003d31b  /system/lib/libbinder.so (_ZN7android14IPCThreadState14joinThreadPoolEb+46)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 0004f8c5  /system/lib/libbinder.so (???)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #06 pc 0000e345  /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+140)
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes=
04-05 15:29:59.391 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: do_futex+0xe0/0x920
04-05 15:29:59.392 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12233 nice=10 cgrp=bg_non_interactive sched=0/0 handle=0xd41f5920
04-05 15:29:59.392 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 612838966 42007916 246 ) utm=60 stm=0 core=2 HZ=100
04-05 15:29:59.392 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 00029101  /system/lib/libhwui.so (_ZN7android10uirenderer12renderthread12RenderThread10threadLoopEv+284)
04-05 15:29:59.392 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.392 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: do_futex+0xe0/0x920
04-05 15:29:59.393 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 002af1f3  /system/lib/libart.so (_ZN3artL13Object_waitJIEP7_JNIEnvP8_jobjectxi+36)
04-05 15:29:59.393 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   - waiting on <0x009a1f99> (a java.lang.Object)
04-05 15:29:59.393 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at sun.misc.Unsafe.park(Unsafe.java:325)
04-05 15:29:59.393 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 000665f5  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+80)
04-05 15:29:59.393 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #06 pc 000470b3  /system/lib/libc.so (_ZL15__pthread_startPv+22)
04-05 15:29:59.393 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #07 pc 00019e3d  /system/lib/libc.so (__start_thread+6)
04-05 15:29:59.393 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   (no managed stack frames)
04-05 15:29:59.393 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 10616207 5243332 255 ) utm=0 stm=0 core=2 HZ=100
04-05 15:29:59.393 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Object.wait!(Native method)
04-05 15:29:59.393 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:323)
04-05 15:29:59.394 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xd4/0x130
04-05 15:29:59.394 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.394 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #04 pc 0000e3c1  /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+264)
04-05 15:29:59.394 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 000665f5  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+80)
04-05 15:29:59.394 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.394 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00048668  /system/lib/libc.so (__ioctl+8)
04-05 15:29:59.395 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #08 pc 000470b3  /system/lib/libc.so (_ZL15__pthread_startPv+22)
04-05 15:29:59.395 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait+0xfc/0x210
04-05 15:29:59.396 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xd4/0x130
04-05 15:29:59.396 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 28125105 4358959 16 ) utm=2 stm=0 core=5 HZ=100
04-05 15:29:59.397 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 00000655  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__JI+96)
04-05 15:29:59.397 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "androidmapsapi-vts_com.github.binpower93.stationhubapp_default" prio=10 tid=33 Native
04-05 15:29:59.397 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] 
04-05 15:29:59.397 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | sysTid=12463 nice=10 cgrp=bg_non_interactive sched=0/0 handle=0xc7681920
04-05 15:29:59.398 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at android.os.MessageQueue.nativePollOnce(Native method)
04-05 15:29:59.398 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at android.os.MessageQueue.next(MessageQueue.java:323)
04-05 15:29:59.398 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: SyS_epoll_wait+0x2d0/0x358
04-05 15:29:59.398 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #06 pc 006276ed  /system/framework/arm/boot-framework.oat (Java_android_os_MessageQueue_nativePollOnce__JI+96)
04-05 15:29:59.398 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at com.google.maps.api.android.lib6.gmm6.store.d.run(:com.google.android.gms.DynamiteModulesB:20094)
04-05 15:29:59.398 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | held mutexes=
04-05 15:29:59.398 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_SyS_epoll_pwait+0xd8/0x178
04-05 15:29:59.398 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xc6f61000-0xc6f63000 stackSize=1038KB
04-05 15:29:59.399 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.399 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422] "androidmapsapi-ula-1" prio=10 tid=43 Waiting
04-05 15:29:59.399 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: cpu_switch_to+0x48/0x4c
04-05 15:29:59.399 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #00 pc 00017404  /system/lib/libc.so (syscall+28)
04-05 15:29:59.399 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #01 pc 000b6e49  /system/lib/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+92)
04-05 15:29:59.399 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #02 pc 0029f17b  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadExibNS_11ThreadStateE+514)
04-05 15:29:59.399 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 002a09ab  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectExibNS_11ThreadStateE+258)
04-05 15:29:59.399 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-05 15:29:59.400 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 296146 0 1 ) utm=0 stm=0 core=0 HZ=100
04-05 15:29:59.400 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   | stack=0xc4c08000-0xc4c0a000 stackSize=1038KB
04-05 15:29:59.400 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
04-05 15:29:59.401 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 002a09ab  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectExibNS_11ThreadStateE+258)
04-05 15:29:59.401 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xd4/0x130
04-05 15:29:59.401 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: compat_SyS_futex+0xe8/0x17c
04-05 15:29:59.401 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   - waiting on <0x08952109> (a java.lang.Object)
04-05 15:29:59.401 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x8c/0x98
04-05 15:29:59.402 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #05 pc 00000655  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__JI+96)
04-05 15:29:59.402 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   - waiting on <0x0d85ff0e> (a java.lang.Object)
04-05 15:29:59.402 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.run(Thread.java:761)
04-05 15:29:59.402 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 002a09ab  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectExibNS_11ThreadStateE+258)
04-05 15:29:59.402 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   native: #03 pc 002a09ab  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectExibNS_11ThreadStateE+258)
04-05 15:29:59.402 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Object.wait!(Native method)
04-05 15:29:59.403 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.run(Thread.java:761)
04-05 15:29:59.403 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:427] JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0x100019
04-05 15:29:59.403 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:427]     from void io.realm.internal.SharedRealm.nativeCommitTransaction(long)
04-05 15:29:59.403 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:427] "main" prio=5 tid=1 Runnable
04-05 15:29:59.403 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:427]   | group="main" sCount=0 dsCount=0 obj=0x74130000 self=0xeec05400
04-05 15:29:59.403 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:427]   | sysTid=12199 nice=-10 cgrp=default sched=0/0 handle=0xf18d2534
04-05 15:29:59.403 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:427]   native: #11 pc 000cc4e5  /system/lib/libart.so (_ZN3art8CheckJNI11CallMethodVEPKcP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDSt9__va_listNS_9Primitive4TypeENS_10InvokeTypeE+512)
04-05 15:29:59.403 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:427]   native: #20 pc 00080dcb  /data/app/com.github.binpower93.stationhubapp-2/lib/arm/librealm-jni.so (???)
04-05 15:29:59.403 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:427]   at io.realm.internal.SharedRealm.nativeCommitTransaction(Native method)
04-05 15:29:59.403 12199-12199/com.github.binpower93.stationhubapp A/art: art/runtime/runtime.cc:427]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-05 15:29:59.416 12199-12199/com.github.binpower93.stationhubapp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 12199 (3.stationhubapp)
```

#### Version of Realm and tooling
Realm version(s): 3.1.0 (worked on 3.0.1 SNAPSHOT)

Realm sync feature enabled: no

Android Studio version: 2.3

Which Android version and device: Nexus 5X 7.1.2 (Beta)

### PR DESCRIPTION
**Pull request by beeender**
The changed field string array needs to be reset after sending
notifications.

Fix #4437

### CODE REVIEW

File: realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java [hunk 1]
```diff
@@ -291,6 +290,48 @@ public void changeAllFields() {
...
+                if (changeSet.isFieldChanged(AllTypes.FIELD_STRING)) {
+                    assertFalse(stringChanged.get());
+                    stringChanged.set(true);
+                } else if (changeSet.isFieldChanged(AllTypes.FIELD_LONG)) {
+                    assertFalse(longChanged.get());
+                    longChanged.set(true);
+                } else if (changeSet.isFieldChanged(AllTypes.FIELD_FLOAT)) {
+                    assertFalse(floatChanged.get());
+                    floatChanged.set(true);
+                    looperThread.testComplete();
```
Comment (zaki50) [inline realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java]: Shouldn't we check `longChanged` and `stringChanged` is `true`?

File: realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java [hunk 2]
```diff
@@ -291,6 +290,48 @@ public void changeAllFields() {
 
     @Test
     @RunTestInLooperThread(before = PopulateOneAllTypes.class)
+    public void  changeDifferentFieldOneAfterAnother() {
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java]: Perhaps add a comment about why this is relevant or link to bug report. Also too much whitespace

File: realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp [hunk 3]
```diff
@@ -122,8 +122,10 @@ struct ChangeCallback {
         m_wrapper->m_row_object_weak_ref.call_with_local_ref(env, [&](JNIEnv*, jobject row_obj) {
             static JavaMethod notify_change_listeners(env, row_obj, "notifyChangeListeners",
                                                       "([Ljava/lang/String;)V");
-            env->CallVoidMethod(row_obj, notify_change_listeners, m_field_names_array);
+            env->CallVoidMethod(row_obj, notify_change_listeners, m_deleted ? nullptr : m_field_names_array);
         });
+        m_field_names_array = nullptr;
```
Comment (cmelchior) [inline realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp]: Line 64: Is that condition ever true?
```
if (m_field_names_array) {
  return;
}
```

Comment (beeender) [inline realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp]: it could be set in `before()`. The code will become clearer when implementing the old/new value.

Comment (kneth) [inline realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp]: Should `m_deleted` be updated above?

File: realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java [hunk 4]
```diff
@@ -289,6 +288,53 @@ public void changeAllFields() {
...
+                assertEquals(1, changeSet.getChangedFields().length);
+                if (changeSet.isFieldChanged(AllTypes.FIELD_STRING)) {
+                    assertFalse(stringChanged.get());
+                    stringChanged.set(true);
+                } else if (changeSet.isFieldChanged(AllTypes.FIELD_LONG)) {
+                    assertFalse(longChanged.get());
+                    longChanged.set(true);
+                } else if (changeSet.isFieldChanged(AllTypes.FIELD_FLOAT)) {
+                    assertFalse(stringChanged.get());
+                    assertFalse(longChanged.get());
```
Comment (zaki50) [inline realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java]: `assertTrue()`?
