### PR TITLE
Setters for RealmObject and RealmList now throw IllegalArgumentException if the value contains an invalid object.

### LINKED ISSUE #1749: Should have a check if value is a valid managed object or not in setter of link/link list.
relatd to #1745

### PR DESCRIPTION
**Pull request by zaki50**
fixes #1749 and is related to #1745

review this please @realm/java

### CODE REVIEW

File: realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java [hunk 1]
```diff
@@ -242,6 +245,9 @@ public void setColumnRealmList(RealmList<AllTypes> value) {
             return;
         }
         for (RealmObject linkedObject : (RealmList<? extends RealmObject>) value) {
+            if (!linkedObject.isValid()) {
+                throw new IllegalArgumentException("Each element of 'value' must be an valid managed object.");
```
Comment (kneth) [inline realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: "an" -> "a"

File: realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java [hunk 2]
```diff
@@ -327,7 +330,10 @@ private void emitAccessors(JavaWriter writer) throws IOException {
                     writer.emitStatement("return");
                 writer.endControlFlow();
                 writer.beginControlFlow("for (RealmObject linkedObject : (RealmList<? extends RealmObject>) value)");
-                        writer.emitStatement("links.add(linkedObject.row.getIndex())");
+                    writer.beginControlFlow("if (!linkedObject.isValid())");
+                        writer.emitStatement("throw new IllegalArgumentException(\"Each element of 'value' must be an valid managed object.\")");
```
Comment (kneth) [inline realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java]: "an" -> "a"

File: changelog.txt [hunk 3]
```diff
@@ -4,6 +4,7 @@
  * Fixed a bug making it impossible to read Realms created using primary keys and created by iOS (#1703).
  * Fixed some memory leaks when an Exception is thrown (#1730).
  * RealmQuery.isNull() and RealmQuery.isNotNull() now throw IllegalArgumentException instead of RealmError if the fieldname is a linked field and the last element is a link (#1693).
+ * Setters in managed object for RealmObject and RealmList now throw IllegalArgumentException if the value contains an invalid(standalone, removed, closed) object (#1749).
```
Comment (kneth) [inline changelog.txt]: "invalid(" -> "invalid ("

File: realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java [hunk 4]
```diff
@@ -286,6 +286,9 @@ private void emitAccessors(JavaWriter writer) throws IOException {
                     writer.emitStatement("row.nullifyLink(%s)", fieldIndexVariableReference(field));
                     writer.emitStatement("return");
                 writer.endControlFlow();
+                writer.beginControlFlow("if (!value.isValid())");
```
Comment (cmelchior) [inline realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java]: You also need to check if the object is in the same Realm. This would also behaves really strange if you tried to add an object from another Realm.

File: realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java [hunk 5]
```diff
@@ -327,7 +330,10 @@ private void emitAccessors(JavaWriter writer) throws IOException {
                     writer.emitStatement("return");
                 writer.endControlFlow();
                 writer.beginControlFlow("for (RealmObject linkedObject : (RealmList<? extends RealmObject>) value)");
-                        writer.emitStatement("links.add(linkedObject.row.getIndex())");
+                    writer.beginControlFlow("if (!linkedObject.isValid())");
```
Comment (cmelchior) [inline realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java]: Same

**Comment by zaki50** [comment]
please review again @realm/java

**Comment by zaki50** [comment]
I need more updates. please wait reviewing. @realm/java

**Comment by zaki50** [comment]
please review again @realm/java

**Comment by kneth** [comment]
:+1:

**Comment by beeender** [comment]
```
RealmList<A> aList = B.getAList();
aList.add(ObjectAFromAnotherRealm);
```
Above code is actually legal. But when the `aList` is not a managed `RealmList`, it will throw when `setAList` is called.

I am fine with this behaviour since it is just a corner case. It just feels a little bit inconsistency. What do you think? @realm/java

**Comment by cmelchior** [comment]
Forcing people to use `copyToRealm` before adding lists is fine with me for now. I'll add a bullet point to our 1.0 review though just so we can have a chat about it across the whole API.

**Comment by beeender** [comment]
:+1:
