### PR TITLE
Fixed weak change listeners being removed correctly

### LINKED ISSUE #1875: UnsupportedOperationException in RealmBaseAdapter
I get such exception after I guess last change regarding notifications (0.86.0-SNAPSHOT):

`Caused by: java.lang.UnsupportedOperationException`
`		at java.util.concurrent.CopyOnWriteArrayList$CowIterator.remove(CopyOnWriteArrayList.java:744)`
`		at io.realm.HandlerController.addChangeListenerAsWeakReference(HandlerController.java:145)`
`		at io.realm.RealmBaseAdapter.<init>(RealmBaseAdapter.java:56)`
`		at com.borg.forza.adapters.RealmModelAdapter.<init>(RealmModelAdapter.java:0)`

Seems like CopyOnWriteArrayList iterator does not support remove operation.

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #1875 

We didn't remove listeners correctly in `addChangeListenerAsWeakReference` compared to `notifyGlobalListeners`. 

No changelog needed as this hasn't been released yet.

@realm/java

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/HandlerController.java [hunk 1]
```diff
@@ -139,17 +139,32 @@ void addChangeListener(RealmChangeListener listener) {
...
+                }
+                toRemoveList.add(weakRef);
             }
-        }
 
-        weakChangeListeners.add(new WeakReference<RealmChangeListener>(listener));
+            // Check if Listener already exists
+            if (weakListener == listener) {
+                addListener = false;
+                break;
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: Might be better just let the loop finished to clear the weak refs.

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: Yes, I was considering that as well. I will change it

**Comment by beeender** [comment]
And need the change log :+1:

**Comment by cmelchior** [comment]
> No changelog needed as this hasn't been released yet. 

;)

**Comment by beeender** [comment]
Who mentioned changelog? i didn't XD

**Comment by zaki50** [comment]
:+1:

**Comment by nhachicha** [comment]
:+1:

**Comment by cmelchior** [comment]
retest this please

**Comment by dalinaum** [comment]
:+1:
