### PR TITLE
Show error messages for UTF decoding issues

### LINKED ISSUE #7081: Failure when converting to UTF-8 (WITH SAMPLE REPO)
###  We received a crash report with the following truncated stack trace:

```
Fatal Exception: java.lang.IllegalArgumentException: Illegal Argument: Failure when converting to UTF-8; error_code = 6;  0x0050 0x0061 0x0070 0x0061 0x0020 0x0047 0x0020 0xd83c
Exception backtrace:
<backtrace not supported on this platform> in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp line 798
       at io.realm.internal.Table.nativeFindFirstString(Table.java)
       at io.realm.internal.Table.findFirstString(Table.java:583)
       at io.realm.com_coolapp_CoolObjectRealmProxy.copyOrUpdate(com_coolapp_CoolObjectRealmProxy.java:507)
       at io.realm.LibraryModuleMediator.copyOrUpdate(LibraryModuleMediator.java:105)
       at io.realm.Realm.copyOrUpdate(Realm.java:1700)
       at io.realm.Realm.copyToRealmOrUpdate(Realm.java:1296)
```

#### Steps & Code to Reproduce
We were able to reproduce this by attempting to insert the following string into realm:
`val problemString = "\uD83D"`

This is the workaround we are using at present:
`String(badText.toByteArray(Charsets.UTF_8))`

#### Version of Realm and tooling
Realm version(s): 7.0.2

#### Repo demonstrating crash
https://github.com/rm8x/realm-utf8-issue

### PR DESCRIPTION
**Pull request by clementetb**
Show a more descriptive message for UTF encoding exceptions

This PR rebases the changes from #7091 into releases.

Error descriptions are extracted from the comments in [utf8.hpp : to_utf8()](https://github.com/realm/realm-java/blob/0e1464114782f88165309bd0d73d13a8fde72ab7/realm/realm-library/src/main/cpp/utf8.hpp#L260)

closes #7081

### CODE REVIEW

File: realm/realm-library/src/androidTest/java/io/realm/UTFStrings.java [hunk 1]
```diff
@@ -0,0 +1,109 @@
+/*
```
Comment (rorbech) [inline realm/realm-library/src/androidTest/java/io/realm/UTFStrings.java:1]: Maybe append `Test` to the file name to make it stand our that it contains tests.

**Review by rorbech — APPROVED** [review]
Looks good. 

Don't know the convention, but guess it would be ok for me to rebase original PR to new branch to allow keeping the history when there is no other collaborators.

File: realm/realm-library/src/androidTest/java/io/realm/UTFStrings.java (hunk 1 above)
Comment (cmelchior) [reply realm/realm-library/src/androidTest/java/io/realm/UTFStrings.java]: Yup, I renamed the class
