### PR TITLE
Fix a memory leak in RealmBaseAdapter

### LINKED ISSUE #1109: Possibility of a memory leak due to a combination of `RealmChangeListener` and `automaticUpdate`
Reported by @zaki50 

`RealmChangeListener` is added to `Realm` when `automaticUpdate` is true. Then the listener instance was not released until the `Realm` instance is released because the `RealmChangeListener` is never deleted.

Since a listener instance is an anonymous inner class of `RealmBaseAdapter`, it holds a reference to the `RealmBaseAdapter` as an enclosing instance. `RealmBaseAdapter` usually holds a reference to the `Activity` that uses it as `Context`. So these instances will not be released until the `Realm` instance is released.

If you use `Realm` in only one Activity, there is no problem because `Realm#close()` is called when the `Activity`  is destroyed. (Strictly speaking, adapters may be accumulated if re-create a `RealmBaseAdapter` while the Activity is alive.)

On the other hand, if you use two activities, there are main activity and another activity that has `ListView`, each activity uses `Realm`, the `Realm` instance is held in cache until `onDestroy` of main activity is called. For example if you transition between the two Activities as follows, Main -> List-> back -> List -> back -> List... I think the `RealmChangeListener` may be accumulated in the `Realm`.

What do you think? @cmelchior @emanuelez

### PR DESCRIPTION
**Pull request by emanuelez**
Fixes #1109
We now use WeakReferences to store the change listeners.
This allows the Garbage Collector to clean up the adapters.

### CODE REVIEW

**Comment by emanuelez** [comment]
Changelog:
 * Fixed a memory leak when using RealmBaseAdapter

**Comment by emanuelez** [comment]
@cmelchior @kneth @bmunkholm

File: realm/src/main/java/io/realm/Realm.java [hunk 1]
```diff
@@ -1408,9 +1410,14 @@ public void removeAllChangeListeners() {
     }
 
     void sendNotifications() {
-        List<RealmChangeListener> defensiveCopy = new ArrayList<RealmChangeListener>(changeListeners);
-        for (RealmChangeListener listener : defensiveCopy) {
```
Comment (cmelchior) [inline realm/src/main/java/io/realm/Realm.java]: I guess removing the defensive copy is OK since Realm instances are thread local anyway?

**Comment by cmelchior** [comment]
:+1:

File: realm/src/main/java/io/realm/Realm.java (hunk 1 above)
Comment (emanuelez) [inline realm/src/main/java/io/realm/Realm.java]: Exactly

**Comment by kneth** [comment]
:+1:
