### PR TITLE
More checkings when modify RealmList

### LINKED ISSUE #2381: Missing checking when call `RealmList.add()`/`set` with `DynamicObject`
The below test should pass as well as other `RealmList`'s methods `add(int location, E object)`/`set(int location, E object)`

```java
    @Test
    public void getList_addWrongTypeTo() {
        DynamicRealm dynamicRealm = DynamicRealm.getInstance(realm.configuration);
        dynamicRealm.beginTransaction();

        DynamicRealmObject allTypes = dynamicRealm.createObject(AllTypes.CLASS_NAME);
        allTypes.setString(AllTypes.FIELD_STRING, "bender");

        DynamicRealmObject cat = dynamicRealm.createObject(Cat.CLASS_NAME);
        cat.setString("name", "nibbler");

        RealmList<DynamicRealmObject> list = allTypes.getList(AllTypes.FIELD_REALMLIST);
        list.add(cat);
        thrown.expect(IllegalArgumentException.class);

        dynamicRealm.commitTransaction();
    }
```

### PR DESCRIPTION
**Pull request by beeender**
Fix #2381

* New method LinkView.getTargetTable().
* Proper checking to add DynamicRealmObject to RealmList.
* Disallow modifying with RealmObject belongs to another Realm instance.

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/RealmList.java [hunk 1]
```diff
@@ -218,15 +218,30 @@ public E set(int location, E object) {
...
-        // We don't support moving DynamicRealmObjects across Realms automatically. The overhead is too big as you
-        // have to run a full schema validation for each object.
         if (object instanceof DynamicRealmObject) {
-            throw new IllegalArgumentException("Automatically copying DynamicRealmObjects from other Realms are not supported");
+            String listClassName = view.getTargetTable().getName();
+            String objectClassName = ((DynamicRealmObject) object).row.getTable().getName();
+            if (object.realm == realm && listClassName.equals(objectClassName)) {
+                // Same Realm instance and same target table
+                return object;
+            } else if (object.realm == realm) {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmList.java]: It looks a bit funny with 3 these if's at the same level, I would probably inline this in the first if like this:
```
if (object.realm == realm) {
  if (listClassName.equals(objectClassName) {
   //...
   } else {
   //...
   }
} else {

}
```

File: realm/realm-library/src/main/java/io/realm/RealmList.java [hunk 2]
```diff
@@ -218,15 +218,30 @@ public E set(int location, E object) {
...
-        if (object.row != null && object.realm.getPath().equals(realm.getPath())) {
-            return object;
-        }
-
-        // We don't support moving DynamicRealmObjects across Realms automatically. The overhead is too big as you
-        // have to run a full schema validation for each object.
         if (object instanceof DynamicRealmObject) {
-            throw new IllegalArgumentException("Automatically copying DynamicRealmObjects from other Realms are not supported");
+            String listClassName = view.getTargetTable().getName();
+            String objectClassName = ((DynamicRealmObject) object).row.getTable().getName();
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmList.java]: DynamicRealmObject has a `getType` method for this.

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmList.java]: DynamicRealmObject has a `getType` method for this.

File: realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java [hunk 3]
```diff
@@ -1019,4 +1022,213 @@ public void testRemoveAllFromRealmInvalidListShouldThrow() {
             assertEquals("This Realm instance has already been closed, making it unusable.", e.getMessage());
         }
     }
+
+    private interface ListModifier <T extends RealmObject> {
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: Please add a small description for this interface. At a glance the name is not that telling.

File: realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java [hunk 4]
```diff
@@ -1019,4 +1022,213 @@ public void testRemoveAllFromRealmInvalidListShouldThrow() {
...
+        void modify(RealmList<T> list, T element);
+    }
+
+    private void doTestModifyListFromOtherThread(final ListModifier<Dog> modifier) {
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: Also, small description for this method

File: realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java [hunk 5]
```diff
@@ -1019,4 +1022,213 @@ public void testRemoveAllFromRealmInvalidListShouldThrow() {
...
+            @Override
+            public void modify(RealmList<Dog> list, Dog element) {
+                list.add(element);
+            }
+        });
+    }
+
+    @Test
+    public void add_withLocationObjectFromOtherThread() {
+        doTestModifyListFromOtherThread(new ListModifier<Dog>() {
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: In e.g. RealmResults all these tests are combined in one method: `runMethodOnWrongThread`. It takes up a lot less space than this? Not sure what is better, but I probably lean slightly towards what RealmResultsTests are doing?

**Comment by cmelchior** [comment]
Mostly a few comments about the test cases and a few improvements to checking, otherwise it looks good.

**Comment by beeender** [comment]
@realm/java Updated

File: realm/realm-library/src/main/java/io/realm/internal/LinkView.java [hunk 6]
```diff
@@ -153,6 +153,12 @@ public void removeAllTargetRows() {
         nativeRemoveAllTargetRows(nativePointer);
     }
 
+    public Table getTargetTable() {
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/internal/LinkView.java]: Can't you use `Table::get_table_ref()`?

Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/internal/LinkView.java]: @kneth Yep, updated the commit. Please help to check.

File: realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java [hunk 7]
```diff
@@ -1019,4 +1022,167 @@ public void testRemoveAllFromRealmInvalidListShouldThrow() {
             assertEquals("This Realm instance has already been closed, making it unusable.", e.getMessage());
         }
     }
+
+    @Test
+    public void add_set_objectFromOtherThread() {
+        final CountDownLatch finishedLatch = new CountDownLatch(1);
+        final Dog dog = testRealm.where(Dog.class).findFirst();
+        final String expectedMsg = "Cannot copy an object from another Realm instance.";
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: Shouldn't this throw an IllegalState because of a wrong thread first? Then check for this later?

File: realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java [hunk 8]
```diff
@@ -1019,4 +1022,167 @@ public void testRemoveAllFromRealmInvalidListShouldThrow() {
...
+        }).start();
+        TestHelper.awaitOrFail(finishedLatch);
+    }
+
+    @Test
+    public void add_set_dynamicObjectFromOtherThread() {
+        final CountDownLatch finishedLatch = new CountDownLatch(1);
+        DynamicRealm dynamicRealm = DynamicRealm.getInstance(testRealm.getConfiguration());
+        final DynamicRealmObject dynDog = dynamicRealm.where(Dog.CLASS_NAME).findFirst();
+        final String expectedMsg = "Cannot copy an object from another Realm instance.";
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: Same

File: realm/realm-library/src/main/java/io/realm/internal/LinkView.java (hunk 6 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/LinkView.java]: Should we cache this? Right now you create a new Table object this method is called.

File: realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java (hunk 7 above)
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]:
```java
} else {
                // We don't support moving DynamicRealmObjects across Realms automatically. The overhead is too big as
                // you have to run a full schema validation for each object.
                // And copying from another Realm instance pointed to the same Realm file is not supported as well.
                throw new IllegalArgumentException("Cannot copy an object from another Realm instance.");
            }
```

change to 
```
            } else if (realm.threadId ==object.realm.threadId) {
                // We don't support moving DynamicRealmObjects across Realms automatically. The overhead is too big as
                // you have to run a full schema validation for each object.
                // And copying from another Realm instance pointed to the same Realm file is not supported as well.
                throw new IllegalArgumentException("Cannot copy an object from another Realm instance.");
            } else {
                throw new IllegalStateException("Cannot copy an object from another Realm instance in anther thread.");
            }
```

Something like above is better?

Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: I was more thinking about the standard `realm.checkIfValid()` check.

Would `object.realm.checkIfValid()` not be enough?

Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: No, for the case to check `DynamicRealm` and `Realm` in the same thread.

Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: Do, you are right. Just ignore my comment then. The original wording is fine. The newer one is technically more correct, but I am not sure the complexity is worth it.

File: realm/realm-library/src/main/java/io/realm/internal/LinkView.java (hunk 6 above)
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/internal/LinkView.java]: It is only a new java `Table` object which points to the same `Table` pointer in the core. No need to cache like other tables we created in java.

File: realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java [hunk 9]
```diff
@@ -1019,4 +1022,167 @@ public void testRemoveAllFromRealmInvalidListShouldThrow() {
...
+
+        new Thread(new Runnable() {
+            @Override
+            public void run() {
+                Realm realm = Realm.getInstance(testRealm.getConfiguration());
+                realm.beginTransaction();
+                RealmList<Dog> list = realm.createObject(Owner.class).getDogs();
+                list.add(realm.createObject(Dog.class));
+                try {
```
Comment (bmunkholm) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: Refactor the common code out of this method and the following.

Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: @bmunkholm That was what i did before -- use common code https://github.com/realm/realm-java/pull/2390#discussion_r55023084 . But we found it is not easy to read.

File: realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java [hunk 10]
```diff
@@ -1019,4 +1022,167 @@ public void testRemoveAllFromRealmInvalidListShouldThrow() {
...
+        try {
+            list.set(0, dynCat);
+            fail();
+        } catch (IllegalArgumentException expected) {
+            assertEquals(expectedMsg, expected.getMessage());
+
+        }
+
+        dynamicRealm.cancelTransaction();
+
```
Comment (stk1m1) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: White space removal? I noticed line 1185 doesn't have one.

File: realm/realm-library/src/main/java/io/realm/RealmList.java [hunk 11]
```diff
@@ -218,15 +219,32 @@ public E set(int location, E object) {
...
-        // Object is already in this realm
-        if (object.row != null && object.realm.getPath().equals(realm.getPath())) {
-            return object;
-        }
-
-        // We don't support moving DynamicRealmObjects across Realms automatically. The overhead is too big as you
-        // have to run a full schema validation for each object.
         if (object instanceof DynamicRealmObject) {
-            throw new IllegalArgumentException("Automatically copying DynamicRealmObjects from other Realms are not supported");
+            String listClassName = view.getTargetTable().getName().substring(Table.TABLE_PREFIX.length());
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmList.java]: I would prefer if this information was accessed through RealmSchema somehow. All these rules about naming should all be enforced there instead of being spread around the codebase (IMO). It probably means adding something like `getSchemaForTable` as I am not sure the functionality exists yet.

File: realm/realm-jni/src/io_realm_internal_LinkView.cpp [hunk 12]
```diff
@@ -193,11 +193,24 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_LinkView_nativeFind
...
+JNIEXPORT jlong JNICALL Java_io_realm_internal_LinkView_nativeGetTargetTable
+  (JNIEnv *, jobject, jlong nativeLinkViewPtr)
+{
+    TR_ENTER_PTR(nativeLinkViewPtr)
+
+    LinkView *lv = LV(nativeLinkViewPtr);
+    Table* pTable = &(lv->get_target_table());
+    LangBindHelper::bind_table_ptr(pTable);
+
+    return (jlong)pTable;
```
Comment (stk1m1) [inline realm/realm-jni/src/io_realm_internal_LinkView.cpp]: I'm trying be cautious, but wouldn't it be better to use `return reinterpret_cast<jlong>(pTable);` since the returned value would be re-casted to `Table*` again?

File: realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java (hunk 7 above)
Comment (stk1m1) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: > } else if (realm.threadId ==object.realm.threadId) {

:+1: for checking thread.

Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: Done

File: realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java (hunk 10 above)
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java]: Done

File: realm/realm-library/src/main/java/io/realm/internal/LinkView.java [hunk 13]
```diff
@@ -153,6 +153,20 @@ public void removeAllTargetRows() {
...
+        // Execute the disposal of abandoned realm objects each time a new realm object is created
+        context.executeDelayedDisposal();
+        long nativeTablePointer = nativeGetTargetTable(nativePointer);
+        try {
+            // Copy context reference from parent
+            return new Table(context, this.parent, nativeTablePointer);
+        }
+        catch (RuntimeException e) {
```
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/internal/LinkView.java]: please remove new line before `catch`

File: realm/realm-jni/src/io_realm_internal_LinkView.cpp (hunk 12 above)
Comment (beeender) [inline realm/realm-jni/src/io_realm_internal_LinkView.cpp]: done

**Comment by cmelchior** [comment]
:+1:

File: realm/realm-jni/src/io_realm_internal_LinkView.cpp [hunk 14]
```diff
@@ -193,11 +193,24 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_LinkView_nativeFind
...
- }
+}
+
+JNIEXPORT jlong JNICALL Java_io_realm_internal_LinkView_nativeGetTargetTable
+  (JNIEnv *, jobject, jlong nativeLinkViewPtr)
+{
+    TR_ENTER_PTR(nativeLinkViewPtr)
+
+    LinkView *lv = LV(nativeLinkViewPtr);
+    Table* pTable = &(lv->get_target_table());
```
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_LinkView.cpp]: Where to put `*`?

Comment (beeender) [inline realm/realm-jni/src/io_realm_internal_LinkView.cpp]: opps... copied lines from different places...

**Comment by kneth** [comment]
:+1:
