### PR TITLE
Fix progress listener flaky tests

### LINKED ISSUE #5245: downloadProgressListener_indefinitely worker thread doesn't terminate
As per the discussion [here](https://github.com/realm/realm-java/pull/5159#discussion_r136507434), we need to investigate why the `downloadProgressListener_indefinitely` test fails. Removing the [join](https://github.com/realm/realm-java/pull/5159/files/69aa8f2d39fce182485c34767d6249cd7d8173f3#diff-98189d61fc029709ddad095607a8590eL193) seems to fix the issue, which indicates that the `worker` thread didn't terminate, which causes the test thread to wait indefinitely until it times out

### PR DESCRIPTION
**Pull request by beeender**
close #5245

### CODE REVIEW

File: realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java [hunk 1]
```diff
@@ -148,50 +164,51 @@ public void run() {
...
         session.addDownloadProgressListener(ProgressMode.INDEFINITELY, new ProgressListener() {
             @Override
             public void onChange(Progress progress) {
-                if (progress.isTransferComplete()) {
+                Realm adminRealm = Realm.getInstance(adminConfig);
+                long objectCounts = adminRealm.where(AllTypes.class).count();
+                adminRealm.close();
+                // The downloading progress listener could be triggered at the db version where only contains the meta
+                // data. So we start checking from when the first 10 objects downloaded.
+                if (objectCounts != 0 && progress.isTransferComplete()) {
```
Comment (nhachicha) [inline realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java]: this will swallow the Initial trigger 👍🏼

**Comment by nhachicha** [comment]
btw the test still times out https://ci.realm.io/job/realm/job/realm-java/job/PR-5439/4/testReport/junit/io.realm.objectserver/ProgressListenerTests/downloadProgressListener_indefinitely/

**Comment by beeender** [comment]
Create https://github.com/realm/realm-sync/issues/1770 for the time out issue.
