### PR TITLE
Fix log level in jni

### LINKED ISSUE #4204: Fix JNI logging method level
Currently all method uses the same level `io_realm_log_LogLevel_ERROR` 
https://github.com/realm/realm-java/blob/fb677d98bd0c329115295d139d3fe44f3b5e5ac5/realm/realm-library/src/main/cpp/jni_util/log.hpp#L88-L108

### PR DESCRIPTION
**Pull request by zaki50**
fixes #4204 

@realm/java

### CODE REVIEW

File: realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java [hunk 1]
```diff
@@ -1030,6 +1030,7 @@ public void run() {
         realm.beginTransaction();
         Dog akamaru = realm.createObject(Dog.class);
         realm.commitTransaction();
+        looperThread.keepStrongReference.add(akamaru);
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java]: This is not necessary. This flaky test will be fixed by #4209

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,9 @@
 ## 2.3.2
 
+### Bug fixes
+
+* Fixed log levelis in JNI layer (#4204).
```
Comment (kneth) [inline CHANGELOG.md]: "levelis" -> "levels"

Comment (zaki50) [inline CHANGELOG.md]: done
