### PR TITLE
Ensure alignment between test app and server admin interface

### LINKED ISSUE #6904: Flaky Realm App tests on CI
Some of our integration tests for the MongoDB Realm functionality seems to be quite flaky.

This is especially true for EmailPasswordAuthTests. One example here [https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-java/detail/PR-6895/1/pipeline](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-java/detail/PR-6895/1/pipeline)

The error manifests as `ACCOUNT_NAME_IN_USE(realm::app::ServiceError:49): name already in use` which indicate that somehow our test users are not being correctly deleted after each test, but attempts to verify this in [https://github.com/realm/realm-java/pull/6848](https://github.com/realm/realm-java/pull/6848) has so far failed.

### PR DESCRIPTION
**Pull request by rorbech**
Should hopefully fix #6904

### CODE REVIEW

File: realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/admin/ServerAdmin.kt [hunk 1]
```diff
@@ -80,10 +81,18 @@ class ServerAdmin {
         result = JSONObject(executeRequest(builder))
         groupId = (result.getJSONArray("roles")[0] as JSONObject).getString("group_id")
 
-        // Get Internal App Id
+        // Get Internal App Id of the requested app
+        val appId = this.app.configuration.appId
         builder = Request.Builder().url("$baseUrl/groups/$groupId/apps").get()
-        result = JSONArray(executeRequest(builder))[0] as JSONObject
-        appId = result.getString("_id")
+        val response = JSONArray(executeRequest(builder))
```
Comment (cmelchior) [inline realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/admin/ServerAdmin.kt:87]: Interesting and good catch 🎉 . I wonder why it even worked in the first place before? And why it was only flaky?

Comment (rorbech) [reply realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/admin/ServerAdmin.kt:87]: Because with two apps the first one is sometimes the right one 😄 Maybe they are sorted by generated ids o.a.

Comment (cmelchior) [reply realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/admin/ServerAdmin.kt:87]: Doh, ofcourse 👍

Comment (rorbech) [reply realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/admin/ServerAdmin.kt:87]: The tricky parts is why it was almost only happening on CI?

Comment (cmelchior) [reply realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/admin/ServerAdmin.kt:87]: Yup, I guess it is a timing issue that just surfaces there. Also, we would need to understand what the server uses for sorting when returning those apps. Maybe it is just based on how the data is stored in MongoDB instead of a specific sorting.
