### PR TITLE
Only load RealmObservableFactory when RxJava exist

### LINKED ISSUE #1990: Info message from art: Rejecting re-init
Just as an information, when I start the app with the most current version of Realm I get the following log messages:

```
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$4>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$4>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$3>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$3>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$2>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$2>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$1>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$1>
```

We are currently not using the new `rx`feature, but just wanted to see if this is something to be concerned about.

The device was a Nexus 5 running Android 6.

### PR DESCRIPTION
**Pull request by beeender**
Close #1990.

* Check RxJava existence only once.
* Don't load RealmObservableFactory if RxJava doesn't exist.
* Correct exceptions in the java doc.

NOTE: When reflection called on the RealmObject/RealmResults, crash will
still happen because of Observable doesn't exist in the class path. In
such a case, a dummy rx.Observable is still needed as a workaround.

### CODE REVIEW

**Comment by beeender** [comment]
@realm/java

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java [hunk 1]
```diff
@@ -269,6 +270,23 @@ public String toString() {
     }
 
     /**
+     * Check if the RxJava is can be loaded.
+     *
+     * @return true if RxJava dependency exist.
+     */
+    public static synchronized boolean isRxJavaAvailable() {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: Any reason this is public?

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java [hunk 2]
```diff
@@ -269,6 +270,23 @@ public String toString() {
...
+        if (rxJavaAvailable  == null) {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: Too much whitespace before ==

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java [hunk 3]
```diff
@@ -182,7 +182,7 @@ public void removeChangeListener(RealmChangeListener listener) {
      * </pre>
      *
      * @return RxJava Observable that only calls {@code onNext}. It will never call {@code onComplete} or {@code OnError}.
-     * @throws UnsupportedOperationException if the required RxJava framework is not on the classpath.
+     * @throws NoClassDefFoundError if the required RxJava framework is not on the classpath.
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: It looks a bit odd that the other methods can throw both UnsupportedOperation and NoClassDef, while this only throw the latter?

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 4]
```diff
@@ -290,7 +291,7 @@ public final void removeChangeListeners() {
             Observable<E> observable = (Observable<E>) realm.configuration.getRxFactory().from(dynamicRealm, dynamicObject);
             return observable;
         } else {
-            throw new UnsupportedOperationException(realm.getClass() + " not supported");
+            throw new UnsupportedOperationException(realm.getClass() + " does not support RxJava.");
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: The exception in the RealmObservableFactory throws an message with a pointer to our docs. IMO we should do the same in these now as people new to Realm might not have read the docs and accidentally use this method?

**Comment by cmelchior** [comment]
Nice correction. Good idea to move the check to RealmConfiguration

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java (hunk 1 above)
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: `io/realm/RealmConfiguration.java` and `io/realm/rx/RealmObservableFactory.java` are in different package.

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java (hunk 3 above)
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: Whenever jvm needs the information of `Observable`, `NoClassDefFoundError` will be thrown. `UnsupportedOperationException` will only be thrown when user inherit the `BaseRealm` and create `Observable` from there. I am not sure why did you throw that at the first place. If you don't recall the reason, maybe we could just remove that?

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java (hunk 1 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: But the method is only used in RealmConfiguration right, so couldn't it just be private?

Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: Uh, you are right. will fix it.

**Comment by cmelchior** [comment]
:+1:

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java [hunk 5]
```diff
@@ -61,6 +61,7 @@
 
     private static final Object DEFAULT_MODULE;
     private static final RealmProxyMediator DEFAULT_MODULE_MEDIATOR;
+    private static Boolean rxJavaAvailable;
```
Comment (emanuelez) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: Why not a primitive here?

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java [hunk 6]
```diff
@@ -269,6 +277,23 @@ public String toString() {
     }
 
     /**
+     * Check if the RxJava is can be loaded.
```
Comment (emanuelez) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: -> Check if RxJava can be loaded.

File: realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java [hunk 7]
```diff
@@ -206,17 +189,11 @@ public void call() {
     }
 
     @Override
-    public Observable<RealmQuery<DynamicRealmObject>> from(final DynamicRealm realm, final RealmQuery<DynamicRealmObject> query) {
+    public Observable<RealmQuery<DynamicRealmObject>> from(final DynamicRealm realm,
+                                                           final RealmQuery<DynamicRealmObject> query) {
```
Comment (emanuelez) [inline realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java]: What's with the indenting?

**Comment by kneth** [comment]
:+1:

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java (hunk 5 above)
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: `rxJavaAvailable` can be `null`/`false`/`true` . `null` means it is not checked yet.

File: realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java (hunk 7 above)
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java]: It is longer than 120 chars
