### PR TITLE
Acquire a global ref of jstring for field changes

### LINKED ISSUE #4378: Reach the Local Ref Table size limit when 512+ fields changes for the same object.
Currently the `String` array of changed field names are created from JNI which may reach the local ref table size limits. 

Idea to fix it is creating `JavaString` class and acquire a global ref then release the local ref.

Test to reproduce it:

```java
    @Test
    @RunTestInLooperThread
    public void moreFieldsChangedThanLocalRefTableSize() {
        final String CLASS_NAME = "ManyFields";
        final int FIELD_COUNT = 1024;
        RealmConfiguration config = looperThread.createConfiguration("many_fields");
        DynamicRealm realm = DynamicRealm.getInstance(config);

        realm.beginTransaction();
        RealmSchema schema = realm.getSchema();
        RealmObjectSchema objectSchema = schema.create(CLASS_NAME);
        for (int i = 0; i < FIELD_COUNT; i++) {
            objectSchema.addField("field" + i, int.class);
        }
        DynamicRealmObject obj = realm.createObject(CLASS_NAME);
        realm.commitTransaction();

        obj.addChangeListener(new RealmObjectChangeListener<DynamicRealmObject>() {
            @Override
            public void onChange(DynamicRealmObject object, ObjectChangeSet changeSet) {
                assertEquals(FIELD_COUNT, changeSet.getChangedFields().length);
                looperThread.testComplete();
            }
        });

        realm.beginTransaction();
        for (int i = 0; i < FIELD_COUNT; i++) {
            obj.setInt("field" + i, 42);
        }
        realm.commitTransaction();
    }
```

### PR DESCRIPTION
**Pull request by beeender**
When there are more than 512 fields change, the JNI local ref table size
limitation may be reached. Fix #4378

### CODE REVIEW

File: realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp [hunk 1]
```diff
@@ -70,19 +70,20 @@ struct ChangeCallback {
...
+        std::vector<JavaGlobalRef> field_names;
         auto table = m_wrapper->m_object.row().get_table();
         for (size_t i = 0; i < change_set.columns.size(); ++i) {
             if (change_set.columns[i].empty()) {
                 continue;
             }
             // FIXME: After full integration of the OS schema, parse the column name from
             // wrapper->m_object.get_object_schema() will be faster.
-            field_names.push_back(to_jstring(env, table->get_column_name(i)));
+            field_names.push_back(JavaGlobalRef(env, to_jstring(env, table->get_column_name(i)), true));
```
Comment (zaki50) [inline realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp]: Who will delete created global references?
I think we need to call `DeleteGlobalRef` against elements in `field_names`.

Comment (beeender) [inline realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp]: When `field_names` gets destructed (when it gets out of scope of this function), all the element will be destructed. The `DeleteGlobalRef` is called in the `JavaGlobalRef`'s destructor.

File: realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp [hunk 2]
```diff
@@ -70,19 +70,20 @@ struct ChangeCallback {
             return;
         }
 
-        std::vector<jstring> field_names;
+        // The local ref of jstring needs to be released to void reach the local ref table size limitation.
```
Comment (dalinaum) [inline realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp]: to avoid?

File: realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp (hunk 1 above)
Comment (zaki50) [inline realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp]: I couldn't find `DeleteGlobalRef` in the destructor of `JavaGlobalRef`.

Comment (beeender) [inline realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp]: @zaki50 here https://github.com/realm/realm-java/blob/mc/bug/4378/realm/realm-library/src/main/cpp/jni_util/java_global_ref.cpp#L27

Comment (zaki50) [inline realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp]: Ah, I was reading wrong file.

Yes, `DeleteGlobalRef` is called!
