### PR TITLE
Try to create getFilesDir if it doesn't exist on startup.

### LINKED ISSUE #4493: Cannot get Realm instance: io.realm.exceptions.RealmFileException: Unable to open a realm at path
#### Goal

Call `Realm realm = Realm.getInstance(mRealmConfig);` where

`
mRealmConfig = RealmConfiguration.Builder()
                .schemaVersion(2)
                .deleteRealmIfMigrationNeeded()
                .build();
`

#### Expected Results

Get a Realm without exception.

#### Actual Results

The following exception is thrown:
`io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.dropbox.paper/files/default.realm.management': make_dir() failed: No such file or directory. (make_dir() failed: No such file or directory) (/data/data/com.dropbox.paper/files/default.realm.management) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217 Kind: ACCESS_ERROR.`

More here:
[realm-exception.txt](https://github.com/realm/realm-java/files/920336/realm-exception.txt)

#### Steps & Code to Reproduce

This happens on first launch of the app.

#### Version of Realm and tooling
Realm version(s): 2.2.1

Tried upgrading to 3.1.2 but still seeing the same issue.

Realm sync feature enabled: unsure. Would this affect this? How can I turn this on/off?

Android Studio version: 2.3

Which Android version and device:

- Nexus 5 on 6.0.1
- Google Pixel 7.1.1

### PR DESCRIPTION
**Pull request by cmelchior**
Closes #4493 

We cannot "fix" it, but this way we try as hard as possible to recover from the situation, and if that fails we throw a better exception, explaining the situation.

/cc @rajuashok

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 1]
```diff
@@ -195,6 +198,58 @@ public static synchronized void init(Context context) {
...
+                currentTotalWaitMs += waitMs;
+                if (currentTotalWaitMs > maxTotalWaitMs) {
+                    break;
+                }
+            }
+        }
+
+        // One final check before giving up
+        if (context.getFilesDir() == null || !context.getFilesDir().exists()) {
+            throw new IllegalStateException("Context.getFilesDir() could not be found. See https://issuetracker.google.com/issues/36918154");
```
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: do we need to force to crash the app?

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 2]
```diff
@@ -195,6 +198,58 @@ public static synchronized void init(Context context) {
...
+     * <p>
+     * This method attempts to fix that situation. If this doesn't work an {@link IllegalStateException} will be
+     * thrown.
+     * <p>
+     * See these links for further details:
+     * https://issuetracker.google.com/issues/36918154
+     * https://github.com/realm/realm-java/issues/4493#issuecomment-295349044
+     */
+    private static void checkUserDirectoryAvailable(Context context) {
+        File userDir = context.getFilesDir();
```
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Why `userDir`?

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: What else would you call it?

File: realm/realm-library/src/main/java/io/realm/Realm.java (hunk 1 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Well, now users can catch the IllegalStateException if they think they can recover better than we do. If we don't throw this exception here, it becomes a lot more random how the error surfaces (NullPointer / Core Exception / Somewhere else).

File: realm/realm-library/src/main/java/io/realm/Realm.java (hunk 2 above)
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: How about `filesDir` or `defaultDir`?

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: `filesDir` is fine with me

File: realm/realm-library/src/main/java/io/realm/Realm.java (hunk 1 above)
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: If we expect that a user handles the exception in this senario, we should throw specific exception. IllegalState is too generic.

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: I don't mind throwing some more specific exception, but what should it be? `IllegalState` feels pretty accurate here to me? It should definitely not be a checked exception though since that would A) break the API and B) In most users cannot do anything about it anyway

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: It shouldn't be an `Error` either since, you _might_ be able to recover from it.

Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Hmm, `IllegalStateException` is fine then. I think most developers don't care this scenario.

Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Change the exception to something more specific to get more information when that happens. Something like:
```java
throw new IllegalStateException("Context.getFilesDir() returns " + Context.getFilesDir() + " which is not an existing dir. See https://issuetracker.google.com/issues/36918154");
```
