### PR TITLE
Fix class name in exception message

### LINKED ISSUE #5096: Class name in error message from query condition methods is wrong
Following test case will fail with `org.junit.ComparisonFailure: expected:<...eld 'age' in table '[Cat]' is of invalid type...> but was:<...eld 'age' in table '[Owner]' is of invalid type...>`

```
@Test
public void isEmpty_acrossLink_wrongTypeThrows() {
    for (RealmFieldType type : RealmFieldType.values()) {
        if (SUPPORTED_IS_EMPTY_TYPES.contains(type)) {
            continue;
        }

        RealmQuery<Owner> query = realm.where(Owner.class);
        try {
            query.isEmpty(Owner.FIELD_CAT + "." + Cat.FIELD_AGE);
            fail();
        } catch (IllegalArgumentException expected) {
            assertEquals(String.format(Locale.US,
                    "Invalid query: field '%s' in table '%s' is of invalid type '%s'.",
                    Cat.FIELD_AGE, Cat.CLASS_NAME, RealmFieldType.INTEGER.name()),
                    expected.getMessage());
        }
    }
}
```

The point is that the test case uses link query.

### PR DESCRIPTION
**Pull request by zaki50**
This PR fixes #5096

The important change is in `CachedFieldDescriptor#compileFieldDescription()`.
At the end of the method, they passed `className` as an first argument of `setCompilationResults()`. However, that argument should be the name of the container class of final field and actually the `className` is not the one. 

This PR also improve performance of `CachedFieldDescriptor#compileFieldDescription()`.
In the method, map lookup happened three times with the same key for each field. This PR replaced it with just one lookup for each field.

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/internal/ColumnInfo.java [hunk 1]
```diff
@@ -60,23 +60,24 @@
 public abstract class ColumnInfo {
 
     // Immutable column information
-    private static final class ColumnDetails {
+    public static final class ColumnDetails {
         public final long columnIndex;
         public final RealmFieldType columnType;
-        public final String linkTable;
+        public final String peerClassName;
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/ColumnInfo.java]: Not sure I understand this name. Wouldn't `linkedClassName` be better?

File: realm/realm-library/src/main/java/io/realm/internal/ColumnInfo.java [hunk 2]
```diff
@@ -33,9 +33,9 @@
  * <p>
  * While the use of the fields in {@code ColumnDetails} is consistent, there are three subtly different cases:
  * <ul>
- * <li>If the column type is a simple type, the link table field is empty (0L / NULLPTR)</li>
- * <li>If the column type is OBJECT or LINK, the link table field is the class name of the OBJECT/LINK type</li>
- * <li>If the column type is LINKING_OBJECT, the link table field is the class name of the backlink source table
+ * <li>If the column type is a simple type, the {@code peerClassName} field is {@code null}</li>
```
Comment (bmeike) [inline realm/realm-library/src/main/java/io/realm/internal/ColumnInfo.java]: This is not true.  It needs to be 0L / NULLPTR.  This value is use only by native code and it must appear to the native code, to be NULLPTR.

Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/internal/ColumnInfo.java]: I don't think we should describe Javadoc comment in C++ terms.
And this class should not care about whether the value is used only by native code or not.

Since the type of `peerClassName` is `String`, shouldn't we use the term `null` instead of `0L/NULLPTR`?

File: realm/realm-library/src/main/java/io/realm/internal/ColumnInfo.java (hunk 1 above)
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/internal/ColumnInfo.java]: fixed

**Comment by zaki50** [comment]
@bmeike What do you think? https://github.com/realm/realm-java/pull/5098#discussion_r132810980
If you are fine with my comment, I'll merge this.

**Comment by bmeike** [comment]
Approved quite a while ago....
