### PR TITLE
Asset file provided in configuration should not be deleted in migrations

### LINKED ISSUE #2933: Realm not copying database from assets
#### Goal

> What do you want to achieve?
Copy a pre-filled database from assets by using .assetFile(context, "default.realm")

#### Expected Results

> Database gets copied and contains all the data

#### Actual Results

>  Copied database is only 4kb in size, while the original database in the assets folder is 123kb in size.
Using realm.isEmpty() returns true, which it should not. The Realm Browser for OS X correctly shows all the data in the database. Using realm.where() always returns an empty result.

#### Steps & Code to Reproduce

> RealmConfiguration config = new RealmConfiguration.Builder(context)
    .name("default.realm")
    .schemaVersion(1)
    .assetFile(context, "default.realm")
    .deleteRealmIfMigrationNeeded()
    .build();

> Realm realm = Realm.getInstance(config);
> realm.isEmpty() // => true

Using this code, realm.isEmpty() always prints true

#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 2.2 Preview 2

Which Android version and device: CM 13 Android 6.0.1 Galaxy S5 klte

### PR DESCRIPTION
**Pull request by stk1m1**
RealmConfiguration.Builder.assetFile() and deleteRealmIfMigrationNeeded() should not be called at the same time to prevent the provided asset file from deletion in migrations.

Closes  #2933.

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java [hunk 1]
```diff
@@ -473,9 +473,18 @@ public Builder migration(RealmMigration migration) {
          * {@link io.realm.exceptions.RealmMigrationNeededException} the on-disc Realm will be cleared and recreated
          * with the new Realm schema.
          *
+         * <p>This cannot be configured to use an asset file at the same time by calling
+         * {@link #assetFile(Context, String)} as the provided asset file will be cleared in migrations.
+         *
          * <b>WARNING!</b> This will result in loss of data.
+         *
+         * @throws IllegalStateException if configured to use an asset file by calling assetFile() previously.
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: assetFile() -> {@link #assetFile(Context, String)}

**Comment by beeender** [comment]
:+1:

File: CHANGELOG.md [hunk 2]
```diff
@@ -6,6 +6,7 @@
 * Fixed a race condition which would cause some `RealmResults` to not be properly updated inside a `RealmChangeListener`. This could result in crashes when accessing items from those results (#2926/#2951).
 * Fixed a bug that could cause Realm to lose track of primary key when using `RealmObjectSchema.removeField()` and `RealmObjectSchema.renameField()` (#2829).lts (#2926).
 * Updated ProGuard configuration in order not to depend on Android's default configuration (#2972).
+* Fixed a bug that allows both `RealmConfiguration.Builder.assetFile()`/`deleteRealmIfMigrationNeeded()` to be called at the same time which leads to delete the provided asset file in migrations (#2933).
```
Comment (cmelchior) [inline CHANGELOG.md]: Fixed a bug that allowed both `RealmConfiguration.Builder.assetFile()`/`deleteRealmIfMigrationNeeded()` to be configured at the same time, which could lead to the asset file accidentally being deleted.

File: realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java [hunk 3]
```diff
@@ -342,6 +342,26 @@ public void deleteRealmIfMigrationNeeded() {
     }
 
     @Test
+    public void deleteRealmIfMigrationNeeded_failsWhenAssetFileProvided() {
+        Context context = InstrumentationRegistry.getInstrumentation().getContext();
+
+        // Ensure that there is no data
+        Realm.deleteRealm(new RealmConfiguration.Builder(context).build());
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java]: This isn't needed when just testing the builder.

File: realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java [hunk 4]
```diff
@@ -856,6 +876,26 @@ public void assetFileValidFile() throws IOException {
         assertFalse(realmFile.exists());
     }
 
+    @Test
+    public void assetFile_failsWhenDeleteRealmIfMigrationNeededCalled() {
+        Context context = InstrumentationRegistry.getInstrumentation().getContext();
+
+        // Ensure that there is no data
+        Realm.deleteRealm(new RealmConfiguration.Builder(context).build());
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java]: Not needed

File: realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java [hunk 5]
```diff
@@ -856,6 +876,26 @@ public void assetFileValidFile() throws IOException {
...
+
+        // have a builder instance to isolate codepath
+        RealmConfiguration.Builder builder = new RealmConfiguration.Builder(context);
+        try {
+            builder
+                    .deleteRealmIfMigrationNeeded()
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java]: Nice testing both ways 👍

**Comment by stk1m1** [comment]
@realm/java reviews are addressed.

**Comment by stk1m1** [comment]
retest this please

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java [hunk 6]
```diff
@@ -473,9 +473,18 @@ public Builder migration(RealmMigration migration) {
          * {@link io.realm.exceptions.RealmMigrationNeededException} the on-disc Realm will be cleared and recreated
          * with the new Realm schema.
          *
+         * <p>This cannot be configured to have an asset file at the same time by calling
+         * {@link #assetFile(Context, String)} as the provided asset file will be deleted in migrations.
+         *
          * <b>WARNING!</b> This will result in loss of data.
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: `<p>` missing

**Comment by kneth** [comment]
:+1:
