### PR TITLE
Fix retrieval of null valued primitive property from dynamic realm

### LINKED ISSUE #7025: Crash when retrieving null value for primitive property through dynamic realm
#### Goal
Getting a value from a dynamic realm.

#### Actual Results
Emulator logs:
```
2020-08-12 15:33:01.033 11756-12106/com.getdreams A/libc: /Volumes/Android/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::runtime_error: Cannot return null value" failed
2020-08-12 15:33:01.033 11756-12106/com.getdreams A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12106 (mqt_native_modu), pid 11756 (com.getdreams)
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG: Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG: Revision: '0'
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG: ABI: 'x86'
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG: Timestamp: 2020-08-12 15:33:01+0200
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG: pid: 11756, tid: 12106, name: mqt_native_modu  >>> com.getdreams <<<
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG: uid: 10134
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG: Abort message: '/Volumes/Android/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::runtime_error: Cannot return null value" failed'
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG:     eax 00000000  ebx 00002dec  ecx 00002f4a  edx 00000006
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG:     edi ec20733e  esi b641f910
2020-08-12 15:33:01.579 12593-12593/? A/DEBUG:     ebp ed93bad0  esp b641f8b8  eip ed93bad9
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG: backtrace:
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #00 pc 00000ad9  [vdso] (__kernel_vsyscall+9)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #01 pc 00092328  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #02 pc 000ad651  /apex/com.android.runtime/lib/bionic/libc.so (abort+193) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #03 pc 000adb88  /apex/com.android.runtime/lib/bionic/libc.so (__assert2+56) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #04 pc 00404724  /data/app/com.getdreams-fsdKzMdnKsOX3B5UEsKCqg==/lib/x86/librealm-jni.so (BuildId: cf4835a0884696daa85079c4ae786f0bd6d8a360)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #05 pc 0040488e  /data/app/com.getdreams-fsdKzMdnKsOX3B5UEsKCqg==/lib/x86/librealm-jni.so (BuildId: cf4835a0884696daa85079c4ae786f0bd6d8a360)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #06 pc 00401509  /data/app/com.getdreams-fsdKzMdnKsOX3B5UEsKCqg==/lib/x86/librealm-jni.so (BuildId: cf4835a0884696daa85079c4ae786f0bd6d8a360)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #07 pc 0040090e  /data/app/com.getdreams-fsdKzMdnKsOX3B5UEsKCqg==/lib/x86/librealm-jni.so (BuildId: cf4835a0884696daa85079c4ae786f0bd6d8a360)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #08 pc 00400863  /data/app/com.getdreams-fsdKzMdnKsOX3B5UEsKCqg==/lib/x86/librealm-jni.so (__cxa_throw+115) (BuildId: cf4835a0884696daa85079c4ae786f0bd6d8a360)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #09 pc 00282065  /data/app/com.getdreams-fsdKzMdnKsOX3B5UEsKCqg==/lib/x86/librealm-jni.so (BuildId: cf4835a0884696daa85079c4ae786f0bd6d8a360)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #10 pc 000ff37d  /data/app/com.getdreams-fsdKzMdnKsOX3B5UEsKCqg==/lib/x86/librealm-jni.so (Java_io_realm_internal_UncheckedRow_nativeGetBoolean+78) (BuildId: cf4835a0884696daa85079c4ae786f0bd6d8a360)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #11 pc 000a30df  /data/app/com.getdreams-fsdKzMdnKsOX3B5UEsKCqg==/lib/x86/librealm-jni.so (Java_io_realm_internal_CheckedRow_nativeGetBoolean+132) (BuildId: cf4835a0884696daa85079c4ae786f0bd6d8a360)
2020-08-12 15:33:01.858 12593-12593/? A/DEBUG:       #12 pc 00144f67  /apex/com.android.runtime/lib/libart.so (art_quick_generic_jni_trampoline+71) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 15:33:01.859 12593-12593/? A/DEBUG:       #13 pc 02042265  /memfd:/jit-cache (deleted) (io.realm.internal.UncheckedRow.getBoolean+69)
2020-08-12 15:33:01.859 12593-12593/? A/DEBUG:       #14 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 15:33:01.859 12593-12593/? A/DEBUG:       #15 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 15:33:01.859 12593-12593/? A/DEBUG:       #16 pc 00332502  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+386) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 15:33:01.859 12593-12593/? A/DEBUG:       #17 pc 0032c19c  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+988) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 15:33:01.859 12593-12593/? A/DEBUG:       #18 pc 006834ea  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1258) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 15:33:01.859 12593-12593/? A/DEBUG:       #19 pc 00138a21  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 15:33:01.859 12593-12593/? A/DEBUG:       #20 pc 00267b82  [anon:dalvik-classes4.dex extracted in memory from /data/app/com.getdreams-fsdKzMdnKsOX3B5UEsKCqg==/base.apk!classes4.dex] (io.realm.DynamicRealmObject.getBoolean+50)
2020-08-12 15:33:01.859 12593-12593/? A/DEBUG:       #21 pc 00681adc  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1612) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
2020-08-12 15:33:01.859 12593-12593/? A/DEBUG:       #22 pc 00138821  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
```

Device logs:
```
    --------- beginning of crash
2020-08-12 16:32:39.035 2873-2960/? A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 2960 (mqt_native_modu), pid 2873 (dreams.firebase)
2020-08-12 16:32:39.132 6696-6696/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-08-12 16:32:39.132 6696-6696/? A/DEBUG: Build fingerprint: 'google/blueline/blueline:11/RPB3.200720.005/6705141:user/release-keys'
2020-08-12 16:32:39.132 6696-6696/? A/DEBUG: Revision: 'MP1.0'
2020-08-12 16:32:39.132 6696-6696/? A/DEBUG: ABI: 'arm64'
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG: Timestamp: 2020-08-12 16:32:39+0200
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG: pid: 2873, tid: 2960, name: mqt_native_modu  >>> com.getdreams.firebase <<<
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG: uid: 1010357
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG: Abort message: 'terminating with uncaught exception of type std::runtime_error: Cannot return null value'
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG:     x0  0000000000000000  x1  0000000000000b90  x2  0000000000000006  x3  0000006fef2246e0
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG:     x4  fefefefefefefeff  x5  fefefefefefefeff  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG:     x8  00000000000000f0  x9  dd6c3b40cb70bf5e  x10 0000000000000000  x11 ffffffc0fffffbdf
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG:     x12 0000000000000001  x13 0000000000000018  x14 000008d552102058  x15 0001a774477c5cec
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG:     x16 000000730d224c80  x17 000000730d2062b0  x18 00000000ca62c1d6  x19 0000000000000b39
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG:     x20 0000000000000b90  x21 00000000ffffffff  x22 ffffff80ffffffc8  x23 0000006fef224930
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG:     x24 0000006fef224810  x25 0000006fef224850  x26 0000000000000264  x27 0000000000000003
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG:     x28 0000000000000002  x29 0000006fef224760
2020-08-12 16:32:39.136 6696-6696/? A/DEBUG:     lr  000000730d1b9e20  sp  0000006fef2246c0  pc  000000730d1b9e4c  pst 0000000000000000
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG: backtrace:
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #00 pc 000000000004de4c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: e0da623f4ab0530a50a9af9e181b341d)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #01 pc 00000000003c6938  /data/app/~~rTtSk5qMfjVK7rgVggeL9Q==/com.getdreams.firebase-LtWjb7HaIEpdEnI4NIYH_Q==/lib/arm64/librealm-jni.so (BuildId: e40ca2fe74c1a4778f371d2fb07ae692cc14e133)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #02 pc 00000000003c6a90  /data/app/~~rTtSk5qMfjVK7rgVggeL9Q==/com.getdreams.firebase-LtWjb7HaIEpdEnI4NIYH_Q==/lib/arm64/librealm-jni.so (BuildId: e40ca2fe74c1a4778f371d2fb07ae692cc14e133)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #03 pc 00000000003c3bd4  /data/app/~~rTtSk5qMfjVK7rgVggeL9Q==/com.getdreams.firebase-LtWjb7HaIEpdEnI4NIYH_Q==/lib/arm64/librealm-jni.so (BuildId: e40ca2fe74c1a4778f371d2fb07ae692cc14e133)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #04 pc 00000000003c3200  /data/app/~~rTtSk5qMfjVK7rgVggeL9Q==/com.getdreams.firebase-LtWjb7HaIEpdEnI4NIYH_Q==/lib/arm64/librealm-jni.so (BuildId: e40ca2fe74c1a4778f371d2fb07ae692cc14e133)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #05 pc 00000000003c315c  /data/app/~~rTtSk5qMfjVK7rgVggeL9Q==/com.getdreams.firebase-LtWjb7HaIEpdEnI4NIYH_Q==/lib/arm64/librealm-jni.so (__cxa_throw+112) (BuildId: e40ca2fe74c1a4778f371d2fb07ae692cc14e133)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #06 pc 000000000027c908  /data/app/~~rTtSk5qMfjVK7rgVggeL9Q==/com.getdreams.firebase-LtWjb7HaIEpdEnI4NIYH_Q==/lib/arm64/librealm-jni.so (BuildId: e40ca2fe74c1a4778f371d2fb07ae692cc14e133)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #07 pc 000000000014dadc  /data/app/~~rTtSk5qMfjVK7rgVggeL9Q==/com.getdreams.firebase-LtWjb7HaIEpdEnI4NIYH_Q==/lib/arm64/librealm-jni.so (Java_io_realm_internal_UncheckedRow_nativeGetBoolean+24) (BuildId: e40ca2fe74c1a4778f371d2fb07ae692cc14e133)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #08 pc 000000000020784c  /data/app/~~rTtSk5qMfjVK7rgVggeL9Q==/com.getdreams.firebase-LtWjb7HaIEpdEnI4NIYH_Q==/oat/arm64/base.odex (art_jni_trampoline+140)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #09 pc 0000000000947994  /data/app/~~rTtSk5qMfjVK7rgVggeL9Q==/com.getdreams.firebase-LtWjb7HaIEpdEnI4NIYH_Q==/oat/arm64/base.odex (io.realm.internal.UncheckedRow.getBoolean+52)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #10 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 0252adff22f4c0297f97cb35735c7649)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #11 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 0252adff22f4c0297f97cb35735c7649)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #12 pc 000000000031830c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: 0252adff22f4c0297f97cb35735c7649)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #13 pc 000000000030e638  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: 0252adff22f4c0297f97cb35735c7649)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #14 pc 000000000067cae8  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1032) (BuildId: 0252adff22f4c0297f97cb35735c7649)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #15 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 0252adff22f4c0297f97cb35735c7649)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #16 pc 000000000103c45a  /data/app/~~rTtSk5qMfjVK7rgVggeL9Q==/com.getdreams.firebase-LtWjb7HaIEpdEnI4NIYH_Q==/oat/arm64/base.vdex (io.realm.DynamicRealmObject.a+50)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #17 pc 0000000000681dfc  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtualQuick+1344) (BuildId: 0252adff22f4c0297f97cb35735c7649)
2020-08-12 16:32:39.471 6696-6696/? A/DEBUG:       #18 pc 0000000000131594  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual_quick+20) (BuildId: 0252adff22f4c0297f97cb35735c7649)
```

#### Steps & Code to Reproduce
I'm not 100% sure this is the reason, but I have a model like
```kotlin
@RealmClass
open class User : RealmObject() {
    @PrimaryKey
    @Required
    open var id: String = ""
    open var failingValue: Boolean? = false
}
```
The crash seems to happen when `User.failingValue` is `null`, but I'm not sure as it crashes when trying to read the value.
But the following migration fixed the issue:
```java
RealmObjectSchema user = schema.get("User");
if (!user.isRequired("failingValue")) {
    user.transform(obj -> {
        if (obj.isNull("failingValue")) {
            obj.setBoolean("failingValue", false);
        }
    });
    user.setRequired("failingValue", true);
}
```

#### Version of Realm and tooling

Realm version(s): 7.0.1

Realm Sync feature enabled: No

Android Studio version: 4.0.1

Android Build Tools version: 28.0.3

Gradle version: 5.6.4

Which Android version and device(s):

Android 10, Emulator Version 30.0.25-6733922, Google Play Intel Atom (x86)
Android 11, Pixel 3

### PR DESCRIPTION
**Pull request by rorbech**
Closes #7025

### CODE REVIEW

File: realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java [hunk 1]
```diff
@@ -1727,4 +1727,23 @@ public void run() {
...
+        realm.executeTransaction(realm -> {
+            AllJavaTypes object = realm.createObject(AllJavaTypes.class, 1000L);
+            object.setFieldBoolean(null);
+
+            assertNull(object.isFieldBoolean());
+        });
+        realm.close();
+
+        DynamicRealm dynamicRealm = DynamicRealm.getInstance(realm.configuration);
+        dynamicRealm.refresh();
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java:1742]: You don't need to call refresh. It should be up to date when opened.

File: realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java [hunk 2]
```diff
@@ -97,6 +97,9 @@ public DynamicRealmObject(RealmModel obj) {
         proxyState.getRealm$realm().checkIfValid();
 
         long columnKey = proxyState.getRow$realm().getColumnKey(fieldName);
+        if (proxyState.getRow$realm().isNull(columnKey)) {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java:100]: This seems to impact more than just `null` values, so we should have unit tests for all the data types.

File: realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java [hunk 3]
```diff
@@ -1727,4 +1727,23 @@ public void run() {
         thread.start();
         TestHelper.awaitOrFail(threadFinished);
     }
+
+    @Test
+    public void getNullableBoolean() {
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java:1732]: The fix seems to indicate the bug impacted all primitive types. We should have tests for all of them instead of just boolean.

**Review by cmelchior — CHANGES_REQUESTED** [review]
Nice find 👍 
A few comments:
1)The fix looks like it needs more tests
2) We should also update the changelog with an entry under Fixes
3) The bug was on 7.0.1, which means the fix should be merged in the `releases` branch so we can release it as 7.0.3. The v10 branch is only for the v10 beta API's.

File: realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java (hunk 1 above)
Comment (rorbech) [reply realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java:1644]: It does not work without it. Maybe symptom of another issue. The below sequence runs without asserting
```
DynamicRealm dynamicRealm = DynamicRealm.getInstance(realm.configuration);
assertEquals(1, dynamicRealm.where("AllJavaTypes").count());
dynamicRealm.refresh();
assertEquals(2, dynamicRealm.where("AllJavaTypes").count());
```

Comment (cmelchior) [reply realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java:1644]: Hmm, I don't like that. The underlying read transactions should not be shared between `Realm` and `DynamicRealm`. It indicates a bigger problem we need to look into. Probably some caching going wrong somewhere 😕

Comment (rorbech) [reply realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java:1644]: Yes. A dynamic realm with the same configuration was already setup. Sorry.

File: realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java (hunk 2 above)
Comment (rorbech) [reply realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java:97]: Implemented tests for `null` values for all types, but I would assume all-non values to be sufficiently test by existing tests. Or what are you missing specifically?

**Review by edualonso — APPROVED** [review]
Looks good 👍

File: CHANGELOG.md [hunk 4]
```diff
@@ -7,6 +7,7 @@
 * [ObjectServer] Calling `SyncManager.refreshConnections()` did not correctly refresh connections in all cases, which could delay reconnects up to 5 minutes. (Issue [#7003](https://github.com/realm/realm-java/issues/7003))
 * Upgrading the file format result did in some cases not work correctly. This could result in a number of crashes, e.g. `FORMAT_UPGRADE_REQUIRED`. (Issue [#6889](https://github.com/realm/realm-java/issues/6889), since 7.0.0)  
 * Bug in memory mapping management. This bug could result in multiple different asserts as well as segfaults. In many cases stack backtraces would include members of the EncyptedFileMapping near the top - even if encryption was not used at all. In other cases asserts or crashes would be in methods reading an array header or array element. In all cases the application would terminate immediately. (Issue [#3838](https://github.com/realm/realm-core/pull/3838), since 7.0.0)
+* Crash when retrieving null valued primitive fields from dynamic realm. (Issue [#7025](https://github.com/realm/realm-java/issues/7025))
```
Comment (cmelchior) [inline CHANGELOG.md:10]:
```suggestion
* Crash when retrieving `null` valued primitive fields from dynamic realm. (Issue [#7025](https://github.com/realm/realm-java/issues/7025))
```

File: realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java [hunk 5]
```diff
@@ -1629,4 +1631,95 @@ public void run() {
...
+            assertNull(primitiveNullables.getFieldDouble());
+            assertNull(primitiveNullables.getFieldString());
+            assertNull(primitiveNullables.getFieldBinary());
+            assertNull(primitiveNullables.getFieldDate());
+
+            realm.delete(AllJavaTypes.class);
+            AllJavaTypes allJavaTypes = realm.createObject(AllJavaTypes.class, UUID.randomUUID().getLeastSignificantBits());
+
+            assertNull(allJavaTypes.getFieldObject());
+            allJavaTypes.getFieldBooleanList().add(null);
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java:1653]: These tests do not seem related in a test named `getNullableFields` Lists can never be `null` and I hope that adding null is tested elsewhere, if not, it should probably be in its own test?

File: realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java [hunk 6]
```diff
@@ -1629,4 +1631,95 @@ public void run() {
...
         TestHelper.awaitOrFail(threadFinished);
     }
+
+    @Test
+    public void getNullableFields() {
+        realm.executeTransaction(realm -> {
+            NullablePrimitiveFields primitiveNullables = realm.createObject(NullablePrimitiveFields.class);
+            primitiveNullables.setFieldBoolean(null);
+
+            assertNull(primitiveNullables.getFieldBoolean());
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java:1641]: all of these should be tested below?

File: realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java (hunk 2 above)
Comment (cmelchior) [reply realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java:97]: No, those tests should be fine

**Review by cmelchior — APPROVED** [review]

File: realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java (hunk 5 above)
Comment (rorbech) [reply realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java:1653]: The issue was that we could not return null values for nullable fields from a dynamic realm. I thought it would be safest to also included a check of retrieving a null value from a list from a dynamic realm. I could try to find another place for the test...or update the name of the test to `getNullForNullables` ... ?

File: realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java (hunk 6 above)
Comment (rorbech) [reply realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java:1641]: Yes. I was just asserting that they were actually null when retrieved from the typed realm.
