### PR TITLE
Work around the memmove bug on Samsung device

### LINKED ISSUE #3651: Samsung Tab 3 Lite 7 crashes on Realm 2.0.1 and 2.0.2
A Samsung Galaxy Tab 3 Lite 7 (SM-T111) crashes on startup with the below error (Android 4.2.2)
Has been confirmed working on Nexus 5, Nexus 4 and emulators 15, 19, 21, 22, 23, 24.

```
10-18 11:57:25.851 D/dalvikvm( 6127): Trying to load lib /data/app-lib/com.zt.android.test.realmio-1/librealm-jni.so 0x412e0568
10-18 11:57:25.851 D/dalvikvm( 6127): Added shared lib /data/app-lib/com.zt.android.test.realmio-1/librealm-jni.so 0x412e0568
10-18 11:57:25.859 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeCreateConfig
10-18 11:57:25.859 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeGetSharedRealm 1521857752
10-18 11:57:25.867 I/v_hwc   (  112): hwc prepare: 3D composition
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeCloseConfig 1521857752
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeHasTable 1522273128
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeCloseSharedRealm 1522273128
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeCreateConfig
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeGetSharedRealm 1521857752
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeGetVersion 1522276080
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeCloseConfig 1521857752
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 1522276080
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeGetVersion 1522276080
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeGetVersion 1522276080
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 1522276080
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeBeginTransaction 1522276080
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeGetVersion 1522276080
10-18 11:57:25.875 V/REALM   ( 6127):  --> Java_io_realm_internal_SharedRealm_nativeSetVersion 1522276080
10-18 11:57:25.875 F/libc    ( 6127): Fatal signal 11 (SIGSEGV) at 0x5ab3eff6 (code=2), thread 6127 (id.test.realmio)
10-18 11:57:25.882 F/libc    ( 6127): Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 6142 (id.test.realmio)
```

```
10-18 11:48:42.945 D/CrashAnrDetector(  484): Build: samsung/goya3gxx/goya3g:4.2.2/JDQ39/T111XXUAOC2:user/release-keys
10-18 11:48:42.945 D/CrashAnrDetector(  484): Hardware: PXA986
10-18 11:48:42.945 D/CrashAnrDetector(  484): Revision: 2
10-18 11:48:42.945 D/CrashAnrDetector(  484): Bootloader: T111XXUAOC2
10-18 11:48:42.945 D/CrashAnrDetector(  484): Radio: unknown
10-18 11:48:42.945 D/CrashAnrDetector(  484): Kernel: Linux version 3.4.5-2825369 (se.infra@SWDB2804) (gcc version 4.6.x-google 20120106 (prerelease) (GCC) ) #2 SMP PREEMPT Tue Mar 17 22:04:14 KST 2015
10-18 11:48:42.945 D/CrashAnrDetector(  484):
10-18 11:48:42.945 D/CrashAnrDetector(  484): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-18 11:48:42.945 D/CrashAnrDetector(  484): Build fingerprint: 'samsung/goya3gxx/goya3g:4.2.2/JDQ39/T111XXUAOC2:user/release-keys'
10-18 11:48:42.945 D/CrashAnrDetector(  484): Revision: '2'
10-18 11:48:42.945 D/CrashAnrDetector(  484): pid: 5805, tid: 5805, name: id.test.realmio  >>> io.realm.test.realmio <<<
10-18 11:48:42.945 D/CrashAnrDetector(  484): signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 5baa4ffe
10-18 11:48:42.945 D/CrashAnrDetector(  484):     r0 5baa500b  r1 5baa4ffe  r2 5bb71283  r3 5baa4ffe
10-18 11:48:42.945 D/CrashAnrDetector(  484):     r4 00000000  r5 5baa500a  r6 5bbb5358  r7 5dc08d20
10-18 11:48:42.945 D/CrashAnrDetector(  484):     r8 00000010  r9 00000010  sl 5e8bf810  fp 00000010
10-18 11:48:42.945 D/CrashAnrDetector(  484):     ip 00000000  sp bed19318  lr 00000000  pc 5e7a1052  cpsr 20000030
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d0  65706f72705f6b70  d1  532f6c616e726500
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d2  65742e64696f7200  d3  6d6c6165722e7402
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d4  746c75616665642f  d5  6d2e6d6c6165722e
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d6  6e656d6567616e61  d7  7373656363612f74
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d8  0000000000000000  d9  0000000000000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d10 0000000000000000  d11 0000000000000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d12 0000000000000000  d13 0000000000000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d14 0000000000000000  d15 0000000000000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d16 4026000000000000  d17 0000000000000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d18 0000000000000000  d19 0000000000000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d20 4008000000000000  d21 3fbc71c71c71c71c
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d22 3fcc7288e957b53b  d23 3fd24998d6307188
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d24 3fd99a27ad32ddf5  d25 3fe555b0aaeac752
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d26 0000000000000000  d27 0000000000000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d28 0000000000000000  d29 0000000000000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):     d30 0000000000000000  d31 0000000000000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):     scr 20000010
10-18 11:48:42.945 D/CrashAnrDetector(  484):
10-18 11:48:42.945 D/CrashAnrDetector(  484): backtrace:
10-18 11:48:42.945 D/CrashAnrDetector(  484):     #00  pc 00082052  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):     #01  pc 000a50b7  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):     #02  pc 0005a69d  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):
10-18 11:48:42.945 D/CrashAnrDetector(  484): stack:
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed192d8  5bbb5950
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed192dc  00001680
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed192e0  5bbb5bd0
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed192e4  00001900
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed192e8  5e7991cb  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed192ec  5e7a0e85  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed192f0  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed192f4  5e8d4168  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed192f8  5bbb5958
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed192fc  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19300  bed19330  [stack]
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19304  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19308  5dc08d20
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed1930c  5dc08d20
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19310  df0027ad
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19314  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):     #00  bed19318  5e799c41  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed1931c  00000001
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19320  0000000f
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19324  00000008
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19328  5e8bf810  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed1932c  00000008
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19330  5bbb5360
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19334  ffffffff
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19338  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed1933c  5dc08d20
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19340  00000001
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19344  00000001
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19348  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed1934c  5e8bf810  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19350  5dc08008
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19354  5e7c40bb  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):     #01  bed19358  ffffffff
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed1935c  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19360  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19364  00000008
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19368  5abee570
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed1936c  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19370  5ab9ed08
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19374  5abee6e0
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19378  5e8bf810  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed1937c  00000008
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19380  00000001
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19384  5e7db265  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19388  5e8bf810  /data/app-lib/io.realm.test.realmio-1/librealm-jni.so
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed1938c  00000008
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19390  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed19394  5abee570
10-18 11:48:42.945 D/CrashAnrDetector(  484):          ........  ........
10-18 11:48:42.945 D/CrashAnrDetector(  484):     #02  bed193b8  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed193bc  00000000
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed193c0  5dc08d20
10-18 11:48:42.945 D/CrashAnrDetector(  484):          bed193c4  5e7c0c
10-18 11:48:42.945 D/CrashAnrDetector(  484): processName:io.realm.test.realmio
10-18 11:48:42.945 D/CrashAnrDetector(  484): broadcastEvent : io.realm.test.realmio SYSTEM_TOMBSTONE
```

I'm working on getting a sample project. /cc @beeender

### PR DESCRIPTION
**Pull request by beeender**
Fix #3651

### CODE REVIEW

**Comment by Zhuinden** [comment]
If this works.... Celebration :smile:

**Comment by nhachicha** [comment]
is this function hooking? we used similar approach in ReactNative https://github.com/realm/realm-js/blob/master/src/android/jsc_override.cpp#L60-L126

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+{
+    return (int8_t*)__real_memmove(dest, src, n) - n;
+}
+
+void* __wrap_memmove(void *dest, const void *src, size_t n)
+{
+    return (*s_wrap_memmove_ptr)(dest, src, n);
+}
+
+static void check_memmove()
```
Comment (cmelchior) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: Did this test come from anywhere? Then a link to that would be nice

File: realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp [hunk 2]
```diff
@@ -57,6 +59,8 @@ JNIEXPORT void JNICALL Java_io_realm_internal_SharedRealm_nativeInit(JNIEnv* env
 {
     TR_ENTER()
 
+    hack_init();
```
Comment (cmelchior) [inline realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp]: Shouldn't this be called in JNI_OnLoad or something? There is no guarantee that this code is the first native code being called?

Comment (beeender) [inline realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp]: UH, yes, `JNI_OnLoad()` would be a better place! But first need to make this patch work ...

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp (hunk 1 above)
Comment (Zhuinden) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: it's from https://code.google.com/p/android/issues/detail?id=81692

**Comment by beeender** [comment]
@nhachicha no, the code you posted is really hacky 😁  It modifies the machine code in RAM during run time. This will just link to our wrapped version function during the linking time.

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 3]
```diff
@@ -32,10 +32,25 @@ void* __builtin_memmove(void *dest, const void *src, size_t n);
...
-    return __builtin_memmove(dest, src, n);
+    uint8_t* tmp;
+    const uint8_t* s;
+
+    if (dest <= src) {
+		tmp = (uint8_t*)dest;
+		s = (uint8_t*)src;
+		while (count--)
+			*tmp++ = *s++;
+	} else {
```
Comment (Zhuinden) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: whitespace is weird here

File: realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp (hunk 2 above)
Comment (nhachicha) [inline realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp]: I think using `__attribute__((constructor));` is also an option, if I remember it runs when the `.so` is loaded https://github.com/realm/realm-js/blob/master/src/android/jsc_override.cpp#L38

**Comment by beeender** [comment]
### Benchmark, on a low-end Arm device:
#### With this PR:
image

#### Without this PR:
image

No notable difference can be seen.

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+extern "C" {
+void* __wrap_memmove(void* dest, const void* src, size_t n);
+void* __real_memmove(void* dest, const void* src, size_t n);
+void* __builtin_memmove(void* dest, const void* src, size_t n);
+}
+
+typedef void* (*MemMoveFunc)(void* dest, const void* src, size_t n);
+static MemMoveFunc s_wrap_memmove_ptr = &__real_memmove;
+
+// Pure C implementation for memmove. Copied from kernel.
```
Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: "kernel" -> "the Linux kernel"

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+static void* hacked_memmove(void* dest, const void* src, size_t count)
+{
+    uint8_t* tmp;
+    const uint8_t* s;
+
+    if (dest <= src) {
+        tmp = (uint8_t*)dest;
+        s = (uint8_t*)src;
+        while (count--)
```
Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: Wrap in `{ ... }`

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+            *tmp++ = *s++;
+    }
+    else {
+        tmp = (uint8_t*)dest;
+        tmp += count;
+        s = (uint8_t*)src;
+        s += count;
+        while (count--)
```
Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: Wrap in `{ ... }`

**Comment by kneth** [comment]
Switch to a pure C implementation (for the buggy devices) is probably going to slow down these devices. On the other hand, preventing a crash is more important than performance.

**Comment by finnschiermer** [comment]
The code looks fine to me. BUT: The Linux Kernel is under GPL. Copying a piece of code from it is likely a no-go, even if the code under consideration can be found in virtually any introduction to C.

**Comment by beeender** [comment]
UH!! Right!! I will get some other implementation then.

File: realm/realm-library/src/main/cpp/io_realm_internal_Util.cpp [hunk 7]
```diff
@@ -37,6 +38,9 @@ const string TABLE_PREFIX("class_");
 
 JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*)
 {
+    // Workaround some known bugs of system calls on some special devices.
```
Comment (cmelchior) [inline realm/realm-library/src/main/cpp/io_realm_internal_Util.cpp]: I would rewrite this to:

"Workaround for some known bugs in system calls on specific devices"

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 8]
```diff
@@ -0,0 +1,85 @@
...
+// There is a bug in memmove for some Samsung devices which will return "dest-n" instead of dest.
+// The bug was originally found by QT, see https://bugreports.qt.io/browse/QTBUG-34984 .
+// To work around it, we use linker's wrap feature to use a pure C implementation of memmove if the device has the
+// problem.
+static void check_memmove()
+{
+    char* array = strdup("Foobar");
+    void* ptr = __real_memmove(array + 1, array, sizeof("Foobar") - 2);
+    if (ptr != array + 1) {
+        Log::e("memmove is broken on this device. switch to the builtin implementation.");
```
Comment (cmelchior) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: Switching to the builtin

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 9]
```diff
@@ -0,0 +1,85 @@
...
+        s_wrap_memmove_ptr = &hacked_memmove;
+    }
+    else {
+        Log::i("memmove is not broken on this device - lucky you.");
```
Comment (cmelchior) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: No need to log anything in this case.

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 10]
```diff
@@ -72,6 +67,7 @@ static void check_memmove()
     if (ptr != array + 1) {
         Log::e("memmove is broken on this device. switch to the builtin implementation.");
         s_wrap_memmove_ptr = &hacked_memmove;
+        s_wrap_memcpy_ptr =  &hacked_memmove;
```
Comment (Zhuinden) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: memcpy can be replaced also by `hacked_memmove`? cool

File: realm/realm-library/src/main/cpp/jni_util/bcopy.cpp [hunk 11]
```diff
@@ -0,0 +1,139 @@
...
+/*
+ * Macros: loop-t-times; and loop-t-times, t>0
+ */
+#define TLOOP(s)                                                                                                     \
+    if (t)                                                                                                           \
+    TLOOP1(s)
+#define TLOOP1(s)                                                                                                    \
+    do {                                                                                                             \
+        s;                                                                                                           \
+    } while (--t)
```
Comment (zaki50) [inline realm/realm-library/src/main/cpp/jni_util/bcopy.cpp]: Are those macro definition correct?

I think those should be in one line like:
```
#define	TLOOP(s) if (t) TLOOP1(s)
#define	TLOOP1(s) do { s; } while (--t)
```

File: realm/realm-library/src/main/cpp/CMakeLists.txt [hunk 12]
```diff
@@ -126,7 +126,7 @@ endif()
 set(WARNING_CXX_FLAGS "-Werror -Wall -Wextra -pedantic -Wmissing-declarations \
     -Wempty-body -Wparentheses -Wunknown-pragmas -Wunreachable-code \
     -Wno-missing-field-initializers  -Wno-maybe-uninitialized -Wno-uninitialized")
-set(REALM_COMMON_CXX_FLAGS "-DREALM_ANDROID -DREALM_HAVE_CONFIG -DPIC -pthread -fvisibility=hidden -std=c++14 -fsigned-char")
+set(REALM_COMMON_CXX_FLAGS "-DREALM_ANDROID -DREALM_HAVE_CONFIG -DPIC -pthread -fvisibility=hidden -std=c++14 -fsigned-char -fno-builtin-memcpy -fno-builtin-memmove")
```
Comment (zaki50) [inline realm/realm-library/src/main/cpp/CMakeLists.txt]: I think we should add a comment why `-fno-builtin-memcpy` and `-fno-builtin-memmove` are needed.

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp (hunk 10 above)
Comment (zaki50) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: yes, the only difference between `memcpy` and `memmove` is that the `memmove` guarantees to work as expected when the source and destination are overlapping.

File: realm/realm-library/src/main/cpp/jni_util/bcopy.cpp (hunk 11 above)
Comment (zaki50) [inline realm/realm-library/src/main/cpp/jni_util/bcopy.cpp]: no idea why current code is working as expected..

Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/bcopy.cpp]: Notice `\` at the end of the lines

File: realm/realm-library/src/main/cpp/CMakeLists.txt (hunk 12 above)
Comment (kneth) [inline realm/realm-library/src/main/cpp/CMakeLists.txt]: I don't think they are required.

File: realm/realm-library/src/main/cpp/jni_util/bcopy.cpp (hunk 11 above)
Comment (zaki50) [inline realm/realm-library/src/main/cpp/jni_util/bcopy.cpp]: Ah, github does not print `\` at the end of line...

File: realm/realm-library/src/main/cpp/CMakeLists.txt (hunk 12 above)
Comment (zaki50) [inline realm/realm-library/src/main/cpp/CMakeLists.txt]: nice

File: realm/realm-library/src/main/cpp/jni_util/bcopy.cpp (hunk 11 above)
Comment (zaki50) [inline realm/realm-library/src/main/cpp/jni_util/bcopy.cpp]: No, my fault. Since I reviewed this on mobile phone, I didn't see the right edge..

Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/bcopy.cpp]: 📵  :smile:

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 13]
```diff
@@ -27,44 +28,40 @@ extern "C" {
...
-	} else {
-		tmp = (uint8_t*)dest;
-		tmp += count;
-		s = (uint8_t*)src;
-		s += count;
-		while (count--)
-			*--tmp = *--s;
-	}
-	return dest;
+    Log::e("hacked_memmove");
```
Comment (Zhuinden) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: probably shouldn't leave that there long-term

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp (hunk 10 above)
Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: For example, on FreeBSD and OS X `memmove` and `memcpy` are calling `bcopy`. The only difference is that `memmove` returns the new end. I mean, this are the naive implementation in C. FreeBSD (haven't check OS X) has optimized versions written in assembler for a number of architectures like Intel and ARM.

File: realm/realm-library/src/main/cpp/CMakeLists.txt [hunk 14]
```diff
@@ -138,7 +138,7 @@ set(CMAKE_CXX_FLAGS_DEBUG "-ggdb -Og -DNDEBUG")
 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${REALM_COMMON_CXX_FLAGS} ${WARNING_CXX_FLAGS} ${ABI_CXX_FLAGS}")
 
 # Set link flags
-set(REALM_LINKER_FLAGS "")
+set(REALM_LINKER_FLAGS "-Wl,--wrap,memmove -Wl,--wrap,memcpy")
```
Comment (beeender) [inline realm/realm-library/src/main/cpp/CMakeLists.txt]: I think we may want to keep the workaround limited to the `memmove` only since we don't have any evidence to say there is a bug for `memcpy` as well.

File: realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp (hunk 2 above)
Comment (beeender) [inline realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp]: `__attribute__((constructor));` looks much better, but it seems to be a gcc extension, i am not quite sure if clang support it. I will check and replace the `JNI_onLoad()` if it supported for clang as well.

File: realm/realm-library/src/main/cpp/jni_util/bcopy.hpp [hunk 15]
```diff
@@ -0,0 +1,29 @@
...
+
+#ifndef REALM_BCOPY_H
+#define REALM_BCOPY_H
+
+#include <cstddef>
+
+namespace realm {
+namespace jni_util {
+
+void* my_bcopy(void *, const void *, std::size_t);
```
Comment (beeender) [inline realm/realm-library/src/main/cpp/jni_util/bcopy.hpp]: `my_bcopy` sounds strange... just `__bcopy`? Also, no need to have this in an independent header since it is not supposed to be used for any other places, just `extern` it from the `hack.cpp`?

File: realm/realm-library/src/main/cpp/CMakeLists.txt (hunk 14 above)
Comment (kneth) [inline realm/realm-library/src/main/cpp/CMakeLists.txt]: I have seen a few stack traces with `memcpy`. But it can be that `memcpy` calls `memmove` in certain cases.

**Comment by kneth** [comment]
@beeender I have asked our ops team for legal advice since we are including 3rd party code. Please do not merge before we have a clear understanding of the legal implications.

**Comment by Zhuinden** [comment]
@kneth any luck? This fix is super-duper important

**Comment by cmelchior** [comment]
@Zhuinden We just pinged our legal. 
We want this released just as much as you 😄

**Comment by dalinaum** [comment]
Sumsung? Is it a typo?

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 16]
```diff
@@ -0,0 +1,81 @@
...
+{
+    char* array = strdup("Foobar");
+    void* ptr = __real_memmove(array + 1, array, sizeof("Foobar") - 2);
+    if (ptr != array + 1) {
+        Log::e("memmove is broken on this device. switch to the builtin implementation.");
+        s_wrap_memmove_ptr = &hacked_memmove;
+        s_wrap_memcpy_ptr =  &hacked_memmove;
+    }
+    else {
+        Log::i("memmove is not broken on this device - lucky you.");
```
Comment (dalinaum) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: Should it be logged?

**Comment by Zhuinden** [comment]
Shame that 3.1.0 did not have this, hoping for 3.1.1 😄

**Comment by cmelchior** [comment]
Yes, we wil make a patch release with this as soon as legal gives a 👍

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp (hunk 16 above)
Comment (cmelchior) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: No this shouldn't be logged :)

**Comment by beeender** [comment]
need to benchmark with/without wrap `memcpy`

**Comment by beeender** [comment]
Wrap both memmove and memcpy:
with_memcpy_0

wrap only memmove
without_memcpy_1

no noticeable performance difference.

**Comment by Zhuinden** [comment]
> Switching to DRY libc11's implementations

I guess the legal team said you need one with a bit more permissive license

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 17]
```diff
@@ -0,0 +1,116 @@
...
+void* __wrap_memcpy(void *dest, const void *src, size_t n)
+{
+    return (*s_wrap_memcpy_ptr)(dest, src, n);
+}
+
+
+// See https://github.com/realm/realm-java/issues/3651#issuecomment-290290228
+// There is a bug in memmove for some Samsung devices which will return "dest-n" instead of dest.
+// The bug was originally found by QT, see https://bugreports.qt.io/browse/QTBUG-34984 .
+// To work around it, we use linker's wrap feature to use a pure C implementation of memmove if the device has the
```
Comment (cmelchior) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: has this

File: realm/realm-library/src/main/cpp/jni_util/hack.cpp [hunk 18]
```diff
@@ -0,0 +1,116 @@
...
+// problem.
+static void check_memmove()
+{
+    char* array = strdup("Foobar");
+    size_t len = strlen(array);
+    void* ptr = __real_memmove(array + 1, array, len - 1);
+    if (ptr != array + 1 || strncmp(array, "FFooba", len) != 0) {
+        Log::e("memmove is broken on this device. Switching to the builtin implementation.");
```
Comment (cmelchior) [inline realm/realm-library/src/main/cpp/jni_util/hack.cpp]: `builtin` reads wrong to me here. What about `Switching to a version provided by Realm` ?
