### PR TITLE
addPrimaryKey() on RealmObjectSchema misses Index addition.

### LINKED ISSUE #2819: "Index not defined for existing Realm file" error while performing migration.
Hello,

I'm using Realm 0.90.1.

I'm trying to perform a migration in which I want to create two more tables. One of them has a @PrimaryKey.

I've tried the manual way like this:

And the migration looks like this:

```
          public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
		RealmSchema schema = realm.getSchema();

		if (oldVersion == 0) {
			schema.create("Table1").addField("myid", long.class)
					.addField("test", boolean.class)
					.addPrimaryKey("myid");

			schema.create("Table2").addField("wID", int.class)
				.addField("uID", int.class)
				.addField("ts", long.class)
				.addField("type", String.class);

			oldVersion++;
		}
```

My applications crashes with the following exception:

`                                                                         
Process: com.vectorwatch.android, PID: 22182 java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4664)`

I've dived deeper in Realm code and I've saw that an exception is thrown with the following detailsMessage:

`Index not defined for field myid in existing Realm file. Either set @Index or migrate using io.realm.internal.Table.removeSearchIndex().
`

So I assumed that I should call also addIndex() in the migration. This did the trick, but this is was kind of annoying. From the Realm documentation, I see that "(the annotation @PrimaryKey implicitly sets the annotation @Index)". The javadoc of the addPrimaryKey method says:

`
     * Adds a primary key to a given field. This is the same as adding the {@link io.realm.annotations.PrimaryKey} annotation on the field.
`

So I assumed that addPrimaryKey() also adds an Index. It is nowhere mentioned that when performing a migration, you should call addIndex() when you have an addPrimaryKey().

Can I make a pull request to add this use case in your Migration example app? Also please tell if I can help anymore you with this issue.

Thank you very much for this great framework!

### PR DESCRIPTION
**Pull request by stk1m1**
`RealmObjectSchema.addPrimaryKey()` is supposed to add a search index to its primary key field but it is currently missing.  This is to fix the addition and removal of a search index related to primary key methods in `RealmObjectSchema`. Closes #2819.

@realm/java please review.

### CODE REVIEW

**Comment by kneth** [comment]
:+1: when `CHANGELOG.md` is updated :-)

**Comment by stk1m1** [comment]
@kneth I will add it in no time.

**Comment by kneth** [comment]
@stk1m1 Me like

File: realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java [hunk 1]
```diff
@@ -226,6 +226,41 @@ public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
...
+
+        // Create v1 of the Realm
+        RealmConfiguration realmConfig = configFactory.createConfigurationBuilder()
+                .schemaVersion(1)
+                .schema(AllTypes.class, AnnotationTypes.class)
+                .migration(migration)
+                .build();
+
+        realm = Realm.getInstance(realmConfig);
+        RealmObjectSchema schema = realm.getSchema().getSchemaForClass(AnnotationTypes.class);
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java]: `getSchemaForClass` is an internal API, the public method is just called `get`. We should use the public API if possible IMO

**Comment by cmelchior** [comment]
Apart from small comment 👍

**Comment by nhachicha** [comment]
+1
