### PR TITLE
Fixed race condition when closing Realms

### LINKED ISSUE #1608: NPE at BaseRealm.java:591
Today I upgraded our app to Realm 0.83.1 from my previous patched build of 0.83.0

Unfortunately I've seen the "Cannot send message to Handler on a dead thread" error @cmelchior  and I were battling a couple of weeks ago, although I don't have much data to help track that down yet.

Also, there's a new NPE bug in BaseRealm.java which should be reasonably easy to figure out - here's the stack trace:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.realm.internal.SharedGroupManager.advanceRead()' on a null object reference
at io.realm.BaseRealm$RealmCallback.handleMessage(BaseRealm.java:591)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5430)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
```

I'm happy to help debug this with a custom build of realm-java with additional debug code next week, so let me know if there's anything in particular I should do to help. 
Obviously trying to narrow it down to a simple test case would be ideal but I won't be able to spend significant time doing anything like that until later next week.

Cheers,
Andrew

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #1608 

To qoute Dianne Hackborn: "Once you think you understand concurrency, It will jump right back and bite you" :(
Also WTF is a method called `removeCallbacksAndMessages` not removing the only thing in the Handler API actually called Callback.

Problem is that we store our handlers in a ConcurrentHashMap. This means that if we start iterating over them in another thread it is over a copy of the map, so if a Realm is closed in the meantime on the original thread, the iterator will still post messages to it. At the same time, we have no way of telling the handler on the original thread to actually stop handling messages.

Only way around this would be to synchronize access to all our handlers, which I want to avoid for performance reasons as the Handlers are our main way of propagating changes. So instead our `Handler.Callback` now checks if the Realm is actually still open.

@realm/java 
@andrewthecoder

### CODE REVIEW

File: realm/src/main/java/io/realm/BaseRealm.java [hunk 1]
```diff
@@ -600,7 +608,12 @@ public static synchronized void migrateRealm(RealmConfiguration configuration, R
     private class RealmCallback implements Handler.Callback {
         @Override
         public boolean handleMessage(Message message) {
-            if (message.what == REALM_CHANGED) {
+            // Due to how a ConcurrentHashMap iterator is created we cannot be sure that other threads are
+            // aware when this threads handler is removed before they send messages to it. We don't wish to synchronize
+            // access to the handlers as they are the prime mean of notifying about updates. Instead we make sure
+            // that if a message does slip though (however unlikely), it will not try to update a SharedGroup that no
+            // long exists. `sharedGroupManager` will only be null if a Realm is really closed.
```
Comment (emanuelez) [inline realm/src/main/java/io/realm/BaseRealm.java]: long -> longer

**Comment by emanuelez** [comment]
Nice! Is there any way to write a test that exposes the bug this PR fixes?

**Comment by cmelchior** [comment]
Only in a synthetic test case. We both create the iterator and iterate inside `commitTransaction` so I don't there is any way of adding lock-steps to it :(

**Comment by emanuelez** [comment]
:+1:

File: realm/src/main/java/io/realm/BaseRealm.java [hunk 2]
```diff
@@ -176,9 +177,13 @@ public void removeAllChangeListeners() {
...
 
-    protected void removeHandler(Handler handler) {
-        handler.removeCallbacksAndMessages(null);
+    /**
+     * Remove and stop the current thread handler as gracefully as possible.
+     */
+    protected void removeHandler() {
         handlers.remove(handler);
+        // Warning: This only clears the Looper queue. Handler.Callback is not removed.
+        handler.removeCallbacksAndMessages(null);
```
Comment (nhachicha) [inline realm/src/main/java/io/realm/BaseRealm.java]: This will only remove any pending posts, what about preventing other threads from posting?

Comment (nhachicha) [inline realm/src/main/java/io/realm/BaseRealm.java]: ok just saw your hack with `if (message.what == REALM_CHANGED && sharedGroupManager != null)`

**Comment by nhachicha** [comment]
:+1:

**Comment by andrewthecoder** [comment]
Very nice @cmelchior, thanks for looking into this again!

I was never able to narrow this down to a simple test case @emanuelez as it involves using realm-java in an app with lots of concurrency with various different background threads accessing the database simultaneously.

As such, the closest we've got to a test case is my app - I was seeing the "Cannot send message to Handler on a dead thread" error at least once quite quickly after launching my app and logging in (starting the background tasks).
I'll build and test this PR branch later today or tomorrow.

**Comment by andrewthecoder** [comment]
So I've been testing / developing for the last 6 hours with the latest snapshot built from this branch, and my app hasn't crashed once, so the null check / NPE fix is definitely fine.

The bad news is, as much as your epiphany and explanation above makes total sense to me, I just saw the handler warning again (for the first time in 6 hours though, so I think that's better than before!):

```
10-18 02:59:28.246 390-435/com.podfather.podfather D/PF.HTTPLoggingInterceptor: Sending request http://andrewfather-hapi.int.podfather.com/auto_list_jobs_json.php?v=1.3&d=9779&iat=1 on Connection{andrewfather-hapi.int.podfather.com:80, proxy=DIRECT@ hostAddress=192.168.98.66 cipherSuite=none protocol=http/1.1}
10-18 02:59:28.246 390-435/com.podfather.podfather D/PF.HTTPLoggingInterceptor: User-Agent: Android|5.1|22|6.49|1.30|LGE LG-H815|IMEI.359872061632294
10-18 02:59:28.246 390-435/com.podfather.podfather D/PF.HTTPLoggingInterceptor: Cache-Control: no-cache
10-18 02:59:28.246 390-435/com.podfather.podfather D/PF.HTTPLoggingInterceptor: Authorization: Basic VnRhYjp2dGFiMTIzNA==
10-18 02:59:28.246 390-435/com.podfather.podfather D/PF.HTTPLoggingInterceptor: Host: andrewfather-hapi.int.podfather.com
10-18 02:59:28.246 390-435/com.podfather.podfather D/PF.HTTPLoggingInterceptor: Connection: Keep-Alive
10-18 02:59:28.246 390-435/com.podfather.podfather D/PF.HTTPLoggingInterceptor: Accept-Encoding: gzip
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue: Handler (android.os.Handler) {12b5defb} sending message to a Handler on a dead thread
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {12b5defb} sending message to a Handler on a dead thread
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.enqueueMessage(Handler.java:631)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendMessageAtTime(Handler.java:600)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendMessageDelayed(Handler.java:570)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendEmptyMessage(Handler.java:519)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at io.realm.BaseRealm.commitTransaction(BaseRealm.java:316)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at io.realm.Realm.commitTransaction(Realm.java:112)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.data.LocalStorage.setItem(LocalStorage.java:108)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.helpers.Utilities.setDataStringByType(Utilities.java:405)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.helpers.Utilities.setStorageString(Utilities.java:391)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.interfaces.JavaScriptInterface.setupRegularAlarmsFromAccountFeatures(JavaScriptInterface.java:3104)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.interfaces.JavaScriptInterface.setupAlarms(JavaScriptInterface.java:1686)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Looper.loop(Looper.java:135)
10-18 02:59:28.266 390-593/com.podfather.podfather W/MessageQueue:     at android.os.HandlerThread.run(HandlerThread.java:61)
10-18 02:59:28.266 390-593/com.podfather.podfather W/REALM: Cannot update Looper threads when the Looper has quit. Use realm.setAutoRefresh(false) to prevent this.
10-18 02:59:28.266 390-593/com.podfather.podfather D/PF.JavaScriptInterface: Detected and set jobPollingEnabled to true as account feature value = 1
10-18 02:59:28.276 390-3909/com.podfather.podfather I/PF.JavaScriptInterface: Executing JavaScript in WebView: PFUI.updateDataToSendDisplay() from com.podfather.podfather.interfaces.JavaScriptInterface.callJSInWebview, com.podfather.podfather.services.DataPostService.updateDataToSendCount, com.podfather.podfather.services.DataPostService.onHandleIntent
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue: Handler (android.os.Handler) {2482f5a9} sending message to a Handler on a dead thread
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {2482f5a9} sending message to a Handler on a dead thread
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.enqueueMessage(Handler.java:631)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendMessageAtTime(Handler.java:600)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendMessageDelayed(Handler.java:570)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendEmptyMessage(Handler.java:519)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at io.realm.BaseRealm.commitTransaction(BaseRealm.java:316)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at io.realm.Realm.commitTransaction(Realm.java:112)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.data.LocalStorage.setItem(LocalStorage.java:108)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.helpers.Utilities.setDataStringByType(Utilities.java:405)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.helpers.Utilities.setStorageString(Utilities.java:391)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.interfaces.JavaScriptInterface.setupRegularAlarmsFromAccountFeatures(JavaScriptInterface.java:3118)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.interfaces.JavaScriptInterface.setupAlarms(JavaScriptInterface.java:1686)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Looper.loop(Looper.java:135)
10-18 02:59:28.286 390-593/com.podfather.podfather W/MessageQueue:     at android.os.HandlerThread.run(HandlerThread.java:61)
10-18 02:59:28.286 390-593/com.podfather.podfather W/REALM: Cannot update Looper threads when the Looper has quit. Use realm.setAutoRefresh(false) to prevent this.
10-18 02:59:28.296 390-593/com.podfather.podfather D/PF.JavaScriptInterface: Starting job polling alarm to fire once every 60000ms as the account feature is enabled 
10-18 02:59:28.316 390-3909/com.podfather.podfather D/PF.DataPostService: Successful POST requests: 0, failed POST requests: 0
10-18 02:59:28.316 390-3909/com.podfather.podfather D/PF.DataPostService: calling JS function: PFCallbacks.actionDataPostComplete()
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue: Handler (android.os.Handler) {5b9bdbf} sending message to a Handler on a dead thread
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {5b9bdbf} sending message to a Handler on a dead thread
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.enqueueMessage(Handler.java:631)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendMessageAtTime(Handler.java:600)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendMessageDelayed(Handler.java:570)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.sendEmptyMessage(Handler.java:519)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at io.realm.BaseRealm.commitTransaction(BaseRealm.java:316)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at io.realm.Realm.commitTransaction(Realm.java:112)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.data.LocalStorage.setItem(LocalStorage.java:108)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.helpers.Utilities.setDataStringByType(Utilities.java:405)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.helpers.Utilities.setStorageString(Utilities.java:391)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.interfaces.JavaScriptInterface.setupRegularAlarmsFromAccountFeatures(JavaScriptInterface.java:3147)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at com.podfather.podfather.interfaces.JavaScriptInterface.setupAlarms(JavaScriptInterface.java:1686)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at android.os.Looper.loop(Looper.java:135)
10-18 02:59:28.326 390-593/com.podfather.podfather W/MessageQueue:     at android.os.HandlerThread.run(HandlerThread.java:61)
10-18 02:59:28.326 390-593/com.podfather.podfather W/REALM: Cannot update Looper threads when the Looper has quit. Use realm.setAutoRefresh(false) to prevent this.
10-18 02:59:28.326 390-593/com.podfather.podfather D/PF.JavaScriptInterface: Detected and set trackingEnabled to true from driver details 
10-18 02:59:28.326 390-593/com.podfather.podfather D/PF.JavaScriptInterface: Parsed tracking frequency to milliseconds from account feature value: 60000
10-18 02:59:28.336 390-3909/com.podfather.podfather I/PF.JavaScriptInterface: Executing JavaScript in WebView: PFCallbacks.actionDataPostComplete(0, 0) from com.podfather.podfather.interfaces.JavaScriptInterface.callJSInWebview, com.podfather.podfather.services.DataPostService.onHandleIntent, android.app.IntentService$ServiceHandler.handleMessage
10-18 02:59:28.336 390-3909/com.podfather.podfather D/PF.DataPostService: onHandleIntent setting dataPostService.currentlyProcessing to false
10-18 02:59:28.336 390-3909/com.podfather.podfather D/PF.DataPostService: Completed dataPostService, releasing wakelock if one is held
10-18 02:59:28.336 390-593/com.podfather.podfather D/PF.JavaScriptInterface: Starting tracking alarm to fire once every 60000ms as the handheld_tracking account feature is enabled 
10-18 02:59:28.366 390-593/com.podfather.podfather D/PF.JavaScriptInterface: Detected and set deviceHealthEnabled to true from driver details 
10-18 02:59:28.386 390-593/com.podfather.podfather D/PF.JavaScriptInterface: Starting device health alarm to fire once every 60000ms as the handheld_device_health account feature is enabled 
```

Sorry @cmelchior!
As usual let me know if there's anything else I can add to my build to help debug.

**Comment by andrewthecoder** [comment]
Actually, I spoke too soon - it's happening in the exact same place as it was when I was debugging this with you two weeks ago; on login to our app, when this method is called:

```
public void cancelAlarms()
    {
        CustomLog.callingMethod(LOG_TAG);

        // Get reference to system alarm manager to remove alarms
        AlarmManager alarmManager = (AlarmManager) singleton.getSystemService(Context.ALARM_SERVICE);

        XWalkViewActivity xWalkViewActivity = XWalkViewActivity.getInstance();
        if (xWalkViewActivity != null)
        {
            CustomLog.i(LOG_TAG, "Stopping all services and alarms");


            CustomLog.v(LOG_TAG, "Stopping dataPostService");
            Intent service = new Intent(xWalkViewActivity, DataPostService.class);
            xWalkViewActivity.stopService(service);

            CustomLog.v(LOG_TAG, "Stopping ConnectivityCheckService");
            service = new Intent(xWalkViewActivity, ConnectivityCheckService.class);
            xWalkViewActivity.stopService(service);

            CustomLog.v(LOG_TAG, "Stopping HealthService");
            service = new Intent(xWalkViewActivity, HealthService.class);
            xWalkViewActivity.stopService(service);

            CustomLog.v(LOG_TAG, "Stopping JobDataUpdateService");
            service = new Intent(xWalkViewActivity, JobDataUpdateService.class);
            xWalkViewActivity.stopService(service);

            CustomLog.v(LOG_TAG, "Stopping LocationService");
            service = new Intent(xWalkViewActivity, LocationService.class);
            xWalkViewActivity.stopService(service);


            CustomLog.v(LOG_TAG, "Cancelling DataPostAlarm PendingIntent alarm");
            // Stop once-every-fifteen-minutes-ish alarm to start service and POST any data which is still pending
            Intent intentAlarm = new Intent("com.podfather.podfather.DataPostAlarm");
            intentAlarm.setClass(xWalkViewActivity, DataPostWakefulReceiver.class);
            PendingIntent dataPostAlarmPendingIntent = PendingIntent.getBroadcast(xWalkViewActivity, 0, intentAlarm, PendingIntent.FLAG_UPDATE_CURRENT);
            alarmManager.cancel(dataPostAlarmPendingIntent);

            CustomLog.v(LOG_TAG, "Cancelling LocationUpdate PendingIntent alarm 0");
            // Stop once-every-fifteen-minutes-ish alarm to update the device location without a timeout, allowing the device to try and get a fix even in trickier locations
            Intent locationUpdateIntent = new Intent("com.podfather.podfather.LocationUpdate");
            locationUpdateIntent.setClass(xWalkViewActivity, LocationUpdateWakefulReceiver.class);
            PendingIntent locationUpdateFifteenMinutesPendingIntent = PendingIntent.getBroadcast(xWalkViewActivity, 0, locationUpdateIntent, PendingIntent.FLAG_UPDATE_CURRENT);
            alarmManager.cancel(locationUpdateFifteenMinutesPendingIntent);

            CustomLog.v(LOG_TAG, "Cancelling LocationUpdate PendingIntent alarm 1");
            // Stop once-every-X-seconds alarm to update the device location when tracking is enabled
            PendingIntent locationUpdateTenSecondsPendingIntent = PendingIntent.getBroadcast(xWalkViewActivity, 1, locationUpdateIntent, PendingIntent.FLAG_UPDATE_CURRENT);
            alarmManager.cancel(locationUpdateTenSecondsPendingIntent);

            CustomLog.v(LOG_TAG, "Cancelling HealthUpdate PendingIntent alarm");
            // Stop once-every-X-seconds alarm to update the device health data when tracking is enabled
            Intent healthUpdateIntent = new Intent("com.podfather.podfather.HealthUpdate");
            healthUpdateIntent.setClass(xWalkViewActivity, HealthUpdateWakefulReceiver.class);
            PendingIntent healthUpdatePendingIntent = PendingIntent.getBroadcast(xWalkViewActivity, 1, healthUpdateIntent, PendingIntent.FLAG_UPDATE_CURRENT);
            alarmManager.cancel(healthUpdatePendingIntent);

            CustomLog.v(LOG_TAG, "Cancelling JobDataUpdate PendingIntent alarm");
            // Stop once-every-X-seconds alarm to update the jobs data in the background
            Intent jobDataUpdateIntent = new Intent("com.podfather.podfather.JobDataUpdate");
            jobDataUpdateIntent.setClass(xWalkViewActivity, JobDataUpdateWakefulReceiver.class);
            PendingIntent jobDataUpdatePendingIntent = PendingIntent.getBroadcast(xWalkViewActivity, 0, jobDataUpdateIntent, PendingIntent.FLAG_UPDATE_CURRENT);
            alarmManager.cancel(jobDataUpdatePendingIntent);
        }

    }
```

Obviously as you can see that method kills a bunch of Services, some which are IntentServices, so that's the cause of the dead threads.

I'm starting to think maybe it wouldn't be so hard to put together a simple test case which just has a couple of IntentService classes which are started in onCreate, both of which do nothing but write random strings to a Realm database, then after a few seconds they are both killed and restarted several times.
If I get some spare time tomorrow I'll try and do that.

**Comment by zaki50** [comment]
That warnings seems to be unavoidable since there is a chance for `handler.sendEmptyMessage(REALM_CHANGED)` to return `false` even if `handler.getLooper().getThread().isAlive()` returns `true`.

**Comment by cmelchior** [comment]
Yes, it is a separate issue. The error message is there because is it can actually mean wrong behaviour. I described the scenario in this PR: https://github.com/realm/realm-java/pull/1501

It is especially visible when using IntentService because it will explicitly call `Looper.quit()` as part of its lifecycle in `onDestroy`. IntentServices are a bit annoying, because they have a Looper, but for the purpose of Realm they should behave as not having one. 

The race condition for this to occur still seems incredible rare though, so I can't shake the feeling that some our our caches are not behaving like they should.

One fix that should work would be to expose something like `autoRefreshLooperThreads(bool)` on the RealmConfiguration, which would also mimic the behaviour we had with our old constructors where it was a visible flag. However I am not sure it is worth the extra complexity in RealmConfiguration vs. the downside of having a spurious warning in the log. What do you think @realm/java?

In any case it would be really fast to add, so I could be tempted to do so in a branch, just to verify our assumptions.

**Comment by zaki50** [comment]
If we had a way to detect running in IntentService, we could automatically disable auto refresh.

Detecting by `Looper.myLooper().getThread().getName().startsWith("IntentService[")` is too ugly..

**Comment by zaki50** [comment]
I don't think `autoRefreshLooperThreads` is a good direction since  `Realm.getInstance(RealmConfiguration)` returns cached Realm instance and we can't guarantee that returned instance is following the configuration of auto refresh.

**Comment by cmelchior** [comment]
Good point. People might manually change auto-refresh state, which would make the semantics slightly weird, if you don't know you get a cached Realm when calling `getInstance()` 

I'm afraid we have to resort to something like `Looper.myLooper().getThread().getName().startsWith("IntentService[")` to detect IntentService, but it is a slippery path and will require a lot of testing.
