### PR TITLE
Fix transform crashing when you delete transformed objects

### LINKED ISSUE #6657: Index out of bounds in migration transformation
#### Goal
Run transformation in a migration for all elements. If a linking object (`Bar`) is found, I want to set a the string from `Bar.bbb` on the `DynamicRealmObject` (`Foo.aaa`) and if not, I want to remove the `Foo`-object.

```kotlin
schema.get("Foo")?.apply {
    addField("aaa", String::class.java)

    transform { dro ->
        dro.linkingObjects("Bar", "foo")
            ?.firstOrNull()
            ?.apply {
                dro.setString("aaa", getString("bbb"))
            }
            ?: dro.deleteFromRealm()
    }
}
```

#### Actual Results
This works fine on a few test devices I could test but crashlytics reports many crashes for end users.
I get 2 crashes:

```java
Fatal Exception: java.lang.IllegalStateException: Row index out of range
Exception backtrace:
<backtrace not supported on this platform>
       at io.realm.internal.CheckedRow.nativeSetString(CheckedRow.java)
       at io.realm.internal.UncheckedRow.setString(UncheckedRow.java:234)
       at io.realm.DynamicRealmObject.setString(DynamicRealmObject.java:689)
       at de.loewen.lcsmobile.migration.MigrateToVersion23Kt$migrateToVersion23$1$1.apply(MigrateToVersion23Kt.java:36)
       at io.realm.MutableRealmObjectSchema.transform(MutableRealmObjectSchema.java:288)
       at de.loewen.lcsmobile.migration.MigrateToVersion23Kt.migrateToVersion23(MigrateToVersion23Kt.java:26)
       at de.loewen.lcsmobile.migration.RealmMigrationManager.migrate(RealmMigrationManager.java:50)
```

and 

```java
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 54 > 53
       at io.realm.internal.Table.nativeMoveLastOver(Table.java)
       at io.realm.internal.Table.moveLastOver(Table.java:330)
       at io.realm.RealmObject.deleteFromRealm(RealmObject.java:115)
       at io.realm.RealmObject.deleteFromRealm(RealmObject.java:87)
       at de.loewen.lcsmobile.migration.MigrateToVersion23Kt$migrateToVersion23$1$1.apply(MigrateToVersion23Kt.java:46)
       at io.realm.MutableRealmObjectSchema.transform(MutableRealmObjectSchema.java:288)
       at de.loewen.lcsmobile.migration.MigrateToVersion23Kt.migrateToVersion23(MigrateToVersion23Kt.java:26)
       at de.loewen.lcsmobile.migration.RealmMigrationManager.migrate(RealmMigrationManager.java:50)
```

#### Steps & Code to Reproduce
This seems to happen everytime the user opens the app (and a migration is needed). As said, I cannot reproduce it myself because it's working on my devices.

#### Version of Realm and tooling

Realm version(s): 6.0.0

Realm Sync feature enabled: No

Android Studio version: 3.6 Beta 3

Android Build Tools version: 29.0.2

Gradle version: 5.6.4

Which Android version and device(s): 8.0.0 (Galaxy S7) crashes on the user; I've tested an S7 with 8.0.0 as well which worked. Also tested Android 10, 9, 8, 7, 6, 5 - all working.

### PR DESCRIPTION
**Pull request by cmelchior**
Closes #6657

Also add support for creating `OsResults` directly from a table, which is much faster than running a query for all objects in a table.

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java [hunk 1]
```diff
@@ -399,12 +401,30 @@ public String getPrimaryKey() {
...
-    public abstract RealmObjectSchema transform(Function function);
+    public RealmObjectSchema transform(Function function) {
+        //noinspection ConstantConditions
+        if (function != null) {
+            // Users might delete object being transformed or accidentally delete other objects
+            // in the same table. E.g. cascading deletes if it is referenced by an object being deleted.
+            OsResults results = OsResults.createFromTable(realm.sharedRealm, table).createSnapshot();
+            long size = results.size();
+            for (long i = 0; i < size; i++) {
+                DynamicRealmObject obj = new DynamicRealmObject(realm, new CheckedRow(results.getUncheckedRow((int) i)));
```
Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java]: why the `(int)` cast? `getUncheckedRow` takes a long already?
