### PR TITLE
Expanding time resolution into millisecs

### LINKED ISSUE #833: Date precisision not precise enough (dropps all milliseconds)
Java Dates have a millisecond presicsion. Realm queries on dates should respect this precision.

See the example project:
https://github.com/falkorichter/realm-date-fail

The test class in question:
https://github.com/falkorichter/realm-date-fail/blob/master/app/src/androidTest/java/com/sensorberg/android/realmdatecomparison/ApplicationTest.java

The tests shows that with 999 milliseconds difference, realm fails to query correctly.

See the status of this test at: https://travis-ci.org/falkorichter/realm-date-fail.svg?branch=master

### PR DESCRIPTION
**Pull request by kneth**
Closes #833 

Current status: ready to be merged

### CODE REVIEW

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp [hunk 1]
```diff
@@ -111,7 +111,6 @@ static jlong getDistinctViewWithHandover
         switch (table->get_column_type(S(columnIndex))) {
             case type_Bool:
             case type_Int:
-            case type_DateTime:
```
Comment (bmunkholm) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: Does timestamp not support distinct?

File: realm/realm-jni/src/util.hpp [hunk 2]
```diff
@@ -669,6 +671,31 @@ inline jobject NewFloat(JNIEnv* env, float value)
...
+}
+
+inline realm::Timestamp from_milliseconds(jlong t)
+{
+    // FIXME: find more efficient way to convert msecs -> (secs, nsecs)
+    // FIXME: guard against overflows
+    int64_t seconds;
+    uint32_t nanoseconds;
+    if (t >= 0) {
+        seconds = int64_t(double(t)*0.001);
```
Comment (zaki50) [inline realm/realm-jni/src/util.hpp]: why converted to `double`?

`seconds = int64_t(t / 1000);` does not work?

File: realm/realm-jni/src/util.hpp [hunk 3]
```diff
@@ -669,6 +671,31 @@ inline jobject NewFloat(JNIEnv* env, float value)
...
+        nanoseconds = 1000000*(int64_t(t)-1000*seconds);
+    }
+    else {
+        seconds = int64_t(double(t)*0.001) - 1;
```
Comment (zaki50) [inline realm/realm-jni/src/util.hpp]: same

File: realm/realm-jni/src/io_realm_internal_CheckedRow.cpp [hunk 4]
```diff
@@ -103,13 +103,13 @@ JNIEXPORT jdouble JNICALL Java_io_realm_internal_CheckedRow_nativeGetDouble
     return Java_io_realm_internal_UncheckedRow_nativeGetDouble(env, obj, nativeRowPtr, columnIndex);
 }
 
-JNIEXPORT jlong JNICALL Java_io_realm_internal_CheckedRow_nativeGetDateTime
+JNIEXPORT jlong JNICALL Java_io_realm_internal_CheckedRow_nativeGetTimestamp
   (JNIEnv* env, jobject obj, jlong nativeRowPtr, jlong columnIndex)
 {
-    if (!ROW_AND_COL_INDEX_AND_TYPE_VALID(env, ROW(nativeRowPtr), columnIndex, type_DateTime))
+    if (!ROW_AND_COL_INDEX_AND_TYPE_VALID(env, ROW(nativeRowPtr), columnIndex, type_Timestamp))
         return 0;
```
Comment (stk1m1) [inline realm/realm-jni/src/io_realm_internal_CheckedRow.cpp]: extra line.

File: realm/realm-jni/src/io_realm_internal_table.cpp [hunk 5]
```diff
@@ -1384,16 +1398,16 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetSortedView(
...
         case type_Double:
         case type_Float:
+        case type_Timestamp:
             try {
                 TableView* pTableView = new TableView( pTable->get_sorted_view(S(columnIndex), ascending != 0 ? true : false) );
                 return reinterpret_cast<jlong>(pTableView);
             } CATCH_STD()
         default:
-            ThrowException(env, IllegalArgument, "Sort is currently only supported on integer, boolean, double, float, String, and Date columns.");
+            ThrowException(env, IllegalArgument, "Invalid type - Only String, Date, boolean, short, int, long and their boxed variants are supported.");
```
Comment (stk1m1) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: boolean, _`byte`_, short, int, long

File: realm/realm-jni/src/io_realm_internal_tableview.cpp [hunk 6]
```diff
@@ -268,15 +268,15 @@ JNIEXPORT jdouble JNICALL Java_io_realm_internal_TableView_nativeGetDouble(
     return TV(nativeViewPtr)->get_double( S(columnIndex), S(rowIndex));  // noexcept
 }
 
-JNIEXPORT jlong JNICALL Java_io_realm_internal_TableView_nativeGetDateTimeValue(
+JNIEXPORT jlong JNICALL Java_io_realm_internal_TableView_nativeGetTimestamp(
     JNIEnv* env, jobject, jlong nativeViewPtr, jlong columnIndex, jlong rowIndex)
 {
     try {
```
Comment (stk1m1) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: Can we remove `try`/`catch` block?

File: realm/realm-jni/src/io_realm_internal_table.cpp [hunk 7]
```diff
@@ -783,13 +793,16 @@ JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetString(
...
+    JNIEnv* env, jobject, jlong nativeTablePtr, jlong columnIndex, jlong rowIndex, jlong timestampValue)
 {
-    if (!TBL_AND_INDEX_AND_TYPE_VALID(env, TBL(nativeTablePtr), columnIndex, rowIndex, type_DateTime))
+    if (!TBL_AND_INDEX_AND_TYPE_VALID(env, TBL(nativeTablePtr), columnIndex, rowIndex, type_Timestamp))
         return;
     try {
-        TBL(nativeTablePtr)->set_datetime( S(columnIndex), S(rowIndex), dateTimeValue);
+        // FIXME: find more accurate and efficient way to convert msec to (sec, nsec)
+        int64_t seconds = int64_t(timestampValue/1000);
+        uint32_t nanoseconds = uint32_t(1000000*(timestampValue-1000*seconds));
```
Comment (zaki50) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: why convert logic is different from one in `from_milliseconds`?

File: realm/realm-jni/src/io_realm_internal_tableview.cpp [hunk 8]
```diff
@@ -36,7 +36,7 @@ inline bool view_valid_and_in_sync(JNIEnv* env, jlong nativeViewPtr) {
         }
         // depends_on_deleted_linklist() will return true if and only if the current TableView was created from a
         // query on a RealmList and that RealmList was then deleted (as a result of the object being deleted).
-        if (!TV(nativeViewPtr)->is_in_sync() && TV(nativeViewPtr)->depends_on_deleted_linklist()) {
+        if (!TV(nativeViewPtr)->is_in_sync() && TV(nativeViewPtr)->depends_on_deleted_object()) {
```
Comment (bmunkholm) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: Is this change related to timestamp?

File: realm/realm-library/src/main/java/io/realm/internal/Table.java [hunk 9]
```diff
@@ -1237,7 +1237,7 @@ public long findFirstDate(long columnIndex, Date date) {
         if (date == null) {
             throw new IllegalArgumentException("null is not supported");
         }
-        return nativeFindFirstDate(nativePtr, columnIndex, date.getTime() / 1000);
+        return nativeFindFirstTimestamp(nativePtr, columnIndex, date.getTime() / 1000);
```
Comment (bmunkholm) [inline realm/realm-library/src/main/java/io/realm/internal/Table.java]: Shouldn't "/1000" here I assume?

File: realm/realm-jni/src/io_realm_internal_tableview.cpp (hunk 8 above)
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: Did the core API change this method?

File: realm/realm-jni/src/util.hpp [hunk 10]
```diff
@@ -654,6 +655,7 @@ extern jmethodID java_lang_float_init;
 extern jclass java_lang_double;
 extern jmethodID java_lang_double_init;
 
+
```
Comment (cmelchior) [inline realm/realm-jni/src/util.hpp]: Remove newline

File: realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java [hunk 11]
```diff
@@ -560,10 +560,8 @@ private CyclicType createCyclicData() {
 
     @Test
     public void dateType() {
-        long testDatesValid[] = {-1000, 0, 1000};
-        long testDatesLoosePrecision[] = {Long.MIN_VALUE, 1, 1001, Long.MAX_VALUE};
+        long testDatesValid[] = {-1001, -1000, -1, 0, 1, 1000, 1001};
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java]: Why remove the boundary checks? Long.MIN/MAX ?

File: realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java [hunk 12]
```diff
@@ -1827,6 +1827,7 @@ public void isValid_removedParent() {
         list.removeAll(SUPPORTED_IS_EMPTY_TYPES);
         list.remove(RealmFieldType.UNSUPPORTED_MIXED);
         list.remove(RealmFieldType.UNSUPPORTED_TABLE);
+        list.remove(RealmFieldType.UNSUPPORTED_DATE);
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java]: If we are cleaning up the API, it might make sense to remove these from RealmFieldType. Could be done in another PR though.

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java [hunk 13]
```diff
@@ -575,6 +575,7 @@ public void deleteAll() {
      * Deletes the Realm file defined by the given configuration.
      */
     static boolean deleteRealm(final RealmConfiguration configuration) {
+        final String management = ".management";
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: Not related to datetime, but the core upgrade in general?

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java [hunk 14]
```diff
@@ -602,6 +603,28 @@ public void onResult(int count) {
...
+                    for (File fileToDelete : filesToDelete) {
+                        if (fileToDelete.exists()) {
+                            boolean deleteResult = fileToDelete.delete();
+                            if (!deleteResult) {
+                                realmDeleted.set(false);
+                                RealmLog.w("Could not delete the file " + fileToDelete);
+                            }
+                        }
+                    }
+                    boolean deleteResult = managementFolder.delete();
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: This would break apps with multiple Realm files?

File: realm/realm-library/src/main/java/io/realm/RealmFieldType.java [hunk 15]
```diff
@@ -37,7 +37,8 @@
     BINARY(4),
     UNSUPPORTED_TABLE(5),
     UNSUPPORTED_MIXED(6),
-    DATE(7),
+    UNSUPPORTED_DATE(7),
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmFieldType.java]: I would probably just remove this together with other unsupported types. No need to expose them in the public API I think?

File: realm/realm-library/src/main/java/io/realm/internal/Table.java (hunk 9 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/Table.java]: This hasn't been addressed?

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/Table.java]: And more importantly. Why isn't it getting caught in a unit test?

File: realm/realm-library/src/main/java/io/realm/internal/TableView.java [hunk 16]
```diff
@@ -370,7 +370,7 @@ public void setDouble(long columnIndex, long rowIndex, double value){
     @Override
     public void setDate(long columnIndex, long rowIndex, Date value){
         if (parent.isImmutable()) throwImmutable();
-        nativeSetDateTimeValue(nativePtr, columnIndex, rowIndex, value.getTime()/1000);
+        nativeSetTimestampValue(nativePtr, columnIndex, rowIndex, value.getTime()/1000);
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/TableView.java]: We shouldn't divide by 1000 here. No unit test catching this?

File: realm/realm-library/src/main/java/io/realm/internal/TableView.java [hunk 17]
```diff
@@ -493,7 +493,9 @@ public long findFirstDouble(long columnIndex, double value) {
 
     @Override
     public long findFirstDate(long columnIndex, Date date) {
-        return nativeFindFirstDate(nativePtr, columnIndex, date.getTime()/1000);
+        // FIXME: waiting for implementation
+        return NO_MATCH;
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/TableView.java]: Nitpick: Throw UnsupportedOperation instead?

**Comment by cmelchior** [comment]
Done with a quick pass. Generally looks great. Like the internal renaming from Date to Timestamp. I am a bit concerned that some dividing by 1000 hasn't been caught by unit tests, which indicate our test coverage could be better?

File: realm/realm-jni/src/io_realm_internal_tableview.cpp (hunk 8 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: No, but we skipped a few core releases. In principle I agree that it should be in a separate PR but I simply had to push this forward.

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp (hunk 1 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: I had to disable it as I got seg. faults. It has been fixed in core.

File: realm/realm-jni/src/util.hpp (hunk 2 above)
Comment (kneth) [inline realm/realm-jni/src/util.hpp]: I have changed the conversion as the `Timestamp` constructor now supports negative nanoseconds.

File: realm/realm-jni/src/io_realm_internal_table.cpp (hunk 5 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: Indeed so

File: realm/realm-jni/src/io_realm_internal_tableview.cpp (hunk 6 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: Yes, I believe we can. Also for other getters.

File: realm/realm-jni/src/io_realm_internal_table.cpp (hunk 7 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: I have consolidated it by calling `from_milliseconds`.

File: realm/realm-jni/src/io_realm_internal_tableview.cpp (hunk 8 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: @cmelchior Yes, the method has been renamed recently.

File: realm/realm-library/src/main/java/io/realm/internal/Table.java (hunk 9 above)
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/internal/Table.java]: We have a test but I disabled it initially and apparently forgot to reenable it. Nice catch!

File: realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java (hunk 11 above)
Comment (kneth) [inline realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java]: I readd the boundaries.

File: realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java (hunk 12 above)
Comment (kneth) [inline realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java]: `RealmFieldType` is supposed to be in sync with a similar enum in core, so I'm a bit reluctant to remove them.

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java (hunk 13 above)
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: Yes, we skipped a few core releases. Of course I should have fixed with in another PR.

File: realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java (hunk 12 above)
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java]: But it is also a public API. Having exposed types that are not used at all in the binding is a bit weird, no?

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java (hunk 14 above)
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: Oh yes, that's a valid point. But the management folder's name is derived from the Realm file's name and you will only have a collision if two Realms have the same name - and then the two Realms are the same and we only have one :-)

File: realm/realm-library/src/main/java/io/realm/RealmFieldType.java (hunk 15 above)
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/RealmFieldType.java]: As noted above, this enum is kept in sync with a similar enum in core. I rather not removed the three unused/unsupported types.

File: realm/realm-library/src/main/java/io/realm/internal/TableView.java (hunk 17 above)
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/internal/TableView.java]: Because of inheritance

File: realm/realm-library/src/main/java/io/realm/internal/TableView.java (hunk 16 above)
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/internal/TableView.java]: The `TableView` setters are not exposed in our public API, and I'm not sure if they can be called easily.

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java (hunk 14 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: Ah yes. Missed that 👍

**Comment by kneth** [comment]
@cmelchior We should definitely investigate our coverage to see if important methods are not tested. But in the case of the `TableView` setters, the conclusion might be that we should remove them.

**Comment by cmelchior** [comment]
Removing unused setters / getters seems like a good idea. We really shouldn't have unused code. Probably in another PR though.

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp [hunk 18]
```diff
@@ -1523,42 +1521,44 @@ JNIEXPORT jdouble JNICALL Java_io_realm_internal_TableQuery_nativeAverageDouble(
 
 
 // date aggregates
-
-JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMaximumDate(
+// FIXME: This is a rough workaround while waiting for https://github.com/realm/realm-core/issues/1720 to be solved
```
Comment (nhachicha) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: the issue you're pointing to is closed, are we still waiting for Core?

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java [hunk 19]
```diff
@@ -602,6 +603,28 @@ public void onResult(int count) {
...
                     }
                 }
+                File managementFolder = new File(realmFolder, realmFileName + management);
+                if (managementFolder.exists()) {
+                    filesToDelete = Arrays.asList(
+                            new File(managementFolder, realmFileName + ".lock"),
+                            new File(managementFolder, realmFileName + ".log_a"),
+                            new File(managementFolder, realmFileName + ".log_b"),
+                            new File(managementFolder, realmFileName + ".log"));
+                    for (File fileToDelete : filesToDelete) {
```
Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: this logic is duplicated (with the legacy _Realm files_ above) can we have a 
```java
boolean deletes (File rootFolder, String realmFileName) {
// ...
}
```
then we can call it with 
```java
deletes(realmFolder, realmFileName);
```
and 
```java
deletes(managementFolder, realmFileName);
```

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp (hunk 18 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: I'll update the comment to be a link to https://github.com/realm/realm-core/issues/1745

File: realm/realm-jni/build.gradle [hunk 20]
```diff
@@ -201,7 +201,7 @@ task downloadCore(group: 'build setup', description: 'Download the latest versio
                     throw new GradleException("Invalid checksum for file '" +
                             "${project.coreArchiveFile.getName()}'. Expected " +
                             "${project.coreSha256Hash.toLowerCase()} but got " +
-                            "${calculatedHash.toLowerCase()}.");
+                                "${calculatedHash.toLowerCase()}.");
```
Comment (cmelchior) [inline realm/realm-jni/build.gradle]: Wrong indent?

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp (hunk 18 above)
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: Please update the link in the comment ☝️ 😄

File: realm/realm-jni/src/io_realm_internal_TableQuery.cpp [hunk 21]
```diff
@@ -1523,42 +1523,44 @@ JNIEXPORT jdouble JNICALL Java_io_realm_internal_TableQuery_nativeAverageDouble(
...
-        !COL_INDEX_AND_TYPE_VALID(env, pTable, columnIndex, type_DateTime) ||
+        !COL_INDEX_AND_TYPE_VALID(env, pTable, columnIndex, type_Timestamp) ||
         !ROW_INDEXES_VALID(env, pTable, start, end, limit))
         return NULL;
     try {
         size_t return_ndx;
-        DateTime result = pQuery->minimum_int(S(columnIndex), NULL, S(start), S(end), S(limit), &return_ndx);
-        if (return_ndx != npos) {
-            return NewLong(env, result.get_datetime());
+        // FIXME: use Query::minimum_timestamp()
```
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_TableQuery.cpp]: Remove fixme

File: realm/realm-jni/src/io_realm_internal_Util.cpp [hunk 22]
```diff
@@ -78,7 +80,9 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_Util_nativeGetMemUsage(JNIEnv*, j
 JNIEXPORT jstring JNICALL Java_io_realm_internal_Util_nativeGetTablePrefix(
     JNIEnv* env, jclass)
 {
-    return to_jstring(env, string(TABLE_PREFIX));
+    string table_prefix(TABLE_PREFIX);
```
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_Util.cpp]: std:string is used in "internal_version" below. I am not sure we have a consensus on this? But at least being consistent in the same PR would be nice :)

I prefer std::string above string though.

File: realm/realm-jni/src/io_realm_internal_Version.cpp [hunk 23]
```diff
@@ -34,7 +35,9 @@ JNIEXPORT jint JNICALL Java_io_realm_internal_Version_nativeGetAPIVersion(JNIEnv
 JNIEXPORT jstring JNICALL Java_io_realm_internal_Version_nativeGetVersion(JNIEnv *env, jclass)
 {
     try {
-        return to_jstring(env, Version::get_version());
+        std::string str(Version::get_version());
```
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_Version.cpp]: See above

File: realm/realm-jni/src/io_realm_internal_table.cpp [hunk 24]
```diff
@@ -254,6 +259,9 @@ JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeConvertColumnToNullabl
                 case type_Table:
                     // checked previously
                     break;
+                case type_OldDateTime:
+                    // not used
```
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: Throw exception instead? In case someone accidentally uses it?

File: realm/realm-jni/src/io_realm_internal_table.cpp [hunk 25]
```diff
@@ -374,6 +384,9 @@ JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeConvertColumnToNotNull
...
```
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: Same

File: realm/realm-jni/src/io_realm_internal_table.cpp [hunk 26]
```diff
@@ -1285,18 +1299,20 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindAllBool(
     return reinterpret_cast<jlong>(pTableView);
 }
 
-JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindAllDate(
+// FIXME: reenable when find_first_timestamp() is implemented
```
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: This method is still out-commented. Is this not supported yet?

File: realm/realm-jni/src/io_realm_internal_table.cpp [hunk 27]
```diff
@@ -1682,6 +1698,8 @@ JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeMigratePrimaryKeyTable
     const size_t CLASS_COLUMN_INDEX = io_realm_internal_Table_PRIMARY_KEY_CLASS_COLUMN_INDEX;
     const size_t FIELD_COLUMN_INDEX = io_realm_internal_Table_PRIMARY_KEY_FIELD_COLUMN_INDEX;
 
+    const string table_prefix(TABLE_PREFIX);
```
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: std::string

File: realm/realm-jni/src/io_realm_internal_tableview.cpp [hunk 28]
```diff
@@ -204,10 +204,9 @@ JNIEXPORT jstring JNICALL Java_io_realm_internal_TableView_nativeGetColumnName
 JNIEXPORT jlong JNICALL Java_io_realm_internal_TableView_nativeGetColumnIndex
    (JNIEnv *env, jobject, jlong nativeViewPtr, jstring columnName)
 {
-    try {
-        if (!VIEW_VALID_AND_IN_SYNC(env, nativeViewPtr))
+    if (!VIEW_VALID_AND_IN_SYNC(env, nativeViewPtr))
```
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: This change seems at odds with what you wrote below?

File: realm/realm-jni/src/io_realm_internal_tableview.cpp [hunk 29]
```diff
@@ -603,6 +602,8 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_TableView_nativeFindFirstDouble(
     return 0;
 }
 
+// FIXME: find_first_timestamp() isn't implemented
```
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: Not implemented yet? Does it have any impact on the binding?

File: realm/realm-jni/src/io_realm_internal_tableview.cpp [hunk 30]
```diff
@@ -684,6 +686,8 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_TableView_nativeFindAllDouble(
     return 0;
 }
 
+// FIXME: find_all_timestamp() isn't implemented
```
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: Same?

File: realm/realm-jni/src/util.hpp [hunk 31]
```diff
@@ -669,6 +670,24 @@ inline jobject NewFloat(JNIEnv* env, float value)
     return env->NewObject(java_lang_float, java_lang_float_init, value);
 }
 
+inline jlong to_milliseconds(const realm::Timestamp& ts)
+{
+    // From core's reference implementation aka unit test
+    // FIXME: check for overflow
```
Comment (cmelchior) [inline realm/realm-jni/src/util.hpp]: FIXME not addressed

File: realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java [hunk 32]
```diff
@@ -560,10 +560,8 @@ private CyclicType createCyclicData() {
 
     @Test
     public void dateType() {
-        long testDatesValid[] = {-1000, 0, 1000};
-        long testDatesLoosePrecision[] = {Long.MIN_VALUE, 1, 1001, Long.MAX_VALUE};
+        long testDatesValid[] = {Long.MIN_VALUE, -1001, -1000, -1, 0, 1, 1000, 1001, Long.MAX_VALUE};
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java]: 👍

File: realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java [hunk 33]
```diff
@@ -491,12 +490,14 @@ public void avg_partialNullRows() {
 
     @Test
     public void maxDate() {
-        assertEquals(new Date(YEAR_MILLIS * 20 * 4), collection.maxDate(AllJavaTypes.FIELD_DATE));
+        assertEquals(TEST_SIZE, collection.size());
+        assertEquals(new Date(YEAR_MILLIS * 20 * (TEST_SIZE/2 - 1)), collection.maxDate(AllJavaTypes.FIELD_DATE));
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java]: Why did max/min date suddenly change?

File: realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java (hunk 12 above)
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java]: Any comment to this? Maybe just have a list of *all* types inside `RealmFieldType` in a comment, but only expose the supported types?

File: realm/realm-library/src/main/java/io/realm/RealmFieldType.java (hunk 15 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmFieldType.java]: But having them in user facing code serves no purpose. I can see some merit in mirroring the values, but we can just as well do that in Javadoc instead of actual code?

File: realm/realm-library/src/main/java/io/realm/internal/TableOrView.java [hunk 34]
```diff
@@ -328,8 +328,6 @@
 
     TableView findAllDouble(long columnIndex, double value);
 
-    TableView findAllDate(long columnIndex, Date value);
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/internal/TableOrView.java]: Is this because of it not being supported by Core yet or is there some other reason? Perhaps just add a FIXME if it is the first?

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java (hunk 19 above)
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: Good idea!

**Comment by cmelchior** [comment]
Done with review. Mostly minor stuff, but there seems to be a bunch of FIXME's around `find_all_date/find_first_date`. I am not sure we even use those in the public API, so maybe something we should consider removing all together? Don't have to be in this PR though.

File: realm/realm-jni/src/io_realm_internal_table.cpp (hunk 24 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: It should not be possible. All old Realm files are converted, and new Realm will only use `Timestamp`.

File: realm/realm-jni/src/io_realm_internal_Util.cpp (hunk 22 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_Util.cpp]: Removing the `std` name space will probably required that we write `std::size_t` many places.

File: realm/realm-jni/src/io_realm_internal_table.cpp (hunk 24 above)
Comment (cmelchior) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: Then throwing an exception should be safe :) IMO I would much rather we threw exceptions in these cases as it will catch anyone accidentally using them in the future.

File: realm/realm-jni/src/io_realm_internal_table.cpp (hunk 26 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: No, and `find_all_datetime()` was actually a hack.

File: realm/realm-jni/src/io_realm_internal_tableview.cpp (hunk 28 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: Yes, indeed so.

File: realm/realm-jni/src/io_realm_internal_tableview.cpp (hunk 29 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: The impact is that `findFirstDate()` cannot be implemented.

File: realm/realm-jni/src/io_realm_internal_tableview.cpp (hunk 30 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_tableview.cpp]: Yes. but I don't think our public API ever had a `FindAllDate()` on `RealmResults`.

File: realm/realm-jni/src/util.hpp (hunk 31 above)
Comment (kneth) [inline realm/realm-jni/src/util.hpp]: True, it's for dates roughly 400 years in the future.

File: realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java (hunk 33 above)
Comment (kneth) [inline realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java]: It didn't but `4` is assuming a value of `TEST_SIZE` and the test would fail if `TEST_SIZE` was changed. I just made it a bit for robust.

File: realm/realm-library/src/main/java/io/realm/internal/TableOrView.java (hunk 34 above)
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/internal/TableOrView.java]: Yes, it has to be removed as Core doesn't support it. Again, core has never supported it but a clever hack made it possible to trick a non-checking core to perform the operation.

File: realm/realm-jni/src/io_realm_internal_UncheckedRow.cpp [hunk 35]
```diff
@@ -217,7 +217,7 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeGetLinkView
     if (!ROW_VALID(env, ROW(nativeRowPtr)))
         return 0;
 
-    LinkView* link_view_ptr = LangBindHelper::get_linklist_ptr( *ROW( nativeRowPtr ), S( columnIndex) );
+    LinkViewRef* link_view_ptr = const_cast<LinkViewRef*>(&(LangBindHelper::get_linklist_ptr(*ROW(nativeRowPtr), S(columnIndex))));
     return reinterpret_cast<jlong>(link_view_ptr);
```
Comment (AndyDentFree) [inline realm/realm-jni/src/io_realm_internal_UncheckedRow.cpp]: I don't understand how this ends up as a string and there's a lot of casting here. Unless we have a string buried as some kind of opaque type, this looks like a bug, which predates the change to Timestamp.

File: realm/realm-jni/src/io_realm_internal_table.cpp [hunk 36]
```diff
@@ -1384,16 +1400,16 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetSortedView(
...
         case type_Double:
         case type_Float:
+        case type_Timestamp:
             try {
                 TableView* pTableView = new TableView( pTable->get_sorted_view(S(columnIndex), ascending != 0 ? true : false) );
                 return reinterpret_cast<jlong>(pTableView);
             } CATCH_STD()
         default:
-            ThrowException(env, IllegalArgument, "Sort is currently only supported on integer, boolean, double, float, String, and Date columns.");
+            ThrowException(env, IllegalArgument, "Invalid type - Only String, Date, boolean, byte, short, int, long and their boxed variants are supported.");
```
Comment (AndyDentFree) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: Was this deliberately re-worded to be the same as the `FindAllString` exception above or is it a copy-and-paste error? It loses the original's mention of **Sort**.

File: realm/realm-jni/src/io_realm_internal_table.cpp [hunk 37]
```diff
@@ -1433,15 +1449,15 @@ JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetSortedViewMulti(
...
             case type_String:
             case type_Double:
             case type_Float:
+            case type_Timestamp:
                 indices[i] = S(long_arr[i]);
                 ascendings[i] = S(bool_arr[i]);
                 break;
             default:
-                ThrowException(env, IllegalArgument, "Sort is currently only supported on integer, boolean, double, float, String, and Date columns.");
+                ThrowException(env, IllegalArgument, "Invalid type - Only String, Date, byte, boolean, short, int, long and their boxed variants are supported.");
```
Comment (AndyDentFree) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: Same question as on line 1412 above about losing Sort in the message.

File: realm/realm-jni/src/io_realm_internal_table.cpp [hunk 38]
```diff
@@ -1710,9 +1728,11 @@ JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeMigratePrimaryKeyTable
     size_t number_of_rows = pk_table->size();
     for (size_t row_ndx = 0; row_ndx < number_of_rows; row_ndx++) {
         StringData table_name = pk_table->get_string(CLASS_COLUMN_INDEX, row_ndx);
-        if (table_name.begins_with(TABLE_PREFIX)) {
+        if (table_name.begins_with(table_prefix)) {
             // New string copy is needed, since the original memory will be changed.
-            pk_table->set_string(CLASS_COLUMN_INDEX, row_ndx, std::string(table_name.substr(strlen(TABLE_PREFIX))));
+            std::string str(table_name.substr(strlen(TABLE_PREFIX)));
```
Comment (AndyDentFree) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: As we have already copied this into `table_prefix` can use `table_prefix.length()` instead of recalculating `strlen`

File: realm/realm-jni/src/io_realm_internal_Util.cpp (hunk 22 above)
Comment (AndyDentFree) [inline realm/realm-jni/src/io_realm_internal_Util.cpp]: There's a common pattern of creating a stack `std::string table_prefix` to wrap the compile-time constant `TABLE_PREFIX`. Could this be a file-level `static`, or at least locally a `static`, or would you prefer to leave the compiler to optimise that (which I'm a bit doubtful about)?

File: realm/realm-jni/src/io_realm_internal_table.cpp (hunk 24 above)
Comment (bmunkholm) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: If it's not possible - it should assert.

File: realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java (hunk 12 above)
Comment (kneth) [inline realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java]: The trick is that when you add a new type, your IDE will be unhappy in all the `switch` constructors so you remember to update them all.

File: realm/realm-jni/src/io_realm_internal_UncheckedRow.cpp (hunk 35 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_UncheckedRow.cpp]: I am not quite sure what you mean: no strings are involved there. With core 0.100.0, `LangBindHelper::get_linklist_ptr()` has been changed to return a `const LinkViewRef` (a `shared_ptr<LinkView*>`. As we cannot use a `shared_ptr` in Java, I have to store a pointer to `shared_ptr` (returned as a `jlong`). And I need to get rid of the constness too.

That gives us a double indirection which you can see in all the `LinkView` methods.

File: realm/realm-jni/src/io_realm_internal_table.cpp (hunk 36 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: It's not copy-and-paste error but copy-and-paste laziness :-)

File: realm/realm-jni/src/io_realm_internal_table.cpp (hunk 38 above)
Comment (kneth) [inline realm/realm-jni/src/io_realm_internal_table.cpp]: Agree. Using `char*` is probably too much C style these days.

File: realm/realm-jni/src/io_realm_internal_UncheckedRow.cpp (hunk 35 above)
Comment (AndyDentFree) [inline realm/realm-jni/src/io_realm_internal_UncheckedRow.cpp]: Sorry, scratch my comment - I was misinterpreting the github diff as the return type being a jstring - hadn't noticed the line number jump that it was a different method!

**Comment by AndyDentFree** [comment]
👍  preferably with those exception strings fixed to restore the word _sorting_

**Comment by cmelchior** [comment]
👍 , but please create an issue with the overflow problem with dates coming from other platforms. As a minimum we need to document it somewhere instead of hiding it in a FIXME in the code.

**Comment by kneth** [comment]
@cmelchior An exception is thrown (https://github.com/realm/realm-java/pull/2679#discussion_r61776462)

And I have created #2722.

**Comment by cmelchior** [comment]
👍
