### PR TITLE
Using separate interfaces for async transaction also fixes #2130

### LINKED ISSUE #1657: Use interface instead of class for async transaction callback
We have 2 option:
1. Use one interface, users not interested in overriding `onError` or `onSuccess` will create an Adapter 
2. Use 2 interfaces, one for each callback + overload `executeTransaction` to take onSuccess/onError or both this will enable nice lambda syntax

### LINKED ISSUE #2130: Exceptions during async transactions are failing silently
So I've ran into a very frustrating error. Exceptions during asynchronous transactions aren't getting reported. No signs of stacktrace. 

This made me spend a couple of hours trying to figure out why my logic isn't working only to realize that Realm has stopped printing Error stacktraces.

##### Steps to reproduce
Simply throw an `Error` inside a transaction.

##### Example code

````java
private void testRealm() {

    final Realm.Transaction.Callback callback = new Realm.Transaction.Callback() {

        @Override
        public void onSuccess() {
            super.onSuccess();
        }

        @Override
        public void onError(Exception e) {
            super.onError(e);
            e.printStackTrace();
        }

    };

    getRealm().executeTransaction(realm -> {
        throw new IllegalAccessError("Poop");
    }, callback);

}
````
The stacktrace never gets printed.

**Realm version**: 0.87.2

Any ideas how do i fix this?

### PR DESCRIPTION
**Pull request by nhachicha**
Fixes #1657 
Fixes #2130

### CODE REVIEW

**Comment by nhachicha** [comment]
@realm/java

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 1]
```diff
@@ -1070,17 +1069,59 @@ public void executeTransaction(Transaction transaction) {
      * Similar to {@link #executeTransaction(Transaction)} but runs asynchronously from a worker thread.
      *
      * @param transaction {@link io.realm.Realm.Transaction} to execute.
-     * @param callback optional, to receive the result of this query.
      * @return a {@link RealmAsyncTask} representing a cancellable task.
      * @throws IllegalArgumentException if the {@code transaction} is {@code null}, or if the realm is opened from another thread.
      */
-    public RealmAsyncTask executeTransaction(final Transaction transaction, final Transaction.Callback callback) {
```
Comment (dalinaum) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Should we delete `executeTransaction`? Is the fallback interface not needed?

Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: I'm not following you `executeTransaction` is the sync call

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: To follow our normal deprecation policies we would need to deprecate this for 2 releases instead of removing it outright.

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 2]
```diff
@@ -81,24 +81,89 @@ public void setUp() throws Exception {
...
+    @RunTestInLooperThread
+    public void executeTransaction_async_onError() throws Throwable {
+        assertEquals(0, looperThread.realm.allObjects(Owner.class).size());
+
+        looperThread.realm.executeTransactionAsync(new Realm.Transaction() {
+            @Override
+            public void execute(Realm realm) {
+                Owner owner = realm.createObject(Owner.class);
+                owner.setName("Owner");
+                realm.beginTransaction(); //Nested transaction should throw IllegalStateException
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: Maybe more clear to just throw a RuntimeException or similar?

**Comment by cmelchior** [comment]
Looks good :+1:  but we need to mark the old approach as deprecated instead of deleting it outright. At least if we want to follow normal deprecation policies (which seems possible in this case).
But talk to @dalinaum about #1893 because I think you might be stepping on each other toes.

**Comment by zaki50** [comment]
need an entry in changelog

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 3]
```diff
@@ -1070,17 +1069,59 @@ public void executeTransaction(Transaction transaction) {
...
+    public RealmAsyncTask executeTransactionAsync(final Transaction transaction) {
+        return executeTransactionAsync(transaction, null, null);
+    }
+
+    /**
+     * Similar to {@link #executeTransactionAsync(Transaction)}.
+     *
+     * @param transaction {@link io.realm.Realm.Transaction} to execute.
+     * @param onSuccess callback invoked when the transaction succeed.
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: succeed -> succeeds

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 4]
```diff
@@ -81,24 +81,89 @@ public void setUp() throws Exception {
...
                 looperThread.testComplete();
             }
+        }, new Realm.Transaction.OnError() {
 
             @Override
-            public void onError(Exception e) {
-                looperThread.testComplete();;
-                fail(e.getMessage());
+            public void onError(Throwable error) {
+                looperThread.testComplete();
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: `looperThread.testComplete();` should be removed. `fail` will just trigger a throw.

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 5]
```diff
@@ -81,24 +81,89 @@ public void setUp() throws Exception {
...
+            @Override
+            public void execute(Realm realm) {
+                Owner owner = realm.createObject(Owner.class);
+                owner.setName("Owner");
+                looperThread.realm.handler.postDelayed(new Runnable() {
+                    @Override
+                    public void run() {
+                        looperThread.testComplete();
+                    }
+                }, 16);
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: Hope 16 ms is long enough XD

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 6]
```diff
@@ -223,7 +288,7 @@ public void execute(Realm realm) {
     @RunTestInLooperThread
     public void executeTransaction_async_realmClosedOnError() {
         final AtomicInteger counter = new AtomicInteger(100);
-        final Realm realm = Realm.getInstance(looperThread.createConfiguration("testClosedBeforeAsyncTransactionSuccess"));
+        final Realm realm = Realm.getInstance(looperThread.createConfiguration("executeTransaction_async_realmClosedOnError"));
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: No need to create a specific named Realm anymore, just use `looperThread.realm`?

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 7]
```diff
@@ -1070,17 +1069,59 @@ public void executeTransaction(Transaction transaction) {
...
+     */
+    public RealmAsyncTask executeTransactionAsync(final Transaction transaction, final Realm.Transaction.OnSuccess onSuccess, final Realm.Transaction.OnError onError) {
         if (transaction == null)
             throw new IllegalArgumentException("Transaction should not be null");
 
         // If the user provided a Callback then we make sure, the current Realm has a Handler
         // we can use to deliver the result
-        if (callback != null && handler == null) {
+        if ((onSuccess != null || onError != null)  && handler == null) {
             throw new IllegalStateException("Your Realm is opened from a thread without a Looper" +
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: "Your Realm is opened from a thread without a Looper" - > "Your Realm is opened from a thread without a Looper or it has already been closed"

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 8]
```diff
@@ -1128,23 +1169,22 @@ public void run() {
...
                                 @Override
                                 public void run() {
-                                    callback.onSuccess();
+                                    onSuccess.onSuccess();
                                 }
                             });
-                        } else if (exception[0] != null) {
-                            // transaction has not been canceled by there is a exception during transaction.
+                        }
+                        if (onError != null && exception[0] != null) {
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: If there is an exception, and user doesn't supply a `onError`, I think we should just throw.

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Good catch. Yeah, throwing is :+1:

**Comment by nhachicha** [comment]
@realm/java

**Comment by kneth** [comment]
Looks fine!

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java (hunk 4 above)
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: This hasn't been addressed?

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 9]
```diff
@@ -81,24 +81,86 @@ public void setUp() throws Exception {
...
+
+    @RunTestInLooperThread
+    public void executeTransaction_async_onError() throws Throwable {
+        assertEquals(0, looperThread.realm.allObjects(Owner.class).size());
+
+        looperThread.realm.executeTransactionAsync(new Realm.Transaction() {
+            @Override
+            public void execute(Realm realm) {
+                throw new RuntimeException("Oh! What a Terrible Failure");
+
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: Remove whitespace

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java (hunk 6 above)
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: This hasn't been addressed.

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 10]
```diff
@@ -1082,7 +1083,7 @@ public RealmAsyncTask executeTransaction(final Transaction transaction, final Tr
         // we can use to deliver the result
         if (callback != null && handler == null) {
             throw new IllegalStateException("Your Realm is opened from a thread without a Looper" +
-                    " and you provided a callback, we need a Handler to invoke your callback");
+                    " (or it has already been closed) and you provided a callback, we need a Handler to invoke your callback");
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Any reason or changing this when it is deprecated?
Also wouldn't it make more sense to check for `realm.isValid()` instead of doing this?

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 11]
```diff
@@ -1157,6 +1158,147 @@ public void run() {
     }
 
     /**
+     * Similar to {@link #executeTransaction(Transaction)} but runs asynchronously from a worker thread.
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: from -> on?

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 12]
```diff
@@ -1157,6 +1158,147 @@ public void run() {
...
+    /**
+     * Similar to {@link #executeTransactionAsync(Transaction)}.
+     *
+     * @param transaction {@link io.realm.Realm.Transaction} to execute.
+     * @param onSuccess callback invoked when the transaction succeeds.
+     * @return a {@link RealmAsyncTask} representing a cancellable task.
+     * @throws IllegalArgumentException if the {@code transaction} is {@code null}, or if the realm is opened from another thread.
+     */
+    public RealmAsyncTask executeTransactionAsync(final Transaction transaction, final Realm.Transaction.OnSuccess onSuccess) {
+        if (onSuccess == null)
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Missing `{}`

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 13]
```diff
@@ -1157,6 +1158,147 @@ public void run() {
...
+    /**
+     * Similar to {@link #executeTransactionAsync(Transaction)}.
+     *
+     * @param transaction {@link io.realm.Realm.Transaction} to execute.
+     * @param onError callback invoked when the transaction failed.
+     * @return a {@link RealmAsyncTask} representing a cancellable task.
+     * @throws IllegalArgumentException if the {@code transaction} is {@code null}, or if the realm is opened from another thread.
+     */
+    public RealmAsyncTask executeTransactionAsync(final Transaction transaction, final Realm.Transaction.OnError onError) {
+        if (onError == null)
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Same

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 14]
```diff
@@ -1157,6 +1158,147 @@ public void run() {
...
+     */
+    public RealmAsyncTask executeTransactionAsync(final Transaction transaction, final Realm.Transaction.OnSuccess onSuccess) {
+        if (onSuccess == null)
+            throw new IllegalArgumentException("onSuccess callback can't be null");
+
+        return executeTransactionAsync(transaction, onSuccess, null);
+    }
+
+    /**
+     * Similar to {@link #executeTransactionAsync(Transaction)}.
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: This description is a bit funny to me, either add `, but also accepts an OnError handler` or perhaps just write the full description? It does lead to documentation being copied, but that is IMO OK as you want the documentation as local as possible.

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 15]
```diff
@@ -1157,6 +1158,147 @@ public void run() {
...
+     */
+    public RealmAsyncTask executeTransactionAsync(final Transaction transaction, final Realm.Transaction.OnError onError) {
+        if (onError == null)
+            throw new IllegalArgumentException("onError callback can't be null");
+
+        return executeTransactionAsync(transaction, null, onError);
+    }
+
+    /**
+     * Similar to {@link #executeTransactionAsync(Transaction)}.
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Same

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 16]
```diff
@@ -1157,6 +1158,147 @@ public void run() {
...
+     *
+     * @param transaction {@link io.realm.Realm.Transaction} to execute.
+     * @param onSuccess callback invoked when the transaction succeeds.
+     * @param onError callback invoked when the transaction failed.
+     * @return a {@link RealmAsyncTask} representing a cancellable task.
+     * @throws IllegalArgumentException if the {@code transaction} is {@code null}, or if the realm is opened from another thread.
+     */
+    public RealmAsyncTask executeTransactionAsync(final Transaction transaction, final Realm.Transaction.OnSuccess onSuccess, final Realm.Transaction.OnError onError) {
+        if (transaction == null)
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Bracers missing

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 17]
```diff
@@ -1157,6 +1158,147 @@ public void run() {
...
+            throw new IllegalArgumentException("Transaction should not be null");
+
+        // If the user provided a Callback then we make sure, the current Realm has a Handler
+        // we can use to deliver the result
+        if ((onSuccess != null || onError != null)  && handler == null) {
+            throw new IllegalStateException("Your Realm is opened from a thread without a Looper" +
+                    " (or it has already been closed) and you provided a callback, we need a Handler to invoke your callback");
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Why not check for `realm.isValid` instead of adding the description in `()`?

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 18]
```diff
@@ -1157,6 +1158,147 @@ public void run() {
...
+                            && handler.getLooper().getThread().isAlive()) {
+                        if (onSuccess != null && transactionCommitted) {
+                            handler.post(new Runnable() {
+                                @Override
+                                public void run() {
+                                    onSuccess.onSuccess();
+                                }
+                            });
+                        }
+                        if (exception[0] != null) {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: This could be pulled into its own variable. Will make the below code more readable.

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 19]
```diff
@@ -1326,5 +1468,21 @@ public static Object getDefaultModule() {
...
+        /**
+         * Callback invoked to notify the caller thread about the success of the transaction.
+         */
+        interface OnSuccess {
+            void onSuccess();
+        }
+
+        /**
+         * Callback invoked to notify the caller thread about error during the transaction.
+         * The transaction will be rolled back and the background Real will be closed before
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Real -> Realm

**Comment by cmelchior** [comment]
Done, mostly minor stuff, but there where also a few comments left unaddressed from last round.

**Comment by nhachicha** [comment]
updated PR

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 20]
```diff
@@ -81,24 +81,84 @@ public void setUp() throws Exception {
...
+            @Override
+            public void onSuccess() {
+                assertEquals(1, looperThread.realm.allObjects(Owner.class).size());
+                assertEquals("Owner", looperThread.realm.where(Owner.class).findFirst().getName());
+                looperThread.testComplete();
+            }
+        });
+    }
+
+    @RunTestInLooperThread
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: `@Test` is missing.

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 21]
```diff
@@ -81,24 +81,84 @@ public void setUp() throws Exception {
...
-                fail(e.getMessage());
+            public void onError(Throwable error) {
+                fail(error.getMessage());
+            }
+        });
+    }
+
+    @Test
+    @RunTestInLooperThread
+    public void executeTransaction_async_onSuccess() throws Throwable {
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: better to name it as `executeTransactionAsync_onSuccess` ?

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 22]
```diff
@@ -81,24 +81,84 @@ public void setUp() throws Exception {
...
+            public void onSuccess() {
+                assertEquals(1, looperThread.realm.allObjects(Owner.class).size());
+                assertEquals("Owner", looperThread.realm.where(Owner.class).findFirst().getName());
+                looperThread.testComplete();
+            }
+        });
+    }
+
+    @RunTestInLooperThread
+    public void executeTransaction_async_onError() throws Throwable {
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: `executeTransactionAsync_onSuccess`

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 23]
```diff
@@ -81,24 +81,84 @@ public void setUp() throws Exception {
...
+                assertEquals(0, looperThread.realm.allObjects(Owner.class).size());
+                assertNull(looperThread.realm.where(Owner.class).findFirst());
+                looperThread.testComplete();
+            }
+        });
+    }
+
+    @Test
+    @RunTestInLooperThread
+    public void executeTransaction_async_NoCallbacks() throws Throwable {
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: `executeTransactionAsync_NoCallbacks`

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 24]
```diff
@@ -1157,6 +1160,153 @@ public void run() {
...
+    /**
+     * Similar to {@link #executeTransactionAsync(Transaction)}, but also accepts an OnSuccess callback.
+     *
+     * @param transaction {@link io.realm.Realm.Transaction} to execute.
+     * @param onSuccess callback invoked when the transaction succeeds.
+     * @return a {@link RealmAsyncTask} representing a cancellable task.
+     * @throws IllegalArgumentException if the {@code transaction} is {@code null}, or if the realm is opened from another thread.
+     */
+    public RealmAsyncTask executeTransactionAsync(final Transaction transaction, final Realm.Transaction.OnSuccess onSuccess) {
+        if (onSuccess == null){
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: space between `){`

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 25]
```diff
@@ -1157,6 +1160,153 @@ public void run() {
...
+                        if (backgroundException != null) {
+                            if (onError != null) {
+                                handler.post(new Runnable() {
+                                    @Override
+                                    public void run() {
+                                        onError.onError(backgroundException);
+                                    }
+                                });
+                            } else {
+                                handler.post(new Runnable() {
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Should it just throw in the worker thread? And need a test case for this.

File: realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java [hunk 26]
```diff
@@ -78,34 +78,95 @@ public void setUp() throws Exception {
...
+            @Override
+            public void execute(Realm realm) {
+                Owner owner = realm.createObject(Owner.class);
+                owner.setName("Owner");
+            }
+        });
+        looperThread.realm.addChangeListener(new RealmChangeListener() {
+            @Override
+            public void onChange() {
+                looperThread.testComplete();
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java]: Should you verify that 1 owner object exists here?

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 27]
```diff
@@ -1157,6 +1160,160 @@ public void run() {
...
+                                    @Override
+                                    public void run() {
+                                        throw new RuntimeException(backgroundException);
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: We shouldn't wrap exceptions in `RuntimeException` you might convert `Error` to a `RuntimeException`?

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 28]
```diff
@@ -1157,6 +1160,160 @@ public void run() {
...
+                                    }
+                                });
+                            }
+                        }
+                    } else {
+                        // Throw exception in the worker thread if the caller thread terminated
+                        if (backgroundException != null) {
+                            //noinspection ThrowFromFinallyBlock
+                            throw new RuntimeException(backgroundException);
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: Same. Why convert to RuntimeException?

File: realm/realm-library/src/main/java/io/realm/Realm.java (hunk 25 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: There isn't any difference between this and triggering the error callback above right? I guess that technically you can quit a looper thread before it finished receiving all events, but by that assumption we couldn't propagate any errors. I would probably say that chance of this happening is so little, and it would be against the contract you agreed to when doing it async, so basically "it is your own fault"?

**Comment by cmelchior** [comment]
Just discovered that we convert exceptions to RuntimeExceptions which looks like a bad idea? Apart from that :+1:

**Comment by nhachicha** [comment]
@realm/java

**Comment by kneth** [comment]
That's a lot of conditions to keep track of - but it looks just fine to me :smile:

**Comment by cmelchior** [comment]
:+1: Once master has been merged into this :)

**Comment by nhachicha** [comment]
squashed
