### PR TITLE
Fix isLoaded JavaDoc

### LINKED ISSUE #3200: isLoaded() seems to be returning an incorrect value.
I have created a project to replicate the issue I am having. [https://github.com/chrisolsen/realm-issue](https://github.com/chrisolsen/realm-issue)

In the `onChange` listener the RealmObject's `isLoaded()` method is returning a true value, but when I then try to bind the data an IllegalStateException is thrown telling me that I should first check it is loaded.

If you run the linked android project the bug will only be seen on the first launch, after that a row will exist in the db thereby avoiding the issue.

#### Expected Results

`isLoaded` should initially return false, until the IntentService inserts the data.

#### Actual Results

`isLoaded()` returns `true` before any data exists in the db, causing a crash

```
07-20 10:14:46.833 5112-5112/com.example.chris.test D/User null?: no
07-20 10:14:46.833 5112-5112/com.example.chris.test D/User loaded?: true
07-20 10:14:46.836 5112-5262/com.example.chris.test D/onHandleIntent: in the service
07-20 10:14:46.863 5112-5112/com.example.chris.test D/AndroidRuntime: Shutting down VM


                                                                      --------- beginning of crash
07-20 10:14:46.863 5112-5112/com.example.chris.test E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.example.chris.test, PID: 5112
                                                                      java.lang.IllegalStateException: Can't access a row that hasn't been loaded, make sure the instance is loaded by calling RealmObject.isLoaded().
                                                                          at io.realm.internal.Row$1.getString(Row.java:176)
                                                                          at io.realm.UserRealmProxy.realmGet$name(UserRealmProxy.java:60)
                                                                          at com.example.chris.test.UserData.getName(UserData.java:11)
                                                                          at com.example.chris.test.databinding.ActivityMainBinding.executeBindings(ActivityMainBinding.java:96)
                                                                          at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:355)
                                                                          at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:172)
                                                                          at android.databinding.ViewDataBinding$7.doFrame(ViewDataBinding.java:238)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

#### Steps & Code to Reproduce

Run the linked app. The first time the app is run the above crash will occur, after that the app will work as intended.

#### Code Sample

See [https://github.com/chrisolsen/realm-issue](https://github.com/chrisolsen/realm-issue)

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: Nexus5 emulator (android 6.0), Nexus 7 device (android 6.0)

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #3200 

The exception message when accessing 'null' object fields where a bit misleading. Exception + Javadoc have been updated.

@realm/java 
@beeender

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 1]
```diff
@@ -150,25 +150,82 @@ public final boolean isValid() {
     }
 
     /**
-     * Determines if the current RealmObject is obtained synchronously or asynchronously (from a worker thread).
+     * Checks if the query used to find this RealmObject has completed.
+     *
+     * Objects created from async methods like {@link RealmQuery#findFirstAsync()} return a
+     * dummy object that represent the future result of the {@link RealmQuery}. It can be considered
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: represent -> represents

File: realm/realm-library/src/main/java/io/realm/internal/Row.java [hunk 2]
```diff
@@ -113,8 +113,8 @@
     boolean hasColumn(String fieldName);
 
     Row EMPTY_ROW = new Row() {
-        private final static String UNLOADED_ROW_MESSAGE = "Can't access a row that hasn't been loaded, make sure the instance" +
-                " is loaded by calling RealmObject.isLoaded().";
+        private final static String UNLOADED_ROW_MESSAGE = "Can't access a row that hasn't been loaded or represents 'null', " +
+                "make sure the instance is loaded and valid by calling RealmObject.isLoaded() && RealmObject.isValid().";
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/internal/Row.java]: quote for the function name :)

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 3]
```diff
@@ -150,25 +150,82 @@ public final boolean isValid() {
...
+     * similar to a {@link java.util.concurrent.Future} in this regard.
+     *
+     * Once this method returns {@code true}, this object represents the query result even if the query
+     * didn't find any object matching the query parameters. In this case the RealmObject will
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: RealmObject -> {@link RealmObject}

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 4]
```diff
@@ -150,25 +150,82 @@ public final boolean isValid() {
...
+     * become a "null" object.
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: "null" -> "{@code null}

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 5]
```diff
@@ -150,25 +150,82 @@ public final boolean isValid() {
...
+     * "Null" objects will throw if any accessor is called, so it is important to also check {@link #isValid()}
+     * before calling any methods. A common pattern is this:
+     *
+     * <pre>
+     * {@code
+     * Person person = realm.where(Person.class).findFirstAsync();
+     * person.addChangeListener(new RealmChangeListener() {
+     *      @Override
+     *      public void onChange(Person person) {
+     *          if (person.isLoaded() && person.isValid()) {
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: When the listener is called, `isLoaded()` will always return `true`. I cannot figure out a case it returns `false` here.

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: Your right. I should just remove that. `isLoaded()` is more useful for RxJava support where the unloaded object is also emitted.

Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: But maybe it is good to have it in the example since user might reuse the same listener on different object?

File: realm/realm-library/src/main/java/io/realm/RealmObject.java (hunk 4 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: Empty object could also work, neither the term "null object" nor "empty object" is really well-defined, but at least "null" is a concept that is familiar to people. "empty" could mean a lot of things I think...

File: realm/realm-library/src/main/java/io/realm/RealmObject.java (hunk 5 above)
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: Shouldn't matter though. Even if you re-use the listener, it will only be called with a loaded object. `isLoaded()` is only really useful outside the listener.

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 6]
```diff
@@ -150,25 +150,82 @@ public final boolean isValid() {
...
+     *      @Override
+     *      public void onChange(Person person) {
+     *          if (RealmObject.isLoaded(person) && RealmObject.isValid(person)) {
+     *              // It is safe to access the person.
+     *          }
+     *      }
+     * });
+     * }
+     * </pre>
+     *
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: dup the same text is annoy especially in the same file  ... but well ...

**Comment by beeender** [comment]
:+1: with a few comments.

**Comment by stk1m1** [comment]
👍

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 7]
```diff
@@ -150,25 +150,86 @@ public final boolean isValid() {
     }
 
     /**
-     * Determines if the current RealmObject is obtained synchronously or asynchronously (from a worker thread).
+     * Checks if the query used to find this RealmObject has completed.
+     *
+     * Objects created from async methods like {@link RealmQuery#findFirstAsync()} return a
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: Can an object return a dummy object? Consider to delete "Objects created from".

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 8]
```diff
@@ -150,25 +150,86 @@ public final boolean isValid() {
...
+     * dummy object that represents the future result of the {@link RealmQuery}. It can be considered
+     * similar to a {@link java.util.concurrent.Future} in this regard.
+     *
+     * Once this method returns {@code true}, this object represents the query result even if the query
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: "this method": which method are we talking about? The async method?

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 9]
```diff
@@ -150,25 +150,86 @@ public final boolean isValid() {
...
+     * didn't find any object matching the query parameters. In this case the {@link RealmObject} will
+     * become a "null" object.
+     *
+     * "Null" objects represents {@code null} and will throw if any accessor is called, so it is important
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: "will throw": the object doesn't throw. Maybe:

"Null" objects represent {@code null}. An exception is throw if any accessor is called ..."

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 10]
```diff
@@ -150,25 +150,86 @@ public final boolean isValid() {
...
+     * to also check {@link #isValid()} before calling any methods. A common pattern is this:
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: Remove "this"

File: realm/realm-library/src/main/java/io/realm/RealmObject.java [hunk 11]
```diff
@@ -150,25 +150,86 @@ public final boolean isValid() {
...
+     *              // It is safe to access the person.
+     *          }
+     *      }
+     * });
+     * }
+     * </pre>
+     *
      * Synchronous RealmObjects are by definition blocking hence this method will always return {@code true} for them.
-     * This will return {@code true} if called for an unmanaged object (created outside of Realm).
+     * This method will also return {@code true} if called on an unmanaged object (created outside of Realm).
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/RealmObject.java]: Remove "also" - it sounds like the method can return multiple values.

File: realm/realm-library/src/main/java/io/realm/internal/Row.java [hunk 12]
```diff
@@ -113,8 +113,8 @@
     boolean hasColumn(String fieldName);
 
     Row EMPTY_ROW = new Row() {
-        private final static String UNLOADED_ROW_MESSAGE = "Can't access a row that hasn't been loaded, make sure the instance" +
-                " is loaded by calling RealmObject.isLoaded().";
+        private final static String UNLOADED_ROW_MESSAGE = "Can't access a row that hasn't been loaded or represents 'null', " +
+                "make sure the instance is loaded and valid by calling 'RealmObject.isLoaded() && RealmObject.isValid()'.";
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/internal/Row.java]: "valid" -> "is valid"

**Comment by cmelchior** [comment]
Updated @kneth

**Comment by kneth** [comment]
:+1:
