### PR TITLE
IllegalArgumentException when calling copyFromRealm(dynamicRealmObject)

### LINKED ISSUE #2058: Calling copyFromRealm with a list of DynamicRealmObject should throw
Throw a meaningful exception when calling `realm.copyFromRealm(List<DynamicRealmObject)`

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #2058

It should not be possible to call `Realm.copyFromRealm()` with DynamicRealmObject. Right now it crashes with a weird schema exception "cannot find RealmObject".

@realm/java

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/Realm.java [hunk 1]
```diff
@@ -1196,6 +1198,9 @@ private void checkMaxDepth(int maxDepth) {
         if (!realmObject.isValid()) {
             throw new IllegalArgumentException("RealmObject is not valid, so it cannot be copied.");
         }
+        if (realmObject instanceof DynamicRealmObject) {
+            throw new IllegalArgumentException("DynamicRealmObjects cannot be copied from Realm");
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/Realm.java]: missing `.` at the end of exception message.
`DynamicRealmObjects` -> `DynamicRealmObject`

File: realm/realm-library/src/androidTest/java/io/realm/RealmTest.java [hunk 2]
```diff
@@ -2641,6 +2641,37 @@ public void testCopyListFromRealmSameElements() {
...
+        try {
+            testRealm.copyFromRealm(dObj);
+            fail();
+        } catch (IllegalArgumentException ignored) {
+        }
+    }
+
+    @Test
+    public void testCopyFromRealmDynamicRealmListThrows() {
+        DynamicRealm dynamicRealm = DynamicRealm.getInstance(testRealm.getConfiguration());
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmTest.java]: Does this test pass?

**Comment by cmelchior** [comment]
Yes but Findbugs was unhappy:
```
> FindBugs rule violations were found. See the report at: file:///home/jenkins/jenkins/workspace/java_pr/realm/realm-library/build/findbugs/findbugs-output.html
```

File: changelog.txt [hunk 3]
```diff
@@ -1,3 +1,6 @@
+0.87.3
+ * A proper IllegalArgumentException is now thrown when calling Realm.copyFromRealm() with a DynamicRealmObject (#2058).
```
Comment (kneth) [inline changelog.txt]: "A proper" -> ""

**Comment by cmelchior** [comment]
retest this please

**Comment by cmelchior** [comment]
retest this please

File: realm/realm-library/src/androidTest/java/io/realm/RealmTest.java (hunk 2 above)
Comment (zaki50) [inline realm/realm-library/src/androidTest/java/io/realm/RealmTest.java]: @beeender passes on my local device.

Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmTest.java]: My bad, I misunderstood the code.

**Comment by beeender** [comment]
:+1:

**Comment by cmelchior** [comment]
Bump @realm/java

**Comment by kneth** [comment]
:+1:
