### PR TITLE
Accept null RealmResults for RealmBaseAdapter. refs #1086

### LINKED ISSUE #1086: RealmBaseAdapter with null RealmResults
Can you please handle null `realmResults` within `RealmBaseAdapter`? If the adapter has no content at all, and `RealmQuery` possibly returns `null` too, it doesn't make sense for `RealmBaseAdapter` to not accepting `null`.

Example:

    RealmResults<MyObject> results = realm.where("...").find(); // it's possible the result is null
    MyRealmAdapter adapter = new MyRealmAdapter(context, results); // if results is null, you get exception
    // if I catch the exception, then adapter is null
    // I couldn't do this
    spinner.setAdapter(adapter);
    // or
    adapter.updateRealmResults(notNullRealmResults);

### PR DESCRIPTION
**Pull request by zaki50**
Fixes #1086

### CODE REVIEW

**Comment by zaki50** [comment]
Should we skip unnecessary listener update in updateRealmResults for better performance if target Realm instance is not changed?

File: realm/src/main/java/io/realm/RealmBaseAdapter.java [hunk 1]
```diff
@@ -89,7 +94,20 @@ public long getItemId(int i) {
...
+            }
+            if (realmResults != null) {
+                realmResults.getRealm().addChangeListener(listener);
+            }
+        }
+
         this.realmResults = realmResults;
-        notifyDataSetChanged();
+        if (this.realmResults == null) {
+            notifyDataSetInvalidated();
```
Comment (cmelchior) [inline realm/src/main/java/io/realm/RealmBaseAdapter.java]: I am not sure that calling this here would be correct. JavaDoc says that once this has been called the adapter should not be used anymore, which is not correct in this case, it could become "valid" again by just updating the results agains.

File: realm/src/main/java/io/realm/RealmBaseAdapter.java [hunk 2]
```diff
@@ -89,7 +94,20 @@ public long getItemId(int i) {
      * @param realmResults the new RealmResults coming from the new query.
      */
     public void updateRealmResults(RealmResults<T> realmResults) {
+        if (listener != null) {
```
Comment (cmelchior) [inline realm/src/main/java/io/realm/RealmBaseAdapter.java]: This section could use a comment along the lines of "Making sure that Adapter is refreshed correctly if new RealmResults come from another Realm"

File: realm/src/main/java/io/realm/RealmBaseAdapter.java [hunk 3]
```diff
@@ -89,7 +94,20 @@ public long getItemId(int i) {
...
+            if (this.realmResults != null) {
+                this.realmResults.getRealm().removeChangeListener(listener);
+            }
+            if (realmResults != null) {
```
Comment (cmelchior) [inline realm/src/main/java/io/realm/RealmBaseAdapter.java]: Using both ```this.realmResults``` and ```realmResults``` is a bit confusing to read. A different name for the method variable would increase readability. Perhaps just "results" or "queryResults"?

File: realm/src/main/java/io/realm/RealmBaseAdapter.java (hunk 1 above)
Comment (zaki50) [inline realm/src/main/java/io/realm/RealmBaseAdapter.java]: You are right.
I'll update my PR.

**Comment by cmelchior** [comment]
Hi @zaki50 
Thank you very much. I only had minor comments. You are allowing the adapter to be updated with data from another Realm, but I guess it is OK.

Also please update the changelog.

**Comment by cmelchior** [comment]
You are right that the ChangeListener currently gets triggered on any change, which is not very optimal. We are working on more fine-grained notifications, so until they are implemented I don't think we should handle it in this class.

File: realm/src/main/java/io/realm/RealmBaseAdapter.java (hunk 3 above)
Comment (zaki50) [inline realm/src/main/java/io/realm/RealmBaseAdapter.java]: You mean parameter name of this method should be changed?

Comment (cmelchior) [inline realm/src/main/java/io/realm/RealmBaseAdapter.java]: Yes

**Comment by cmelchior** [comment]
Looks good now :+1: 

@emanuelez @kneth Do you have any comments?

**Comment by emanuelez** [comment]
It looks very good. My only comment is purely about coding style: the empty lines in the unit tests.
Great job @zaki50! And thank you for your contribution.

File: realm/src/main/java/io/realm/RealmBaseAdapter.java [hunk 4]
```diff
@@ -86,10 +91,20 @@ public long getItemId(int i) {
...
      * If the query does not change you might consider using the automaticUpdate feature
      *
-     * @param realmResults the new RealmResults coming from the new query.
+     * @param queryResults the new RealmResults coming from the new query.
      */
-    public void updateRealmResults(RealmResults<T> realmResults) {
-        this.realmResults = realmResults;
+    public void updateRealmResults(RealmResults<T> queryResults) {
+        if (listener != null) {
+            // Making sure that Adapter is refreshed correctly if new RealmResults come from another Realm
```
Comment (kneth) [inline realm/src/main/java/io/realm/RealmBaseAdapter.java]: I think you should write "another Realm instance" as "another Realm" make it sounds like it can come from another Realm file.

**Comment by kneth** [comment]
Besides my little comment on a comment, it looks fine to me.

:+1:

File: realm/src/main/java/io/realm/RealmBaseAdapter.java (hunk 4 above)
Comment (cmelchior) [inline realm/src/main/java/io/realm/RealmBaseAdapter.java]: Actually it can, which is why it is necessary to add and remove the listener ;)

**Comment by cmelchior** [comment]
Hi @zaki50 
If you just remove the empty lines in your unit tests, this will be ready to merge.

**Comment by zaki50** [comment]
@cmelchior I removed empty lines and rebased against master branch.

**Comment by cmelchior** [comment]
Thanks a lot @zaki50. It has been merged.
