### PR TITLE
Better exception message if non model class is provided

### LINKED ISSUE #5779: Better error when calling where with RealmModel
In Kotlin I sometimes end up in a situation where a type that I pass to `where` is treated as a `RealmModel` instead of a `RealmModel` subclass, but it's not always obvious from looking at the code. The problem is `where` eventually calls `Util.getOriginalModelClass` which get a superclass of null, causing a runtime NPE exception (`superclass.equals` because superclass is null).

It would be nice if there was a more informative message so that I could tell what was happening right away.

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #5779

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/internal/Util.java [hunk 1]
```diff
@@ -47,6 +47,14 @@ public static String getTablePrefix() {
      * was a RealmProxy class.
      */
     public static Class<? extends RealmModel> getOriginalModelClass(Class<? extends RealmModel> clazz) {
+
+        // The compiler would allow these classes to be parsed as arguments, but they are never
```
Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/internal/Util.java]: to be passed

File: realm/realm-library/src/main/java/io/realm/internal/Util.java [hunk 2]
```diff
@@ -47,6 +47,14 @@ public static String getTablePrefix() {
...
+        // valid as a Realm model class
+        if (clazz.equals(RealmModel.class) || clazz.equals(RealmObject.class)) {
+            throw new IllegalArgumentException("RealmModel or RealmObject was parsed as an argument. " +
```
Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/internal/Util.java]: ditto
