### PR TITLE
Fix NPE in RealmConfiguration.equals() when RxJava is unavailable.

### LINKED ISSUE #2416: Realm.getInstance(RealmConfiguration) error
Hi, I've updated Realm from 0.87.5 to 0.88.00 and I am getting a NullPointerException error when I try to open a new instance without close the previous opened instance.

I have an Activity that I open a Realm instance on onCreate and I close it on onDestroy, but I have to start an IntentService and when this IntentService open an another Realm instance, I get a NullPointerException. If I close the realm of Activity before onDestroy, nothing happens.

```
        config = new RealmConfiguration.Builder(context)
                .name(Environment.REALM_NAME)
                .schemaVersion(Environment.REALM_VERSION)
                .build();

        realm = Realm.getInstance(config);
```

I am getting a NullPointerException when I open Realm.getInstance(config) twice without close the first one. If I close the first instance, it is ok.

### PR DESCRIPTION
**Pull request by zaki50**
This PR fixes #2416

please review this @realm/java

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java [hunk 1]
```diff
@@ -183,7 +183,8 @@ public boolean equals(Object obj) {
         if (!Arrays.equals(key, that.key)) return false;
         if (!durability.equals(that.durability)) return false;
         if (migration != null ? !migration.equals(that.migration) : that.migration != null) return false;
-        if (!rxObservableFactory.equals(that.rxObservableFactory)) return false;
+        //noinspection SimplifiableIfStatement
+        if (rxObservableFactory != null ? !rxObservableFactory.equals(that.rxObservableFactory) : that.migration != null) return false;
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: `that.migration`??

Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: Oh... I'll fix it!

File: realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java [hunk 2]
```diff
@@ -151,4 +152,17 @@ public void copyRealmFromAssets(Context context, String realmPath, String newNam
         outputStream.close();
         is.close();
     }
+
+    public static void emulateRxJavaUnavailable(RealmConfiguration config) {
+        //noinspection TryWithIdenticalCatches
+        try {
+            final Field field = config.getClass().getDeclaredField("rxObservableFactory");
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java]: What about set `RealmConfiguration.rxJavaAvailable` to `new Boolean(false)`? current implementation is also fine to me.

File: realm/realm-library/src/main/java/io/realm/RealmConfiguration.java (hunk 1 above)
Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/RealmConfiguration.java]: @beeender thanks. fixed!

**Comment by beeender** [comment]
Sorry for the bug i created :P

File: realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java (hunk 2 above)
Comment (zaki50) [inline realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java]: Since `rxJavaAvailable` is a static variable, that affects globally.
I prefer current implementation.

Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java]: :+1:

**Comment by beeender** [comment]
:+1:

File: realm/realm-library/src/androidTest/java/io/realm/RealmTests.java [hunk 3]
```diff
@@ -186,6 +186,31 @@ public void getInstance_writeProtectedFile() throws IOException {
...
     @Test
+    public void getInstance_twiceWhenRxJavaUnavailable() {
+        // test for https://github.com/realm/realm-java/issues/2416
+
+        final RealmConfiguration configuration1 = configFactory.createConfiguration("no_RxJava.realm");
+        TestRealmConfigurationFactory.emulateRxJavaUnavailable(configuration1);
+        final RealmConfiguration configuration2 = configFactory.createConfiguration("no_RxJava.realm");
+        TestRealmConfigurationFactory.emulateRxJavaUnavailable(configuration2);
+
+        /*
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmTests.java]: I would move this comment above actually getting the configurations and perhaps use `//` instead just to cut down on the boilerplate/whitespace

File: realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java [hunk 4]
```diff
@@ -151,4 +152,17 @@ public void copyRealmFromAssets(Context context, String realmPath, String newNam
         outputStream.close();
         is.close();
     }
+
+    public static void emulateRxJavaUnavailable(RealmConfiguration config) {
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java]: Any reason this method is on `TestRealmConfigurationFactory` instead of `TestHelper`? This functionality doesn't really seem to belong in this class?

**Comment by cmelchior** [comment]
Apart from a few small comments :+1:

File: realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java (hunk 4 above)
Comment (zaki50) [inline realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java]: moved

File: realm/realm-library/src/androidTest/java/io/realm/RealmTests.java (hunk 3 above)
Comment (zaki50) [inline realm/realm-library/src/androidTest/java/io/realm/RealmTests.java]: done
