### PR TITLE
RealmObject could be GCed when completedAsyncRealmObject

### LINKED ISSUE #4086: NPE on handoverQueryPointer
New random bug happended, this problem can be related with the #2021.

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'long io.realm.RealmQuery.handoverQueryPointer()' on a null object reference
  at io.realm.HandlerController.completedAsyncRealmObject(HandlerController.java:653)
  at io.realm.HandlerController.handleMessage(HandlerController.java:132)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5343)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

- Realm 2.3.0
- Kotlin 1.0.4
- Gradle 2.14.1

### PR DESCRIPTION
**Pull request by beeender**
Fix #4086

### CODE REVIEW

**Comment by beeender** [comment]
hmmm, the root cause described in the PR doesn't seem to be correct. We did acquire a strong ref at the beginning of the function.

**Comment by ppamorim** [comment]
@beeender Thank you!

**Comment by beeender** [comment]
@ppamorim I am sorry that this PR won't be merged since I still cannot see the root cause why that could happen. I really suggest you to wait for #3834 released which will make a proper fix for the issue. #3834 has some fundamental changes for the async queries and the original #4086 only exists in current implementation of async query. I cannot spend more time on it since the #3834 will fix it anyway.

So if you really want to solve the issue right now, you can use this PR and build a lib for yourself. The risks i can tell without knowing the root cause of the original issues are:

- Might be nothing, could be on some calling routing the original async RealmObject has been returned or GCed, then it is safely return there.
or 
- There are some time sequence problems, by returning from there, the original listener on the RealmObject (the results of `findFirstAsync`) won't be called.

**Comment by beeender** [comment]
hmm, on sec, might be bug there. I will push a new commit

**Comment by beeender** [comment]
@ppamorim did you ever use `RealmObject.load()` in your project? I am trying to understand of the reproduce steps for the issue.

**Comment by ppamorim** [comment]
@beeender No one. I believe that this problem happens when the application runs a async thread using a Realm instance to update a field using the method `executeTransaction`, randomly. I am not 100% sure so I must verify it.

File: realm/realm-library/src/main/java/io/realm/HandlerController.java [hunk 1]
```diff
@@ -628,7 +628,7 @@ private void completedAsyncRealmObject(QueryUpdateTask.Result result) {
                 } else if (compare > 0) {
                     // the caller has advanced we need to
                     // retry against the current version of the caller if it's still empty
-                    if (RealmObject.isValid(proxy)) { // already completed & has a valid pointer no need to re-run
+                    if (RealmObject.isLoaded(proxy)) { // already completed & has a valid pointer no need to re-run
```
Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: `isLoaded` guarantees the query completed, it doesn't guarantee a valid pointer (for this we need to call `isValid`)

the instance could be null if the query didn't find anything

Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: I doubt it might the root cause of #4086 , but i am not sure. This behavior has some potential problems. See https://gist.github.com/beeender/9a37c81d56326f02be734a3087da0f84#file-breaking-java-L66

Comment (nhachicha) [inline realm/realm-library/src/main/java/io/realm/HandlerController.java]: I suggest the following then, which will only re-run the query if it's not loaded, but only notifies the listeners if the `RealmObject/accessor` is still attached
```java
if (RealmObject.isLoaded(proxy)) { // already completed, no need to re-run
    if (RealmObject.isValid(proxy)) { // has a valid pointer (not deleted)
        RealmLog.trace("[COMPLETED_ASYNC_REALM_OBJECT %s], realm: %s. " +
                        "RealmObject is already loaded, just notify it",
                realm, HandlerController.this);
        proxy.realmGet$proxyState().notifyChangeListeners$realm();
    }

} else {
//....
```

**Comment by Zhuinden** [comment]
Is this in the SNAPSHOT?

I reproduced this on 2.3.0

**Comment by Zhuinden** [comment]
@beeender @cmelchior guys, this might not be enough - the problem is that if `realm.close()` is called while long-running async query is running, then `close()` does `handler = null`, but `completeAsyncResults` and `completeAsyncObject` does not check against `null`

**Comment by Zhuinden** [comment]
```
02-01 10:19:30.191 25549-25591/com.zhuinden.realmbreak E/REALM_JAVA: java.lang.NullPointerException
                                                                         at io.realm.AndroidNotifier.completeAsyncResults(AndroidNotifier.java:120)
                                                                         at io.realm.RealmQuery.closeSharedRealmAndSendEventToNotifier(RealmQuery.java:2233)
                                                                         at io.realm.RealmQuery.access$000(RealmQuery.java:62)
                                                                         at io.realm.RealmQuery$3.call(RealmQuery.java:1863)
                                                                         at io.realm.RealmQuery$3.call(RealmQuery.java:1845)
                                                                         at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                         at java.lang.Thread.run(Thread.java:856)
02-01 10:19:30.195 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297, .
02-01 10:19:30.195 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297
02-01 10:19:30.195 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320, .
02-01 10:19:30.195 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320
02-01 10:19:30.199 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297, .
02-01 10:19:30.199 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297
02-01 10:19:30.207 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320, .
02-01 10:19:30.211 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320
02-01 10:19:30.215 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297, .
02-01 10:19:30.215 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297
02-01 10:19:30.219 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320, .
02-01 10:19:30.219 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320
02-01 10:19:30.219 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297, .
02-01 10:19:30.219 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297
02-01 10:19:30.219 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320, .
02-01 10:19:30.219 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320
02-01 10:19:30.223 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297, .
02-01 10:19:30.223 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297
02-01 10:19:30.227 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320, .
02-01 10:19:30.227 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320
02-01 10:19:30.227 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297, .
02-01 10:19:30.227 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297
02-01 10:19:30.239 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320, .
02-01 10:19:30.239 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1320
02-01 10:19:30.239 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: jni: ThrowingException 7, std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297, .
02-01 10:19:30.239 25549-25591/com.zhuinden.realmbreak E/REALM_JNI: Exception has been throw: std::exception in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297
```

eep
