### PR TITLE
Fixes #5677

### LINKED ISSUE #5677: Failing to open synced realm after problems with internet.
#### Goal

Open synced realm using Realm.getInstanceAsync.

#### Expected Results

onSuccess called in provided callback
 
#### Actual Results

onError called with Throwable where message is set to "UNKNOWN(-1)
It was not possible to download all remote changes. Has the SyncClient been started?"

#### Steps & Code to Reproduce

1) call Realm.getInstanceAsync with waitForInitialRemoteData() set in configuration.
2) if something happened while data is downloading (internet connection lost, or user disable wifi or enter airplane mode) onError called with proper message. This works as expected.
3) Restore connection to internet
4) Try to connect again with same configuration.
5) onError called with message that downloading is not possible. 

If you restart application - all works fine.

#### Code Sample

```java
RealmConfiguration config =  new SyncConfiguration.Builder(user, getServerURL()).schemaVersion(SCHEMA_VERSION).disableSSLVerification().waitForInitialRemoteData().build();
Realm.getInstanceAsync(config, new Realm.Callback() {
            @Override
            public void onError(@NonNull Throwable exception) {
                user.logout();
                onFinished("migrateRealm exception: " + exception.getMessage());
            }

            @Override
            public void onSuccess(@NonNull Realm realm) {
                Realm localRealm = Realm.getDefaultInstance();
                realm.beginTransaction();
                realm.copyToRealmOrUpdate(...);
                realm.commitTransaction();
                realm.close();
                localRealm.close();
                onFinished(null);
            }
        });
```

#### Version of Realm and tooling
Realm version(s): 4.3.1
Realm sync feature enabled: yes
Android Studio version: 3.0.1
Which Android version and device: any

### PR DESCRIPTION
**Pull request by nhachicha**
- There was an issue with the `onGoingAccessTokenQuery` logic that causes the call to obtain an `access_token` ignored if previously an attempt was made offline.
- Removed session network listener in `SyncSession` since it's redundant with the `SyncManager ` one

### CODE REVIEW

File: realm/realm-library/src/objectServer/java/io/realm/SyncSession.java [hunk 1]
```diff
@@ -516,30 +515,11 @@ String getAccessToken(final AuthenticationServer authServer, String refreshToken
...
-                        public void onChange(boolean connectionAvailable) {
-                            if (connectionAvailable) {
-                                if (!onGoingAccessTokenQuery.getAndSet(true)) {
-                                    authenticateRealm(authServer);
-                                }
-                                NetworkStateReceiver.removeListener(this);
-                            }
-                        }
-                    };
-                    NetworkStateReceiver.addListener(networkListener);
```
Comment (cmelchior) [inline realm/realm-library/src/objectServer/java/io/realm/SyncSession.java]: So this logic here is being triggered indirectly by Object Store,  right?

File: CHANGELOG.md [hunk 2]
```diff
@@ -3,7 +3,7 @@
 ## Bug Fixes
 
 * Added missing `RealmQuery.oneOf()` for Kotlin that accepts non-nullable types (#5717).
-
+* [ObjectServer] fixed an issue preventing sync to resume when the network is back (#5677).
```
Comment (cmelchior) [inline CHANGELOG.md]: Nitpick: Big `f` in fixed

File: realm/realm-library/src/objectServer/java/io/realm/SyncSession.java (hunk 1 above)
Comment (nhachicha) [reply realm/realm-library/src/objectServer/java/io/realm/SyncSession.java]: Yes, calling reconnect from the SyncManger should hint to the OS to call `bindSessionWithConfig` to obtain an `access_token`
