### PR TITLE
Correct checking in DynamicRealmObject.setList

### LINKED ISSUE #2368: DynamicRealmObject can't set the list field
I have DynamicRealmObject instance that has list field that is connected to some scheme,
but when I use DynamicRealmObject.setList - I have an exception that says that list items should be the same type as original object is

`java.lang.IllegalArgumentException: Element at index 0 is not the proper type. Was class_testInnerWithList3_details expected class_testInnerWithList3.
at io.realm.DynamicRealmObject.setList(DynamicRealmObject.java:595)
at com.kinvey.android.cache.ClassHash.saveData(ClassHash.java:209)
at com.kinvey.android.cache.RealmCache.insertOrUpdate(RealmCache.java:285)
at com.kinvey.android.cache.RealmCache.save(RealmCache.java:155)
at com.kinvey.androidTest.cache.CacheTest.testSaveWithInnerList(CacheTest.java:179)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1873)
`

in my test I create object with scheme name testInnerWithList3 and list items are expected to be testInnerWithList3_details

and when I'm trying to use DynamicRealmObject.setList(RealmList) I got following exception

### PR DESCRIPTION
**Pull request by beeender**
Fix #2368

### CODE REVIEW

**Comment by beeender** [comment]
Back to WIP, there is some more checking in setters needs to be done.

**Comment by beeender** [comment]
@realm/java

File: realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java [hunk 1]
```diff
@@ -543,8 +543,8 @@ public void setObject(String fieldName, DynamicRealmObject value) {
             if (value.realm == null || value.row == null) {
                 throw new IllegalArgumentException("Cannot link to objects that are not part of the Realm.");
             }
-            if (!realm.getConfiguration().equals(value.realm.getConfiguration())) {
-                throw new IllegalArgumentException("Cannot add an object from another Realm");
+            if (realm != value.realm) {
+                throw new IllegalArgumentException("Cannot add an object from another Realm.");
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java]: Different Realm is a bit ambiguous here? Because this also fails if you have to SharedGroups for the same Realm. I guess that is the point though, but perhaps rephrase to `Cannot add an object from another Realm instance` ?

File: realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java [hunk 2]
```diff
@@ -587,15 +588,16 @@ public void setList(String fieldName, RealmList<? extends RealmObject> list) {
...
             RealmObject obj = list.get(i);
-            if (!typeValidated) {
-                String elementType = obj.row.getTable().getName();
-                if (!tableName.equals(elementType)) {
-                    throw new IllegalArgumentException(String.format(Locale.ENGLISH,
-                            "Element at index %d is not the proper type. " +
-                            "Was %s expected %s.", i, elementType, tableName));
-                }
+            if (obj.realm != realm) {
+                throw new IllegalArgumentException("Each element in `list` must belong to the same Realm.");
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java]: Same

**Comment by cmelchior** [comment]
Apart from a small comment about the error message itself :+1:

File: realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java [hunk 3]
```diff
@@ -561,8 +561,9 @@ public void setObject(String fieldName, DynamicRealmObject value) {
      *
      * @param fieldName field name.
      * @param list list of references.
-     * @throws IllegalArgumentException if field name doesn't exists, it is not a list field or the type
-     * of the object represented by the DynamicRealmObject doesn't match.
+     * @throws IllegalArgumentException if field name doesn't exists, it is not a list field, the type
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java]: "exists" -> "exist"

File: realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java [hunk 4]
```diff
@@ -587,15 +588,16 @@ public void setList(String fieldName, RealmList<? extends RealmObject> list) {
...
             RealmObject obj = list.get(i);
-            if (!typeValidated) {
-                String elementType = obj.row.getTable().getName();
-                if (!tableName.equals(elementType)) {
-                    throw new IllegalArgumentException(String.format(Locale.ENGLISH,
-                            "Element at index %d is not the proper type. " +
-                            "Was %s expected %s.", i, elementType, tableName));
-                }
+            if (obj.realm != realm) {
+                throw new IllegalArgumentException("Each element in `list` must belong to the same Realm instance.");
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java]: Don't use back quotes- it's not markdown ;-) Just use plain quotation marks (`'`).

File: realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java [hunk 5]
```diff
@@ -587,15 +588,16 @@ public void setList(String fieldName, RealmList<? extends RealmObject> list) {
...
+            }
+            if (!typeValidated && !linkTargetTable.hasSameSchema(obj.row.getTable())) {
+                throw new IllegalArgumentException(String.format(Locale.ENGLISH,
+                        "Element at index %d is not the proper type. " +
+                                "Was %s expected %s.", i, obj.row.getTable().getName(), linkTargetTable.getName()));
```
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java]: Add `'` around the two `%s`.

**Comment by kneth** [comment]
:+1: with a few minor comments.

**Comment by beeender** [comment]
All comments fixed.
