### PR TITLE
RAII wrapper for some JNI resources

### LINKED ISSUE #3726: Native crash on api 10
When I call `Realm.GetDefaultInstance()` I get a crash in native code on an api 10 (GT-I9070) device. It works on newer devices. It crashes with realm 2.1.1 but not on 1.2.0. 

logs:
```
10-31 09:45:57.400 I/dalvikvm: "Signal Catcher" daemon prio=5 tid=4 RUNNABLE
10-31 09:45:57.400 I/dalvikvm:   | group="system" sCount=0 dsCount=0 obj=0x40518e60 self=0xf20b0
10-31 09:45:57.400 I/dalvikvm:   | sysTid=5210 nice=0 sched=0/0 cgrp=[no-cpu-subsys] handle=1151064
10-31 09:45:57.400 I/dalvikvm:   | schedstat=( 1037600 244140 25 )
10-31 09:45:57.400 I/dalvikvm:     at dalvik.system.NativeStart.run(Native Method)
10-31 09:45:57.400 I/dalvikvm: [<c0295308>] save_stack_trace_tsk+0x0/0x90
                               [<c03b5af0>] proc_pid_stack+0xf8/0x144
                               [<c03b6e54>] proc_single_show+0x48/0x84
                               [<c038b47c>] seq_read+0x26c/0x4e4
                               [<c03720fc>] vfs_read+0xa8/0x150
                               [<c0372250>] sys_read+0x3c/0x68
                               [<c0291740>] ret_fast_syscall+0x0/0x30
                               [<ffffffff>] 0xffffffff
                               ------------------------------
10-31 09:45:57.400 I/dalvikvm: "main" prio=5 tid=1 RUNNABLE
10-31 09:45:57.400 I/dalvikvm:   | group="main" sCount=1 dsCount=0 obj=0x400281f8 self=0xd190
10-31 09:45:57.400 I/dalvikvm:   | sysTid=5207 nice=0 sched=0/0 cgrp=[no-cpu-subsys] handle=-1345002240
10-31 09:45:57.400 I/dalvikvm:   | schedstat=( 757019059 483764632 1174 )
10-31 09:45:57.500 I/dalvikvm:     at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
10-31 09:45:57.500 I/dalvikvm:     at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
10-31 09:45:57.500 I/dalvikvm:     at io.realm.BaseRealm.<init>(BaseRealm.java:82)
10-31 09:45:57.530 I/dalvikvm:     at io.realm.Realm.<init>(Realm.java:140)
10-31 09:45:57.530 I/dalvikvm:     at io.realm.Realm.createAndValidate(Realm.java:285)
10-31 09:45:57.530 I/dalvikvm:     at io.realm.Realm.createInstance(Realm.java:266)
10-31 09:45:57.560 I/dalvikvm:     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:143)
10-31 09:45:57.560 I/dalvikvm:     at io.realm.Realm.getDefaultInstance(Realm.java:211)
10-31 09:45:57.560 I/dalvikvm:     at *snip*.LoginActivity.startLogin(LoginActivity.java:221)
10-31 09:45:57.560 I/dalvikvm:     at *snip*.LoginActivity.login(LoginActivity.java:207)
10-31 09:45:57.560 I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
10-31 09:45:57.560 I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:507)
10-31 09:45:57.580 I/dalvikvm:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
10-31 09:45:57.580 I/dalvikvm:     at android.view.View.performClick(View.java:2585)
10-31 09:45:57.590 I/dalvikvm:     at android.view.View$PerformClick.run(View.java:9299)
10-31 09:45:57.620 I/dalvikvm:     at android.os.Handler.handleCallback(Handler.java:587)
10-31 09:45:57.620 I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:92)
10-31 09:45:57.620 I/dalvikvm:     at android.os.Looper.loop(Looper.java:130)
10-31 09:45:57.620 I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:3770)
10-31 09:45:57.620 I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
10-31 09:45:57.620 I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:507)
10-31 09:45:57.620 I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
10-31 09:45:57.620 I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
10-31 09:45:57.620 I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)
10-31 09:45:57.620 I/dalvikvm: [<ffffffff>] 0xffffffff
                               ------------------------------
```

realm config:
```
Realm.init(this);
        RealmConfiguration config = new RealmConfiguration.Builder()
                .schemaVersion(REALMSCHEMAVERSION)
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(config);
```

### PR DESCRIPTION
**Pull request by beeender**
* Move the global jvm pointer to JniUtils and add some helper functions.
* Wrapper for jmethodID, global weak ref.
* Refactor the wrapper for the local ref.
* Before using the global weak ref, always try to acquire a local ref
  first since until Android 4.0 weak global references could only be
  passed to NewLocalRef, NewGlobalRef, and DeleteWeakGlobalRef.
  See https://developer.android.com/training/articles/perf-jni.html#unsupported
  for more details. This fix #3726 .

### CODE REVIEW

File: realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp [hunk 1]
```diff
@@ -19,9 +19,11 @@
 #include <shared_realm.hpp>
 #include <object_store.hpp>
 #include "util.hpp"
+#include "jni_util/java_local_ref.hpp"
 #include "io_realm_internal_TableQuery.h"
 
 using namespace realm;
+using namespace realm::jni_util;
```
Comment (bmunkholm) [inline realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp]: No need for adding "using" to make it more unclear what you call in line 1215 :-)

File: realm/realm-library/src/main/cpp/io_realm_internal_Util.cpp [hunk 2]
```diff
@@ -22,7 +22,10 @@
 #include "mem_usage.hpp"
 #include "util.hpp"
 
+#include "jni_util/jni_utils.hpp"
+
 using std::string;
+using namespace realm::jni_util;
```
Comment (bmunkholm) [inline realm/realm-library/src/main/cpp/io_realm_internal_Util.cpp]: delete "using" line - you already qualify the namespace in l 45 - which is better anyway.

File: realm/realm-library/src/main/cpp/java_binding_context.cpp [hunk 3]
```diff
@@ -15,46 +15,20 @@
...
-    if (m_java_notifier) {
-        // Always try to attach here since this may be called in the finalizer/phantom thread where m_local_jni_env
-        // should not be used on. No need to call DetachCurrentThread since this thread should always be created by
-        // JVM.
-        JNIEnv *env;
-        m_jvm->AttachCurrentThread(&env, nullptr);
-        env->DeleteWeakGlobalRef(m_java_notifier);
-    }
-}
+using namespace realm::jni_util;
```
Comment (bmunkholm) [inline realm/realm-library/src/main/cpp/java_binding_context.cpp]: delete line.

File: realm/realm-library/src/main/cpp/objectserver_shared.hpp [hunk 4]
```diff
@@ -28,6 +28,9 @@
 #include <sync/sync_manager.hpp>
 
 #include "util.hpp"
+#include "jni_util/jni_utils.hpp"
+
+using namespace realm::jni_util;
```
Comment (bmunkholm) [inline realm/realm-library/src/main/cpp/objectserver_shared.hpp]: delete

File: realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp (hunk 1 above)
Comment (bmunkholm) [inline realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp]: Well, my point is that you add a line `using namespace realm::jni_util;` to avoid writing `jni_util::` in front of the `JavaLocalRef`. It seems more trouble and less clear to my eye. So I would prefer we add `jni_util::`.
We don't have a standard for when to use `using` - but here and in the other files, it seems unnecessary and inconsistent as you in other files add `using` but still make calls with `jni_util::` :-)

File: realm/realm-library/src/main/cpp/jni_util/java_local_ref.hpp [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+namespace realm {
+namespace jni_util {
+
+struct NeedToCreateLocalRef {};
+static constexpr NeedToCreateLocalRef need_to_create_local_ref{};
+
+// Wraps jobject and automatically calls DeleteLocalRef when this object is destroyed.
+// DeleteLocalRef is not necessary to be called in most cases since all local references will be cleaned up when the
+// program returns to Java from native. But if the local ref is created in a loop, consider to use this class to wrap it
+// because the size of local reference table is relative small (512 on Android).
```
Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/java_local_ref.hpp]: "512" -> "512 bytes"

File: realm/realm-library/src/main/cpp/jni_util/java_method.cpp [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+
+JavaMethod::JavaMethod(JNIEnv *env, jclass cls, const char* method_name, const char* signature)
+{
+    m_method_id = env->GetMethodID(cls, method_name, signature);
+}
+
+JavaMethod::JavaMethod(JNIEnv *env, jobject obj, const char* method_name, const char* signature)
+{
+    jclass cls = env->GetObjectClass(obj);
+    m_method_id = env->GetMethodID(cls, method_name, signature);
```
Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/java_method.cpp]: What if `m_method_id == nullptr`?

File: realm/realm-library/src/main/cpp/jni_util/java_method.cpp [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+    env->DeleteLocalRef(cls);
+}
+
+JavaMethod::JavaMethod(JNIEnv *env, const char* class_name, const char* method_name, const char* signature)
+{
+    jclass cls = env->FindClass(class_name);
+    REALM_ASSERT_DEBUG(cls != nullptr);
+    m_method_id = env->GetMethodID(cls, method_name, signature);
```
Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/java_method.cpp]: What if `m_method_id == nullptr`?

File: realm/realm-library/src/main/cpp/jni_util/java_method.cpp [hunk 8]
```diff
@@ -0,0 +1,41 @@
...
+{
+    jclass cls = env->GetObjectClass(obj);
+    m_method_id = env->GetMethodID(cls, method_name, signature);
+    env->DeleteLocalRef(cls);
+}
+
+JavaMethod::JavaMethod(JNIEnv *env, const char* class_name, const char* method_name, const char* signature)
+{
+    jclass cls = env->FindClass(class_name);
+    REALM_ASSERT_DEBUG(cls != nullptr);
```
Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/java_method.cpp]: So we should enable assertions? Or only a subset of them?

File: realm/realm-library/src/main/cpp/jni_util/jni_utils.cpp [hunk 9]
```diff
@@ -0,0 +1,47 @@
...
+JNIEnv* JniUtils::get_env(bool attach_if_needed) {
+    REALM_ASSERT_DEBUG(s_instance);
+
+    JNIEnv* env;
+    if (s_instance->m_vm->GetEnv(reinterpret_cast<void**>(&env), s_instance->m_vm_version) != JNI_OK &&
+            attach_if_needed) {
+        jint ret = s_instance->m_vm->AttachCurrentThread(&env, nullptr);
+        REALM_ASSERT_DEBUG(ret == JNI_OK);
+    } else {
+        REALM_ASSERT_DEBUG(false);
```
Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/jni_utils.cpp]: Why isn't this an error situation?

File: realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp (hunk 1 above)
Comment (beeender) [inline realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp]: I am trying to stick with:
* always use full namespace in the header files -- I think that is why you say "you in other files add using but still make calls with jni_util::" 
* always use `using namespace` in the source files since it seems to be an convention for OS and core.

I really like to have a rule to follow, when shall we use `using namespace` and when shall we not?

File: realm/realm-library/src/main/cpp/jni_util/jni_utils.cpp (hunk 9 above)
Comment (beeender) [inline realm/realm-library/src/main/cpp/jni_util/jni_utils.cpp]: It is. Shall it change it to `REALM_ASSERT_RELEASE(true)`?

File: realm/realm-library/src/main/cpp/jni_util/java_method.cpp (hunk 8 above)
Comment (beeender) [inline realm/realm-library/src/main/cpp/jni_util/java_method.cpp]: Isn't `REALM_ASSERT_DEBUG` enabled for debug build already? The idea is this kind of error should be found during the development.

File: realm/realm-library/src/main/cpp/jni_util/jni_utils.cpp (hunk 9 above)
Comment (kneth) [inline realm/realm-library/src/main/cpp/jni_util/jni_utils.cpp]: Either that or just throw an exception.

File: realm/realm-library/src/main/cpp/jni_util/java_local_ref.hpp [hunk 10]
```diff
@@ -0,0 +1,57 @@
...
+
+// Wraps jobject and automatically calls DeleteLocalRef when this object is destroyed.
+// DeleteLocalRef is not necessary to be called in most cases since all local references will be cleaned up when the
+// program returns to Java from native. But if the local ref is created in a loop, consider to use this class to wrap it
+// because the size of local reference table is relative small (512 bytes on Android).
+template <typename T>
+class JavaLocalRef {
+public:
+    // need_to_create is useful when acquire a local ref from a global weak ref.
+    inline JavaLocalRef(JNIEnv* env, T obj) noexcept : m_jobject( obj), m_env(env) {};
```
Comment (nhachicha) [inline realm/realm-library/src/main/cpp/jni_util/java_local_ref.hpp]: remove extra space before ` obj`

File: realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp (hunk 1 above)
Comment (bmunkholm) [inline realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp]: Never `using` in header files - agree.
It's not a convention to use ùsing` in .cpp files. It's more a convenience for often used methods. In this case it seems better to fully qualify as it's rather rarely used in the files anyway.

Comment (bmunkholm) [inline realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp]: And you actually have mixed use also in .cpp files :-) e.g. io_realm_internal_Util.cpp

Comment (bmunkholm) [inline realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp]: I see I misread JniUtils:: for jni_utils:: - so there was no real inconsistency. 
It was just a detail - do as you please. It will work either way :-)

Comment (beeender) [inline realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp]: 👯‍♂️

**Comment by dalinaum** [comment]
I just re-ran the CI.

**Comment by beeender** [comment]
@dalinaum Uh ... there is a bug, not CI's fault ...
