### PR TITLE
Fix getLocalInstanceCount crashing when Realms are closed again.

### LINKED ISSUE #3791: Realm.getLocalInstanceCount() can crash
See https://github.com/realm/realm-java/issues/3788#issuecomment-260318809

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #3791 

@realm/java

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/RealmCache.java [hunk 1]
```diff
@@ -402,7 +402,8 @@ static int getLocalThreadCount(RealmConfiguration configuration) {
         } else {
             int totalRefCount = 0;
             for (RealmCacheType type : RealmCacheType.values()) {
-                totalRefCount += cache.refAndCountMap.get(type).localCount.get();
+                Integer localCount = cache.refAndCountMap.get(type).localCount.get();
```
Comment (Zhuinden) [inline realm/realm-library/src/main/java/io/realm/RealmCache.java]: Is there a chance for `cache.refAndCountMap.get(type)` to return null?

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmCache.java]: No, it is initialized in the constructor
