### PR TITLE
Fix SyncConfiguration.toString()

### LINKED ISSUE #3787: SyncConfiguration.toString()
`SyncConfiguration.toString()` currently outputs an empty String. It should output debug information equal to `RealmConfiguration`.

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #3787 

@realm/java

### CODE REVIEW

File: realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java [hunk 1]
```diff
@@ -177,8 +177,17 @@ public int hashCode() {
...
     public String toString() {
-        StringBuilder stringBuilder = new StringBuilder();
-        // TODO
+        StringBuilder stringBuilder = new StringBuilder(super.toString());
+        stringBuilder.append("\n");
+        stringBuilder.append("serverUrl: " + serverUrl);
+        stringBuilder.append("\n");
+        stringBuilder.append("user: " + user);
+        stringBuilder.append("\n");
+        stringBuilder.append("syncPolicy: " + syncPolicy);
```
Comment (zaki50) [inline realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java]: `SyncPolicy` (`AutomaticSyncPolicy`) should override `toString()`.

File: realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java [hunk 2]
```diff
@@ -177,8 +177,17 @@ public int hashCode() {
...
+        stringBuilder.append("\n");
+        stringBuilder.append("errorHandler: " + errorHandler);
```
Comment (zaki50) [inline realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java]: `SyncManager#SESSION_NO_OP_ERROR_HANDLER` should override `toString()`.

File: realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java (hunk 1 above)
Comment (cmelchior) [inline realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java]: Not sure it could provide anything meaningful in a custom toString?

File: realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java (hunk 2 above)
Comment (cmelchior) [inline realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java]: Same. Would there be any meaningful information?

File: realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java [hunk 3]
```diff
@@ -177,8 +177,17 @@ public int hashCode() {
 
     @Override
     public String toString() {
-        StringBuilder stringBuilder = new StringBuilder();
-        // TODO
+        StringBuilder stringBuilder = new StringBuilder(super.toString());
+        stringBuilder.append("\n");
+        stringBuilder.append("serverUrl: " + serverUrl);
+        stringBuilder.append("\n");
+        stringBuilder.append("user: " + user);
```
Comment (cmelchior) [inline realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java]: Done
