### PR TITLE
Fail Realm.migrateRealm() if a SyncConfiguration is used.

### LINKED ISSUE #4075: calling Realm#migration with a SyncConf should throw
Sync Realm perform automatic migration, we shouldn't mislead the user to call [migrateRealm](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L608) with a specified migration block, this should throw `UnsupportedOperationException` instead of silently ignoring the user migration block

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #4075 

I used `IllegalArgumentException` instead of `UnsupportedOperationException`, since the later should only really be used if the method fails for all input IMO.

### CODE REVIEW

File: realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+ */
+@RunWith(AndroidJUnit4.class)
+public class SyncedRealmMigrationTests {
+
+    @Rule
+    public final TestSyncConfigurationFactory configFactory = new TestSyncConfigurationFactory();
+    @Rule
+    public final ExpectedException thrown = ExpectedException.none();
+
+    private Realm realm;
```
Comment (nhachicha) [inline realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java]: Not used

File: realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+    private Context context;
```
Comment (nhachicha) [inline realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java]: Not used

File: realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+
+    @Before
+    public void setup() {
```
Comment (nhachicha) [inline realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java]: `setup` include unused code, could be removed

File: realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+        context = InstrumentationRegistry.getInstrumentation().getContext();
+    }
+
+    @After
+    public void tearDown() {
```
Comment (nhachicha) [inline realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java]: `tearDown ` include unused code, could be removed
