### PR TITLE
Realm Modules

### LINKED ISSUE #870: Android 2.3: Could not find validateTable method in generated proxy class
I've recently changed my app's minimum API level to 9 and when testing on Android 2.3 I always get this exception: 
```
java.lang.RuntimeException: Unable to create application com.tbilisi.bus.App: io.realm.exceptions.RealmException: Could not find the validateTable method in the generated io.realm.HistoryItemRealmProxy class: Annotation processor may not have been executed.
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3413)
            at android.app.ActivityThread.access$2200(ActivityThread.java:124)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1012)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3821)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: io.realm.exceptions.RealmException: Could not find the validateTable method in the generated io.realm.HistoryItemRealmProxy class: Annotation processor may not have been executed.
            at io.realm.Realm.initializeRealm(Realm.java:608)
            at io.realm.Realm.createAndValidate(Realm.java:523)
            at io.realm.Realm.create(Realm.java:480)
            at io.realm.Realm.getInstance(Realm.java:397)
            at io.realm.Realm.getInstance(Realm.java:359)
            at io.realm.Realm.getInstance(Realm.java:340)
            at com.tbilisi.bus.App.loadRealm(App.java:22)
            at com.tbilisi.bus.App.onCreate(App.java:18)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3410)
            at android.app.ActivityThread.access$2200(ActivityThread.java:124)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1012)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3821)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
```

All of my source is published at https://github.com/shvelo/tbilisi-bus  
I've tried adding `@RealmClass` to my models but it doesn't help at all.

### LINKED ISSUE #992: Misleading exception: Annotation processor may not have been executed
Hi guys,

I've got an exception ```An exception was thrown in the copyToRealm method in the proxy class  io.realm.UserRealmRealmProxy: Annotation processor may not have been executed.```. I traced it to this piece of code in the sources of Realm.java:
```java
    private <E extends RealmObject> E copyOrUpdate(E object, boolean update) {
        Class<? extends RealmObject> realmClass = getRealmClassFromObject(object);
        Class<?> proxyClass = getProxyClass(realmClass);
        Method method = insertOrUpdateMethods.get(realmClass);
        if (method == null) {
            try {
                method = proxyClass.getMethod("copyOrUpdate", new Class[]{Realm.class, realmClass, boolean.class, Map.class});
            } catch (NoSuchMethodException e) {
                throw new RealmException("Could not find the copyOrUpdate() method in generated proxy class for " + proxyClass.getName() + ": " + APT_NOT_EXECUTED_MESSAGE, e);
            }
            insertOrUpdateMethods.put(proxyClass, method);
        }
        try {
            Object result = method.invoke(null, this, object, update, new HashMap<RealmObject,RealmObject>());
            return (E) result;
        } catch (IllegalAccessException e) {
            throw new RealmException("Could not execute the copyToRealm method : " + APT_NOT_EXECUTED_MESSAGE, e);
        } catch (InvocationTargetException e) {
            throw new RealmException("An exception was thrown in the copyToRealm method in the proxy class  " + proxyClass.getName() + ": " + APT_NOT_EXECUTED_MESSAGE, e);
        }
    }
```
So, in my case it throws ```InvocationTargetException```. But the message of the original exception is ```java.lang.IllegalStateException: Mutable method call during read transaction.```. But catch clause doesn't take it in account and throws "Annotation processor may not have been executed." anyway.

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #870 
Fixes #992
This PR is part of #880 

It introduces the concept of RealmModules (as a internal feature until we add public methods for it through RealmConfiguration) that makes it possible to group Realm classes into RealmModules (essentially schemas) so each Realm can be configured to only handle a set of classes. It adds the the following features: 

- **Important** In the default case, the app developer does not have to do any setup just like now.
- It has removed almost all reflection code from Realm.java, which also fixes bug: https://github.com/realm/realm-java/issues/870
- It makes it possible for Realm to work with library projects. See enhancement https://github.com/realm/realm-java/issues/511, although there is no public API methods added yet.
- It speeds up creating a fresh Realm instance by 20% for 15 model classes, and 5% for 3 model classes.
- It simplifies the ProGuard setup and allow almost every Realm class to be obfuscated (only module classes cannot be).
- A  description of the how the Annotation processor works has been added to RealmProcessor.java
- The RealmModule annotation is placed in our internal packages until we add RealmConfiguration. Then it will be moved out from internal

API:
```
// Defining a library Realm module
@RealmModule(library = true, allClasses = true)
public class LibModule {
}

@RealmModule(library = true, classes = { Foo.class })
public class LibModule {
}

// Defining an app Realm module
@RealmModule(allClasses = true)
public class AppModule {
}

@RealmModule(classes = { Foo.class, Bar.class})
public class AppModule {
}
```

### CODE REVIEW

**Comment by cmelchior** [comment]
Ready for review @emanuelez @kneth @bmunkholm @alazier

**Comment by emanuelez** [comment]
Move proguard demo from the intro example

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java [hunk 1]
```diff
@@ -30,15 +31,73 @@
...
+ *
+ * WHY:
+ *
+ * 1) A RealmObjectProxy object is created for each class annotated with {@link io.realm.annotations.RealmClass}. This
+ * proxy extends the original model class and rewires all field access to point to the native Realm memory instead of
+ * Java memory. It also adds a lot of static helper methods to the class.
+ *
+ * 2) The annotation processor is either in "library" mode or in "app" mode. This is defined by having a class
+ * annotated with @RealmModule(library = true). Modules with library = true and library = false cannot be mixed, and
+ * will throw an error. If no library modules are defined, we will create a DefaultRealmModule containing all known
```
Comment (kneth) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: "will throw an error" -> "an exception will be thrown"

**Comment by alazier** [comment]
This looks interesting. If it is possible to combine this with RealmConfig it might be nice to do so. Then you can configure a particular Realm to only support a specific set of types.

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java [hunk 2]
```diff
@@ -30,15 +31,73 @@
...
+ *
+ * 1) Create a Realm.
+ *
+ * 2) It is assigned one or more modules. If no module is assigned, the default module is used.
+ *
+ * 4) Each time a static helper method is needed, the Realm can now delegate these method calls to the appropriate
+ *    Mediator which in turn will delegate the method call to the appropriate RealmObjectProxy class.
+ *
+ *
+ * DESIGN GOALS
```
Comment (kneth) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: Consider to move "DESIGN GOALS" to the top.

File: realm/src/main/java/io/realm/Realm.java [hunk 3]
```diff
@@ -1057,109 +966,49 @@ public void writeEncryptedCopyTo(File destination, byte[] key) throws IOExceptio
...
-                tables.put(clazz, table);
-            } catch (IllegalAccessException e) {
-                throw new RealmException("Could not launch the initTable method: " + APT_NOT_EXECUTED_MESSAGE);
-            } catch (InvocationTargetException e) {
-                e.printStackTrace();
-                throw new RealmException("An exception occurred while running the initTable method: " + APT_NOT_EXECUTED_MESSAGE);
-            }
-        }
+        Table table = getTable(clazz);
+//        table = tables.get(clazz);
```
Comment (kneth) [inline realm/src/main/java/io/realm/Realm.java]: If this code is not needed, please remove it instead of commenting it out.

**Comment by kneth** [comment]
Can you provide an example of a library project so future library developers can see how they can use Realm in isolation?

**Comment by cmelchior** [comment]
Good idea. It will be part of a separate PR.

File: realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+ * Utility class for holding metadata for the Realm modules.
+ */
+public class ModuleMetaData {
+
+    private final Set<ClassMetaData> availableClasses;
+    private final RoundEnvironment env;
+    private Map<String, Set<ClassMetaData>> modules = new HashMap<String, Set<ClassMetaData>>();
+    private Map<String, Set<ClassMetaData>> libraryModules = new HashMap<String, Set<ClassMetaData>>();
+    private Map<String, ClassMetaData> classMetaData = new HashMap<String, ClassMetaData>();
+    private boolean shouldCreateDefaultModule = false;
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java]: Useless assignment. False is the default value

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java [hunk 5]
```diff
@@ -30,15 +31,73 @@
...
+ * The RealmProcessor is responsible for creating the plumbing that connects the RealmObjects to a Realm. The process
+ * for doing so is summarized below and then described in more detail.
+ *
+ *
+ * DESIGN GOALS
+ *
+ * The processor should support the following design goals:
+ *
+ * - Minimize reflection.
+ * - As much as possible can be obfuscated.
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: "It can be obfuscated as much as possible"
Otherwise I read it with Yoda's voice in my head :)

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java [hunk 6]
```diff
@@ -75,21 +134,65 @@ public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment
                 Utils.error(e.getMessage(), classElement);
             } catch (UnsupportedOperationException e) {
                 Utils.error(e.getMessage(), classElement);
-            }
+			}
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: Indentation

**Comment by emanuelez** [comment]
This is huge. It should have been splitted further as it is very hard to review properly now.
Also, there's no unit tests to validate the new use-cases.

**Comment by cmelchior** [comment]
Yes, it is huge, but it cannot really be split. I already removed what could be removed, ie. test projects and proguard setup. Also, for single app projects you won't see any difference at least not from a user perspective. 

Maybe it would make sense to do a in-person/hangout review for stuff like this?

File: realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java [hunk 7]
```diff
@@ -0,0 +1,128 @@
...
+                for (Class<?> clazz : module.classes()) {
+                    if (!clazz.getSuperclass().toString().endsWith("RealmObject")) {
+                        Utils.error(clazz.getSimpleName() + " is not extending RealmObject. Only RealmObjects can be " +
+                                "part of a module.");
+                        return false;
+                    }
+                    ClassMetaData metadata = classMetaData.get(clazz.getName());
+                    if (metadata == null) {
+                        Utils.error(Utils.stripPackage(qualifiedName) + " could not be added to the module. It is not " +
+                                "possible to add classes are part of another library.");
```
Comment (kneth) [inline realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java]: "which are"

**Comment by emanuelez** [comment]
Yes, let's take it F2F tomorrow

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java [hunk 8]
```diff
@@ -30,15 +31,73 @@
 
 import io.realm.annotations.RealmClass;
 
+/**
+ * The RealmProcessor is responsible for creating the plumbing that connects the RealmObjects to a Realm. The process
+ * for doing so is summarized below and then described in more detail.
+ *
+ *
+ * DESIGN GOALS
```
Comment (kneth) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: Consider some HTML markup so the generated web page looks better.

Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: :+1: for Kennet's idea

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java [hunk 9]
```diff
@@ -30,15 +31,73 @@
...
+ * - Minimize reflection.
+ * - As much as possible can be obfuscated.
+ * - Library projects must be able to use Realm without interfering with app code.
+ * - App code must be able to use model classes provided by library code.
+ * - It should work for app developers out of the box (ie. put the burden on the library developer)
+ *
+ *
+ * SUMMARY
+ *
+ * 1 ) Create proxy classes for all classes marked with @RealmClass. They are named <modelClass>RealmProxy.java
```
Comment (kneth) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: Mention annotations in the documentation probably require a backslash to get JavaDoc to work.

File: realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java [hunk 10]
```diff
@@ -77,23 +79,23 @@ public static void validateTable(ImplicitTransaction transaction) {
         if(transaction.hasTable("class_Simple")) {
             Table table = transaction.getTable("class_Simple");
             if(table.getColumnCount() != 2) {
-                throw new IllegalStateException("Column count does not match");
+                throw new RealmMigrationNeededException("Column count does not match");
```
Comment (kneth) [inline realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java]: You change to "field" in the messages below. Maybe it should be "field" here too.

File: realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java [hunk 11]
```diff
@@ -0,0 +1,77 @@
...
+ *
+ * A Realm module can either be a library module or an app module. This distinction is made by setting
+ * {@code library = true}. Creating a library module will prevent Realm from creating the default Realm module, which
+ * would otherwise conflict with same class being created by app projects.
+ *
+ * This means that library projects are <bold>required</bold> to use library modules to allow the library to work
+ * seemlessly with app code. App developers can then reuse the modules exposed by the library if they want to use RealmObjects
+ * from that library.
+ *
+ * TODO Add example once RealmConfiguration gets merged.
```
Comment (kneth) [inline realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java]: Will this be done prior to release?

File: realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java [hunk 12]
```diff
@@ -0,0 +1,77 @@
...
+package io.realm.annotations.internal;
+
+import java.lang.annotation.ElementType;
+import java.lang.annotation.Inherited;
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+
+/**
+ * As a default a Realm can store all RealmObjects in a project. However, if you want to restrict a Realm to contain only
```
Comment (kneth) [inline realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java]: Please consider HTML formatting.

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java (hunk 6 above)
Comment (cmelchior) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: It looks fine in the source code. GitHub is doing it wrong.

Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: Not really. Your version is using TABs

File: realm/src/main/java/io/realm/Realm.java [hunk 13]
```diff
@@ -319,15 +310,11 @@ public void setAutoRefresh(boolean autoRefresh) {
...
-    public Table getTable(Class<?> clazz) {
-        final String proxySuffix = "RealmProxy";
-        String proxiedClassName = proxiedClassNames.get(clazz);
-        if (proxiedClassName == null) {
-            String classSimpleName = clazz.getSimpleName();
-            proxiedClassName = classSimpleName.replace(proxySuffix, "");
-            proxiedClassNames.put(clazz, proxiedClassName);
+    public Table getTable(Class<? extends RealmObject> clazz) {
+        if (!clazz.getSuperclass().equals(RealmObject.class)) {
+            clazz = (Class<? extends RealmObject>) clazz.getSuperclass();
```
Comment (cmelchior) [inline realm/src/main/java/io/realm/Realm.java]: Use RealmProxyObject interface

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java (hunk 6 above)
Comment (cmelchior) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: I hate spaces...

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java [hunk 14]
```diff
@@ -0,0 +1,333 @@
...
+            public void emitStatement(int i, JavaWriter writer) throws IOException {
+                writer.emitStatement("return (E) %s.createUsingJsonStream(realm, reader)", proxyClasses.get(i));
+            }
+        }, writer);
+        writer.endMethod();
+        writer.emitEmptyLine();
+    }
+
+    // Emits the control flow for selecting the appropriate proxy class based on the model class
+    // Currently it is just if..else, which is inefficient for large amounts amounts of model classes.
```
Comment (kneth) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java]: The alternative is to create a map between the classes and the `ProxySwitchStatement` objects. I'm sure if it is easier to read/maintain or faster.

**Comment by kneth** [comment]
As we have reviewed face-to-face sometime ago, I believe it is ready to be merged (see my new comments though). Still, I would like to see an example of a library project.

**Comment by cmelchior** [comment]
Yes, I will add that in a separate PR in order to not make this bigger than it needs to be.

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java (hunk 14 above)
Comment (cmelchior) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java]: I have been playing around with a handcoded HashMap implementation for this compared to this if/else approach, and the numbers are not that great:

Test scenario: 20 model classes, trying to call method on every class 10.000 times, Runs on GenyMotion.

```
I/Speed﹕ List: Creating class: 1.286.494 ns.
I/Speed﹕ List: All classes (10000): 18ms.
I/Speed﹕ HashMap: Creating class: 3.091.176 ns.
I/Speed﹕ HashMap: All classes (10000): 13ms.

I/Speed﹕ List: Creating class: 724.824 ns.
I/Speed﹕ List: All classes (10000): 16ms.
I/Speed﹕ HashMap: Creating class: 2.814.679 ns.
I/Speed﹕ HashMap: All classes (10000): 14ms.

I/Speed﹕ List: Creating class: 670.570 ns.
I/Speed﹕ List: All classes (10000): 15ms.
I/Speed﹕ HashMap: Creating class: 2.031.939 ns.
I/Speed﹕ HashMap: All classes (10000): 13ms.
```
Basically we are trading a bit more runtime speed for A LOT of upfront initialisation. I only converted two of 8 methods to a HashMap implementation and each one adds a lot of overhead as they need to wrap each method call in a anonymous inner class, so we can only expect initialisation to go up as well as the increased memory usage.

So I think sticking with if/else for the time being is the best way.

File: realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java [hunk 15]
```diff
@@ -198,77 +200,77 @@ public static void validateTable(ImplicitTransaction transaction) {
         if(transaction.hasTable("class_AllTypes")) {
             Table table = transaction.getTable("class_AllTypes");
             if(table.getColumnCount() != 9) {
```
Comment (bmunkholm) [inline realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: Now that the generator is updated anyway, can you please make spacing consistent and add " " between "if" and "(" and "for" and "("?

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java (hunk 14 above)
Comment (kneth) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java]: Thanks for trying ;-)

Comment (bmunkholm) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java]: Please share the experimental code. I'm sure this can be done more elegantly & faster. The generated code also takes up some space, which we increasingly have to consider.

Comment (cmelchior) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java]: Sure, It has been added to this branch: https://github.com/realm/realm-java/tree/cm-realm-modules-hashmap

File: realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java [hunk 16]
```diff
@@ -0,0 +1,128 @@
...
+            }
+
+            RealmModule module = classElement.getAnnotation(RealmModule.class);
+            Utils.note("Processing " + classElement.getSimpleName());
+            if (module.allClasses() && module.classes().length > 0) {
+                Utils.error("Setting allClasses to true will override specific classes set in " + classElement.getSimpleName().toString());
+                return false;
+            }
+
+            String qualifiedName = ((TypeElement) classElement).getQualifiedName().toString();
```
Comment (bmunkholm) [inline realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java]: A small comment before each code section is lovely.

File: realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java [hunk 17]
```diff
@@ -0,0 +1,128 @@
...
+
+    public ModuleMetaData(RoundEnvironment env, Set<ClassMetaData> availableClasses) {
+        this.env = env;
+        this.availableClasses = availableClasses;
+        for (ClassMetaData metadata : availableClasses) {
+            classMetaData.put(metadata.getFullyQualifiedClassName(), metadata);
+        }
+    }
+
+    public boolean generate(ProcessingEnvironment processingEnv) {
```
Comment (bmunkholm) [inline realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java]: Missing comment (you have for other smaller methods

File: realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java [hunk 18]
```diff
@@ -0,0 +1,128 @@
...
+    private final RoundEnvironment env;
+    private Map<String, Set<ClassMetaData>> modules = new HashMap<String, Set<ClassMetaData>>();
+    private Map<String, Set<ClassMetaData>> libraryModules = new HashMap<String, Set<ClassMetaData>>();
+    private Map<String, ClassMetaData> classMetaData = new HashMap<String, ClassMetaData>();
+    private boolean shouldCreateDefaultModule;
+
+    public ModuleMetaData(RoundEnvironment env, Set<ClassMetaData> availableClasses) {
+        this.env = env;
+        this.availableClasses = availableClasses;
+        for (ClassMetaData metadata : availableClasses) {
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java]: rename `metadata` to `classMetadata`

File: realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java [hunk 19]
```diff
@@ -0,0 +1,128 @@
...
+public class ModuleMetaData {
+
+    private final Set<ClassMetaData> availableClasses;
+    private final RoundEnvironment env;
+    private Map<String, Set<ClassMetaData>> modules = new HashMap<String, Set<ClassMetaData>>();
+    private Map<String, Set<ClassMetaData>> libraryModules = new HashMap<String, Set<ClassMetaData>>();
+    private Map<String, ClassMetaData> classMetaData = new HashMap<String, ClassMetaData>();
+    private boolean shouldCreateDefaultModule;
+
+    public ModuleMetaData(RoundEnvironment env, Set<ClassMetaData> availableClasses) {
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java]: why isn't `availableClasses` already a `Map` to begin with?

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java [hunk 20]
```diff
@@ -75,21 +137,65 @@ public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment
...
-        if (!done) {
-            RealmValidationListGenerator validationGenerator = new RealmValidationListGenerator(processingEnv, classesToValidate);
-            RealmJSonImplGenerator jsonGenerator = new RealmJSonImplGenerator(processingEnv, classesToValidate);
-            try {
-                validationGenerator.generate();
-                jsonGenerator.generate();
-                done = true;
-            } catch (IOException e) {
-                Utils.error(e.getMessage());
+        if (!hasProcessedModules) {
```
Comment (bmunkholm) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: This check could be moved to the top.

File: realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java [hunk 21]
```diff
@@ -0,0 +1,128 @@
...
+
+        // Check that modules are setup correctly
+        for (Element classElement : env.getElementsAnnotatedWith(RealmModule.class)) {
+            if (!classElement.getKind().equals(ElementKind.CLASS)) {
+                Utils.error("The RealmModule annotation can only be applied to classes", classElement);
+                return false;
+            }
+
+            RealmModule module = classElement.getAnnotation(RealmModule.class);
+            Utils.note("Processing " + classElement.getSimpleName());
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java]: `classElement.getSimpleName()` is used in several instances. Better extract it to a local variable

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java [hunk 22]
```diff
@@ -75,21 +137,65 @@ public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment
...
+        // Create default module if needed
+        if (moduleMetaData.shouldCreateDefaultModule()) {
+            if (!createDefaultModule()) {
+                return false;
+            };
+        }
+
+        // Create RealmProxyMediators for all Realm modules
+        for (Map.Entry<String, Set<ClassMetaData>> entry : moduleMetaData.getAllModules().entrySet()) {
+            if (createMediator(Utils.stripPackage(entry.getKey()), entry.getValue())) {
```
Comment (bmunkholm) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: Arn't you missing a "!" before createMediator?
How is this not court by tests?

File: realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java [hunk 23]
```diff
@@ -0,0 +1,128 @@
...
+            if (module.allClasses() && module.classes().length > 0) {
+                Utils.error("Setting allClasses to true will override specific classes set in " + classElement.getSimpleName().toString());
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java]: What is this error message supposed to explain?

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java (hunk 6 above)
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java]: Please fix this

File: realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java (hunk 15 above)
Comment (bmunkholm) [inline realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java]: I fixed that.

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java [hunk 24]
```diff
@@ -0,0 +1,333 @@
...
+
+public class RealmProxyMediatorGenerator {
+    private final String className;
+    private ProcessingEnvironment processingEnvironment;
+    private List<String> qualifiedModelClasses = new ArrayList<String>();
+    private List<String> simpleModelClasses = new ArrayList<String>();
+    private List<String> proxyClasses = new ArrayList<String>();
+
+    private static final String REALM_PACKAGE_NAME = "io.realm";
+    private static final String EXCEPTION_MSG = "\"Could not find the generated proxy class for \" + clazz + \". \" + RealmProxyMediator.APT_NOT_EXECUTED_MESSAGE";
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java]: Long line

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java [hunk 25]
```diff
@@ -0,0 +1,333 @@
...
+
+    public RealmProxyMediatorGenerator(ProcessingEnvironment processingEnvironment, String className, Set<ClassMetaData> classesToValidate) {
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java]: Long line

File: realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java [hunk 26]
```diff
@@ -0,0 +1,134 @@
...
+    private static final List<Class<? extends RealmObject>> MODEL_CLASSES;
+    static {
+        List<Class<? extends RealmObject>> modelClasses = new ArrayList<Class<? extends RealmObject>>();
+        modelClasses.add(AllTypes.class);
+        MODEL_CLASSES = Collections.unmodifiableList(modelClasses);
+    }
+
+    @Override
+    public Table createTable(Class<? extends RealmObject> clazz, ImplicitTransaction transaction) {
+        if (clazz == null) throw new NullPointerException("A class extending RealmObject must be provided");
```
Comment (bmunkholm) [inline realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java]: Always have statements af if on separate lines.

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java [hunk 27]
```diff
@@ -0,0 +1,333 @@
...
+    }
+
+    // Emits the control flow for selecting the appropriate proxy class based on the model class
+    // Currently it is just if..else, which is inefficient for large amounts amounts of model classes.
+    // Consider switching to HashMap or similar.
+    private void emitMediatorSwitch(ProxySwitchStatement statement, JavaWriter writer) throws IOException {
+        emitMediatorSwitch(statement, writer, true);
+    }
+
+    private void emitMediatorSwitch(ProxySwitchStatement statement, JavaWriter writer, boolean nullPointerCheck) throws IOException {
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java]: Break the line

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java [hunk 28]
```diff
@@ -0,0 +1,333 @@
...
+        if (nullPointerCheck) {
+            writer.emitStatement("if (clazz == null) throw new NullPointerException(\"A class extending RealmObject must be provided\")");
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java]: Break the line

File: realm-annotations-processor/src/main/java/io/realm/processor/Utils.java [hunk 29]
```diff
@@ -93,6 +93,20 @@ public static String getGenericType(VariableElement field) {
         return genericType;
     }
 
+    /**
+     * Strips the package name from a fully qualified class name.
+     */
+    public static String stripPackage(String clazz) {
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/Utils.java]: `clazz` should only be used for actual classes, not strings. This should be `fullyQualifiedClassName` for clarity

File: realm/src/main/java/io/realm/Realm.java [hunk 30]
```diff
@@ -315,15 +306,11 @@ public void setAutoRefresh(boolean autoRefresh) {
...
     // Public because of migrations
-    public Table getTable(Class<?> clazz) {
-        final String proxySuffix = "RealmProxy";
-        String proxiedClassName = proxiedClassNames.get(clazz);
-        if (proxiedClassName == null) {
-            String classSimpleName = clazz.getSimpleName();
-            proxiedClassName = classSimpleName.replace(proxySuffix, "");
-            proxiedClassNames.put(clazz, proxiedClassName);
+    public Table getTable(Class<? extends RealmObject> clazz) {
+        if (!clazz.getSuperclass().equals(RealmObject.class)) {
```
Comment (emanuelez) [inline realm/src/main/java/io/realm/Realm.java]: `clazz.getSuperclass()` is used multiple times. Use a local variable instead

File: realm/src/main/java/io/realm/internal/RealmObjectProxy.java [hunk 31]
```diff
@@ -0,0 +1,26 @@
+/*
+ * Copyright 2014 Realm Inc.
```
Comment (emanuelez) [inline realm/src/main/java/io/realm/internal/RealmObjectProxy.java]: This should be 2015 now? Not sure

File: realm/src/main/java/io/realm/internal/RealmProxyMediator.java [hunk 32]
```diff
@@ -0,0 +1,133 @@
+/*
+ * Copyright 2014 Realm Inc.
```
Comment (emanuelez) [inline realm/src/main/java/io/realm/internal/RealmProxyMediator.java]: 2015

File: realm/src/main/java/io/realm/internal/modules/CompositeMediator.java [hunk 33]
```diff
@@ -0,0 +1,120 @@
+/*
+ * Copyright 2014 Realm Inc.
```
Comment (emanuelez) [inline realm/src/main/java/io/realm/internal/modules/CompositeMediator.java]: 2015

File: realm/src/main/java/io/realm/internal/modules/FilterableMediator.java [hunk 34]
```diff
@@ -0,0 +1,130 @@
+/*
+ * Copyright 2014 Realm Inc.
```
Comment (emanuelez) [inline realm/src/main/java/io/realm/internal/modules/FilterableMediator.java]: 2015

File: realm-annotations-processor/src/main/java/io/realm/processor/DefaultModuleGenerator.java [hunk 35]
```diff
@@ -0,0 +1,70 @@
+/*
+ * Copyright 2014 Realm Inc.
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/DefaultModuleGenerator.java]: 2015

File: realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java [hunk 36]
```diff
@@ -0,0 +1,128 @@
+/*
+ * Copyright 2014 Realm Inc.
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java]: 2015

File: realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java [hunk 37]
```diff
@@ -0,0 +1,333 @@
+
+/*
+ * Copyright 2014 Realm Inc.
```
Comment (emanuelez) [inline realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java]: 2015

File: realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java [hunk 38]
```diff
@@ -0,0 +1,75 @@
+/*
+ * Copyright 2014 Realm Inc.
```
Comment (emanuelez) [inline realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java]: 2015

File: realm/src/main/java/io/realm/internal/modules/FilterableMediator.java [hunk 39]
```diff
@@ -0,0 +1,130 @@
...
+    private RealmProxyMediator originalMediator;
+    private Set<Class<? extends RealmObject>> allowedClasses = new HashSet<Class<? extends RealmObject>>();
+
+    /**
+     * Creates a filterable Mediator.
+     *
+     * @param originalMediator      Original auto generated mediator.
+     * @param filter                Subset of classes from original mediator to allow.
+     */
+    public FilterableMediator(RealmProxyMediator originalMediator, List<Class<? extends RealmObject>> filter) {
```
Comment (emanuelez) [inline realm/src/main/java/io/realm/internal/modules/FilterableMediator.java]: `filter` does not look like a good name in this case

File: realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java (hunk 12 above)
Comment (bmunkholm) [inline realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java]: "as a" -> "By"

File: realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java (hunk 19 above)
Comment (cmelchior) [inline realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java]: This Set is used quite a few other places where having it as a Map would both be ugly an unnecessary, so I would rather just create it here.

File: realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java [hunk 40]
```diff
@@ -0,0 +1,79 @@
...
+ * reuse the modules exposed by the library if they want to use RealmClass'es from
+ * that library.
+ */
+@Retention(RetentionPolicy.CLASS)
+@Target(ElementType.TYPE)
+@Inherited
+public @interface RealmModule {
+
+    /**
+     * Setting this to true will mark this module as a library module. This will prevent Realm from generating the
```
Comment (bmunkholm) [inline realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java]: Needs some editing. Also the "RealmObjects" is not really a term we have used before.

File: realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModule.java [hunk 41]
```diff
@@ -0,0 +1,7 @@
+package io.realm;
```
Comment (bmunkholm) [inline realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModule.java]: missing header

File: realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java [hunk 42]
```diff
@@ -0,0 +1,134 @@
+package io.realm;
```
Comment (bmunkholm) [inline realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java]: missing header

File: realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java [hunk 43]
```diff
@@ -0,0 +1,134 @@
...
+    }
+
+    @Override
+    public Table createTable(Class<? extends RealmObject> clazz, ImplicitTransaction transaction) {
+        if (clazz == null) throw new NullPointerException("A class extending RealmObject must be provided");
+
+        if (clazz.equals(AllTypes.class)) {
+            return AllTypesRealmProxy.initTable(transaction);
+        } else {
+            throw new RealmException("Could not find the generated proxy class for " + clazz + ". " + RealmProxyMediator.APT_NOT_EXECUTED_MESSAGE);
```
Comment (bmunkholm) [inline realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java]: Same line many places - make private method. Same for initial check for clazz == null

File: realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModule.java (hunk 41 above)
Comment (cmelchior) [inline realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModule.java]: Autogenerated files doesn't have headers. Adding the header would break our unit tests.

File: realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java (hunk 42 above)
Comment (cmelchior) [inline realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java]: Same

File: realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java (hunk 40 above)
Comment (cmelchior) [inline realm-annotations/src/main/java/io/realm/annotations/internal/RealmModule.java]: Changed the language to something that is hopefully better.

**Comment by cmelchior** [comment]
Ready for round 2: @emanuelez @kneth @bmunkholm

**Comment by emanuelez** [comment]
I think it looks good now, but I think an ok from @bmunkholm 's critical eye is needed here

File: realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModule.java (hunk 41 above)
Comment (bmunkholm) [inline realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModule.java]: ahh - yeah - missing that it was autogenerated :-)

**Comment by bmunkholm** [comment]
:+1:

File: realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java [hunk 44]
```diff
@@ -106,7 +108,7 @@ public void compareProcessedAllTypesFile() throws Exception {
                 .processedWith(new RealmProcessor())
                 .compilesWithoutError()
                 .and()
-                .generatesSources(allTypesProxy);
+                .generatesSources(allTypesDefaultMediator, allTypesDefaultModule, allTypesDefaultMediator);
```
Comment (emanuelez) [inline realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java]: We should still check against allTypesProxy!

Comment (cmelchior) [inline realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java]: Hmm, thought that was done elsewhere. You are right, big mistake, will readd it.
