### PR TITLE
Remove log files in Realm.deleteRealm

### LINKED ISSUE #2834: Cannot delete realm
When starting up my app the first thing I am trying to delete the realm file.

The attached screenshot shows that if fails to delete the management directory.
/data/user/0/com.agrimap.mobile.android/files/default.realm.management

I checked the File.delete() method and it internally catches
android.system.ErrnoException: remove failed: ENOTEMPTY (Directory not empty)

The directory appears to have three files in it.
log_acces, log_a, log_b

screen shot 2016-05-19 at 12 09 12 pm

#### Version of Realm and tooling
Realm version(s): 0.90.1
Android Studio version: 2.1.1
Which Android version and device: Emulator - Nexus 4

### PR DESCRIPTION
**Pull request by beeender**
Close #2834

### CODE REVIEW

**Comment by bmunkholm** [comment]
@finnschiermer Please review.

**Comment by kneth** [comment]
:+1:

@finnschiermer Please see if we have overlooked some aux. files.

**Comment by kneth** [comment]
After a brief chat with @finnschiermer, it is safer to remove all files in the `.management` folder. See http://stackoverflow.com/questions/7768071/how-to-delete-directory-content-in-java how to do so.

**Comment by stk1m1** [comment]
👍

File: realm/realm-library/src/androidTest/java/io/realm/RealmTests.java [hunk 1]
```diff
@@ -1922,14 +1911,15 @@ public void run() {
         realm.beginTransaction();
         realm.createObject(AllTypes.class);
         realm.commitTransaction();
+        // Move the directory so core won't be able to delete log files
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/RealmTests.java]: Instead describe why it could happen, i.e during an upgrade of Realm where core changed the location of log files.

**Comment by cmelchior** [comment]
Apart from minor comment 👍

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java [hunk 2]
```diff
@@ -593,9 +593,14 @@ static private boolean deletes(String canonicalPath, File rootFolder, String rea
         List<File> filesToDelete = Arrays.asList(
                 new File(rootFolder, realmFileName),
                 new File(rootFolder, realmFileName + ".lock"),
+                // Old core log file naming styles
                 new File(rootFolder, realmFileName + ".log_a"),
                 new File(rootFolder, realmFileName + ".log_b"),
                 new File(rootFolder, realmFileName + ".log"),
+                // New styles
```
Comment (beeender) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: Those four lines can be removed.

**Comment by emanuelez** [comment]
👍

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java [hunk 3]
```diff
@@ -633,9 +629,19 @@ public void onResult(int count) {
...
                 String realmFileName = configuration.getRealmFileName();
                 File managementFolder = new File(realmFolder, realmFileName + management);
-                realmDeleted.set(deletes(realmFolder.getPath()+ "/" + realmFileName + management, managementFolder, realmFileName));
-                realmDeleted.set(realmDeleted.get() && deletes(canonicalPath, realmFolder, realmFileName));
 
+                // delete files in management folder and the folder
+                // there is no subfolders in the management folder
+                File[] files = managementFolder.listFiles();
+                if (files != null) {
+                    for (File file : files) {
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: Nitpick, but use a simple for loop instead to save the allocation of an iterator.

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java [hunk 4]
```diff
@@ -633,9 +629,19 @@ public void onResult(int count) {
...
+                        realmDeleted.set(realmDeleted.get() && file.delete());
+                    }
+                }
+                realmDeleted.set(realmDeleted.get() && managementFolder.delete());
+
+                // delete specific files in root folder
+                realmDeleted.set(realmDeleted.get() && deletes(canonicalPath, realmFolder, realmFileName));
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: This will override any failures set by the previous set?

**Comment by zaki50** [comment]
👍

**Comment by nhachicha** [comment]
👍

File: realm/realm-library/src/main/java/io/realm/BaseRealm.java (hunk 4 above)
Comment (kneth) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: `realmDelete()` will return true if and only if all `delete` calls return true.

Comment (zaki50) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: I think all delete operations are skipped once `realmDeleted` is set to `false`.

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: `set` will override any previous value. You need `compareAndSet` if not.

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: In this case if the management folder isn't deleted, that failure will not be detected? Or am I missing something?

Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/BaseRealm.java]: Oh wait, i'm stupid, nevermind 👍
