### PR TITLE
Nh/fixes token renew

### LINKED ISSUE #4038: SyncClient ignoring protocol error
Errors can be either client error or protocol error not both
the following [condition is false](https://github.com/realm/realm-java/blob/releases/realm/realm-library/src/main/cpp/objectserver_shared.hpp#L65-L66), which result in ignoring all recoverable errors including new tokens.

### PR DESCRIPTION
**Pull request by nhachicha**
Fixes #4038 and  #4039. preventing Sync client to renew the access token.

### CODE REVIEW

File: realm/realm-library/src/main/cpp/objectserver_shared.hpp [hunk 1]
```diff
@@ -62,7 +62,7 @@ class JniSession {
             }
         };
         auto error_handler = [weak_session_ref](std::error_code error_code, bool is_fatal, const std::string message) {
-            if (error_code.category() != realm::sync::protocol_error_category() ||
+            if (error_code.category() != realm::sync::protocol_error_category() &&
```
Comment (beeender) [inline realm/realm-library/src/main/cpp/objectserver_shared.hpp]: Seems like I put the trap here 😺

**Comment by nhachicha** [comment]
@realm/java

File: realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/BoundState.java [hunk 2]
```diff
@@ -52,7 +52,22 @@ public void onError(ObjectServerError error) {
...
+            //  the session with this token. To be safe we remove the token that has been considered by the
+            //  the server to be invalid.
+            session.getUser().removeAccessToken(session.getServerUrl());
+
+            // stop the session to avoid sending a bind to the server which will cause it to return
+            // a fatal 203 (bad refresh)
+            session.stopNativeSession();
+
+            // Create a new session & bind it
+            session.createNativeSession();
```
Comment (beeender) [inline realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/BoundState.java]: Wouldn't it be better just go to `UNBOUND` state since in the constructor there will call `stopNativeSession` and `createNativeSession`, also it will transit to `BINDING` state there.
@cmelchior

File: realm/realm-library/src/objectServer/java/io/realm/SyncUser.java [hunk 3]
```diff
@@ -392,6 +392,10 @@ private static String getManagementRealmUrl(URL authUrl) {
         }
     }
 
+    public void removeAccessToken (URI serverURL) {
```
Comment (kneth) [inline realm/realm-library/src/objectServer/java/io/realm/SyncUser.java]: Should a `public` method have documentation?

Comment (cmelchior) [inline realm/realm-library/src/objectServer/java/io/realm/SyncUser.java]: Yes, but I am doubtful we want this method to be public?

File: realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/BoundState.java [hunk 4]
```diff
@@ -52,7 +52,22 @@ public void onError(ObjectServerError error) {
...
+            //  still consider this token to be valid (based on timestamps for example)
+            //
+            //  this may cause the server to send a fatal error (203 bad refresh) if we try to bind
+            //  the session with this token. To be safe we remove the token that has been considered by the
+            //  the server to be invalid.
+            session.getUser().removeAccessToken(session.getServerUrl());
+
+            // stop the session to avoid sending a bind to the server which will cause it to return
+            // a fatal 203 (bad refresh)
+            session.stopNativeSession();
```
Comment (cmelchior) [inline realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/BoundState.java]: I would probably stop the native session before removing the access token. I'm not sure, but I think not doing it could introduce a race condition.

File: realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/BoundState.java (hunk 2 above)
Comment (cmelchior) [inline realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/BoundState.java]: It is true that UNBOUND will stop/crete the session, but it will not automatically transition to BINDING, so I think keeping this logic here makes sense
