### PR TITLE
Fix leaking file handlers.

### LINKED ISSUE #5521: File handles are not released in RealmTransformer
realm-gradle-plugin:4.1.1
Original issue: https://issuetracker.google.com/69114369
Android plugin for Gradle: 3.0.0

JarFile opened in RealmTransform is not closed, which causes issues on Windows. The issue seems to be this line: https://github.com/realm/realm-java/blob/c1302392424a3b8bed323d3164ed5f875551e174/realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy#L245

Stacktrace showing where the file got opened (and not closed) ->
[stacktrace.txt](https://github.com/realm/realm-java/files/1460873/stacktrace.txt)

There is another file handle to the same file, captured in this stacktrace ->
[stacktrace_classpool.txt](https://github.com/realm/realm-java/files/1460891/stacktrace_classpool.txt)

This one seems to be caused by not closing the javassist.JarClassPath opened on this line https://github.com/realm/realm-java/blob/c1302392424a3b8bed323d3164ed5f875551e174/realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy#L219

Thanks!

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #5521 

I don't have a Windows machine to verify this on, but by doing code review it does appear that file handlers are being leaked. Unfortunately one of the leaks are inside JavaAssist, so I reported that upstream while implementing a workaround in our end for the time being.

### CODE REVIEW

File: realm-transformer/src/main/groovy/io/realm/transformer/ManagedClassPool.groovy [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+ */
+
+package io.realm.transformer
+
+import com.android.build.api.transform.TransformInput
+import javassist.ClassPath
+import javassist.ClassPool
+
+/**
+ * This class implements the Transform API provided by the Android Gradle plugin.
```
Comment (Zhuinden) [inline realm-transformer/src/main/groovy/io/realm/transformer/ManagedClassPool.groovy]: It does?

Comment (cmelchior) [reply realm-transformer/src/main/groovy/io/realm/transformer/ManagedClassPool.groovy]: Well, part of it anyway :)

File: realm-transformer/src/main/groovy/io/realm/transformer/ManagedClassPool.groovy [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+ */
+@SuppressWarnings("GroovyUnusedDeclaration")
+class ManagedClassPool extends ClassPool implements Closeable {
+
+    def List<ClassPath> pathElements = new ArrayList<ClassPath>()
+
+    /**
+     * Constructor for creating and populating the JavAssist class pool.
+     * Remember to class {@link #close()} when done with it to avoid leaking file resources
```
Comment (nhachicha) [inline realm-transformer/src/main/groovy/io/realm/transformer/ManagedClassPool.groovy]: Remember to `call
