### PR TITLE
Javadoc for findFirstAsync

### LINKED ISSUE #4360: ChangeListener no longer triggered on a findFirstAsync, after delete
#### Goal

I have a single Token object, that I need to insert/update/delete and be notified every time this happens.
Here's what I do:

```java
        mTokenObservable = database.getRealm().where(Token.class).findFirstAsync();
        mTokenObservable.addChangeListener((RealmChangeListener<Token>) element -> {
            if (element.isValid()) {
                setAccessToken(element.accessToken);
            } else {
                // The token has been deleted
                setAccessToken(null);
            }
        });
```

- This work after the first insert, and also after updates.
- This also works after the first delete.
- But when I insert again after that, I am no longer called.
Note: I confirmed by using Realm Browser that the insert really worked.

#### Expected Results

I should be called.

#### Actual Results

On insertion after the delete, the listener is not triggered

#### Steps & Code to Reproduce

FYI: If I change my `mTokenObservable` to a list and use `findAll` instead of `findFirstAsync`, this works.

#### Code Sample

See above.

#### Version of Realm and tooling
Realm version(s): 3.0.0

Realm sync feature enabled: no

Android Studio version: Android Studio 2.4 Preview 2 Build #AI-171.3804685, built on March 15, 2017

Which Android version and device: Emulator API 23

### PR DESCRIPTION
**Pull request by beeender**
Fix #4360

### CODE REVIEW

File: realm/realm-library/src/main/java/io/realm/RealmQuery.java [hunk 1]
```diff
@@ -1915,15 +1915,14 @@ public E findFirst() {
...
-     * @return immediately an empty {@link RealmObject}. Trying to access any field on the returned object
-     * before it is loaded will throw an {@code IllegalStateException}. Use {@link RealmObject#isLoaded()} to check if
-     * the object is fully loaded or register a listener {@link io.realm.RealmObject#addChangeListener}
-     * to be notified when the query completes. If no RealmObject was found after the query completed, the returned
-     * RealmObject will have {@link RealmObject#isLoaded()} set to {@code true} and {@link RealmObject#isValid()} set to
-     * {@code false}.
+     * Similar to {@link #findFirst()} but runs asynchronously on a worker thread. An listener should be registered to
+     * the returned {@link RealmObject} to get the notification when query completes. The registered listener will also
+     * be triggered if there are changes made to the queried {@link RealmObject}. If the {@link RealmObject} is deleted,
+     * the listener will be called the last time and the query will not be re-executed.
```
Comment (cmelchior) [inline realm/realm-library/src/main/java/io/realm/RealmQuery.java]: called one last time and then stop. The query will not be re-run.
