### PR TITLE
Nh/fix 3966

### LINKED ISSUE #3966: Realm 1.2.0: removing @PrimaryKey constraint does not trigger RealmMigrationNeededException
I like the whole issue template thing, but this one really doesn't need one.

`deleteIfMigrationNeeded()` did not delete Realm after removing `@PrimaryKey` annotation.

#### Version of Realm and tooling
Realm version(s): 1.2.0

Realm sync feature enabled: no

Android Studio version: .

Which Android version and device: .

### PR DESCRIPTION
**Pull request by nhachicha**
fixes #3966

### CODE REVIEW

File: realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java [hunk 1]
```diff
@@ -954,4 +954,29 @@ public void insertOrUpdate_collection_notInTransaction() {
     public void insertOrUpdate_object_notInTransaction() {
         realm.insert(new AllTypes());
     }
+
+
+    @Test
+    public void insertOrUpdate_fromOtherRealm() {
```
Comment (cmelchior) [inline realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java]: Not sure I understand this test? It doesn't seem to be related to the primary key change?

Comment (Zhuinden) [inline realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java]: @cmelchior this is a very odd remote tracking thing because this is for https://github.com/realm/realm-java/issues/3732 which was fixed in https://github.com/realm/realm-java/pull/3755

File: CHANGELOG.md [hunk 2]
```diff
@@ -8,6 +8,7 @@
 
 * "operation not permitted" issue when creating Realm file on some devices' external storage (#3629).
 * Crash on API 10 devices (#3726).
+* Realm migration is triggered, when the primary key definition is altered (#3966).
```
Comment (nhachicha) [inline CHANGELOG.md]: I described the fix, instead of the bug

File: realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java [hunk 3]
```diff
@@ -668,6 +668,25 @@ private void emitValidateTableMethod(JavaWriter writer) throws IOException {
...
+            String fieldName = metadata.getPrimaryKey().getSimpleName().toString();
+            writer.beginControlFlow("if (!table.hasPrimaryKey())")
+                    .emitStatement("throw new RealmMigrationNeededException(sharedRealm.getPath(), \"Primary Key annotation @PrimaryKey was added.\")")
+                    .nextControlFlow("else")
+                    .beginControlFlow("if (table.getPrimaryKey() != columnInfo.%sIndex)", fieldName)
+                    .emitStatement("throw new RealmMigrationNeededException(sharedRealm.getPath(), \"Primary Key annotation definition was changed.\")")
+                    .endControlFlow()
+                    .endControlFlow();
+        } else {
+            // the current model doesn't defines a PK, make sure it's not defined in the Realm schema
```
Comment (beeender) [inline realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java]: defines -> define

File: realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java [hunk 4]
```diff
@@ -668,6 +668,25 @@ private void emitValidateTableMethod(JavaWriter writer) throws IOException {
         writer.emitStatement("final %1$s columnInfo = new %1$s(sharedRealm.getPath(), table)", columnInfoClassName());
         writer.emitEmptyLine();
 
+        // verify primary key definition was not altered
+        if (metadata.hasPrimaryKey()) {
+            // the current model defines a PK, make sure it's defined in the Realm schema
+            String fieldName = metadata.getPrimaryKey().getSimpleName().toString();
+            writer.beginControlFlow("if (!table.hasPrimaryKey())")
+                    .emitStatement("throw new RealmMigrationNeededException(sharedRealm.getPath(), \"Primary Key annotation @PrimaryKey was added.\")")
```
Comment (beeender) [inline realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java]: Better to make the exception clearer, the `fieldName` should be in the exception message. Same for the below exception.

File: realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java [hunk 5]
```diff
@@ -235,6 +235,84 @@ public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
         }
     }
 
+    @Test
+    public void removingPrimaryKeyThrows() {
+
+        // Create v0 of the Realm
+        RealmConfiguration originalConfig = configFactory.createConfigurationBuilder()
+                .schema(AllTypes.class)
```
Comment (beeender) [inline realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java]: This tests will fail after https://github.com/realm/realm-java/pull/3481 fixed.

Maybe simple use DynamicRealm to create only the `StringOnly`?

**Comment by nhachicha** [comment]
@realm/java
